### ISSUE TITLE
any plan to support maven?

### ISSUE THREAD

**Issue by superheizai** [apache/incubator-eventmesh#10]
Hi All,

     any plan to support maven ?
     For our teams,  we use maven to manage our projects. If it can be build with maven, will give us more convenience。
     thanks

**Comment by keranbingaa** [comment]
It's easy to transform gradle project to maven project，you can refer to this link: https://www.jianshu.com/p/cac7ecb81a0c

**Comment by qqeasonchen** [comment]
@superheizai can you submit a PR to support maven?
