### ISSUE TITLE
[Enhancement] Optimize some codes

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1017]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

There is some code in the project that needs to be optimized.
For example:
1.Located at: eventmesh/runtime/core/protocol/http/processor/BatchSendMessageProcessor.java

![image](https://user-images.githubusercontent.com/91315508/178439107-08fc8a84-e7c9-493b-8aeb-910d04262a84.png)

There is some commented out invalid code.

2.Located at: eventmesh/runtime/core/protocol/http/consumer/HandleMsgContext.java
![image](https://user-images.githubusercontent.com/91315508/178439537-ad522e57-a4b4-4af5-9bba-6e8e81d00d0d.png)

### Describe the solution you'd like

1.Remove the invalid code.
2.The log can be opened and then modified to the correct code.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by misselvexu** [comment]
Can I try this issues ?

**Comment by Alonexc** [comment]
> Can I try this issues ?

Of course!

**Comment by HeZean** [comment]
Hi @misselvexu, not mean to offense, but I saw you commented in many issues (including other repos) without submitting PRs, can you update the status if you no longer want to work on them? Many thanks

**Comment by KevinClair** [comment]
Has been finished, see #1134 .
