### ISSUE TITLE
[Doc] Translate the design document (cloudevents.md)

### ISSUE THREAD

**Issue by kirinzhu** [apache/incubator-eventmesh#1068]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

Please translate the docs/en/design-document/06-cloudevents.md (English version) into docs/zh/design-document/06-cloudevents.md (Chinese version).
By doing so, you can get a deeper understanding about the workflow module in EventMesh.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by HeZean** [comment]
Hi, I wanna take it
