### ISSUE TITLE
[Enhancement] Extraction of constants [WebHookOperationConstant]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1072]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/182333168-0a150301-65c8-4e15-ab13-beec76df9072.png)

### Describe the solution you'd like

Located at:eventmesh-webhook-api/src/main/java/org/apache/eventmesh/webhook/api/WebHookOperationConstant.java
Extract the constants from the image to this class.
Will "System. GetProperty (" confPath", System. The getenv (" confPath ")) "to" eventmesh - common/SRC/main/Java/org/apache/eventmesh/common/Constants "Constants of replacement.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Prakhar047** [comment]
I would like to work on this task, an you please assign this task to me?

**Comment by soundarrajan-official** [comment]
I am interested to solve this issue, so can you assign me ?
