### ISSUE TITLE
[Enhancement] Extraction of constants [TopicsHandler]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1073]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/182330241-dd504672-dd5e-441c-b17f-622131ac3d8d.png)
Extracts these constants.

### Describe the solution you'd like

Located at:eventmesh-admin-rocketmq/src/main/java/org/apache/eventmesh/admin/rocketmq/handler/TopicsHandler.java
These reused constants can be extracted to org/apache/eventmesh/admin/rocketmq/Constants.java.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by weihubeats** [comment]
please assign me
