### ISSUE TITLE
[Enhancement] Extraction of constants [NacosWebHookConfigOperation]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1076]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/182508393-a47b9e7c-8cbd-4b2f-904e-1499673abcd3.png)

### Describe the solution you'd like

Located at:eventmesh-webhook-admin/src/main/java/org/apache/eventmesh/webhook/admin/NacosWebHookConfigOperation.java
Extract the constant "webhook" and define it with "static final",just define it in this class.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Karen-W-2002** [comment]
I want to work on this, can you assign this to me? Thanks

**Comment by Alonexc** [comment]
> I want to work on this, can you assign this to me? Thanks

Of course, welcome to the eventmesh community!
