### ISSUE TITLE
[Enhancement] Extraction of constants [GithubProtocol HookConfigOperationManage WebHookController]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1077]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

located at:
org/apache/eventmesh/webhook/receive/protocol/GithubProtocol.java
org/apache/eventmesh/webhook/receive/storage/HookConfigOperationManage.java
org/apache/eventmesh/webhook/receive/WebHookController.java
The constants in the class need to be extracted.

### Describe the solution you'd like

Constants in these three classes can be extracted to the top of the current class, except for log messages and exception messages.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mroccyen** [comment]
i will try my best to do it，please assign to me

**Comment by Kavinkumar07** [comment]
Hi @Alonexc ,
I would like to work on this. Can you please assign this task to me?

**Comment by Yamilini2000** [comment]
I would like to contribute. Can you please assign me?

**Comment by liujunzxcv** [comment]
I would like to work on this
