### ISSUE TITLE
[Enhancement] Extraction of constants [ExporterConfiguration]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1078]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/182511476-be71cb22-e9b6-47f5-aeba-5205c9873df4.png)

### Describe the solution you'd like

Located at:eventmesh-trace-plugin/eventmesh-trace-api/src/main/java/org/apache/eventmesh/trace/api
We can extract the constants from the image into EventMeshTraceConstants.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by seriouszyx** [comment]
I want to choose this issue as my first contribution to the EventMesh community.

**Comment by Alonexc** [comment]
> I want to choose this issue as my first contribution to the EventMesh community.

Welcome to the eventmesh community, this pr will be merged in the next version.
