### ISSUE TITLE
[Enhancement] Extraction of constants [ZipkinConfiguration  ZipkinTraceService]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1079]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/182513054-09107167-4ab3-434d-9b5d-f3ba286b67c2.png)
![image](https://user-images.githubusercontent.com/91315508/182513163-517649de-179f-4f5a-abec-947cdac16fc9.png)

### Describe the solution you'd like

Located at:eventmesh-trace-plugin/eventmesh-trace-zipkin/src/main/java/org/apache/eventmesh/trace/zipkin
A common directory can be created, and then a ZipkinConstants class can be created to hold these constants.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by LIU-WEI-git** [comment]
Hi, I want to do this.
