### ISSUE TITLE
[Enhancement] Extraction of constants [EventMeshClientUtil CloudEventProducer]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1081]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/182539881-fa4abc01-b7be-4ad3-b143-f7ab92ecb422.png)
![image](https://user-images.githubusercontent.com/91315508/182539927-9379545a-6e35-4e68-89a2-84587ae2c7d9.png)

### Describe the solution you'd like

Located at:eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client
Extract the constants in the image, define them with "static final" and put them in this class.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by RiemannChow** [comment]
I want to choose this issue as my first contribution to the EventMesh community.

**Comment by qqeasonchen** [comment]
@RiemannChow sure ok.
