### ISSUE TITLE
[Enhancement] Extraction of constants [example module grpc http directory]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1082]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/182543845-fd944ff6-9e04-444e-bf61-8dce0ca9ba61.png)
![image](https://user-images.githubusercontent.com/91315508/182545873-74541422-accb-4290-9967-89a79ef6f834.png)
![image](https://user-images.githubusercontent.com/91315508/182546056-97f03b7f-6d30-494a-b123-91391f1b588b.png)
![image](https://user-images.githubusercontent.com/91315508/182546157-1ea3e1fa-b556-446f-a713-66bad21223ed.png)
![image](https://user-images.githubusercontent.com/91315508/182546275-1b51f000-3efd-4495-b0c3-adbc9c3ad407.png)

### Describe the solution you'd like

Located at:eventmesh-examples/src/main/java/org/apache/eventmesh/grpc and http.demo
Extract these constants from the image and put them in the ExampleConstants class in the common directory, and change all the classes that use these constants.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mroccyen** [comment]
i will try my best to do it，please assign to me

**Comment by livkovacova** [comment]
Hi, can you assign this issue to me? I would like to start work on it as it would be my first-time contribute.

**Comment by soundarrajan-official** [comment]
I am interested to solve this issue, so can you please assign me ?

**Comment by Yamilini2000** [comment]
I would like to contribute. Can you please assign me?

**Comment by Namrata1-99** [comment]
I am Interested, Can you please assign to me?

**Comment by abinaya-u** [comment]
I would like to work on this and I'm a beginner, please assign to me
