### ISSUE TITLE
[Enhancement] Extraction of constants [example module tcp directory]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1083]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/182548296-67c3458c-797e-4b77-813c-7440b1d2a7af.png)
![image](https://user-images.githubusercontent.com/91315508/182548369-1d171c32-6cd6-437a-a975-ca220b19f5ff.png)

### Describe the solution you'd like

Located at:eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/common/EventMeshTestUtils.java
Please create a UtilsConstants class in the common directory and extract all the constants from the class EventMeshTestUtils to UtilsConstants.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by heihei180** [comment]
i will fix it. pls assign to me. tks.
