### ISSUE TITLE
[Enhancement] Extraction of constants [AbstractProducer RocketMQProducerImpl RocketMQConsumerImpl]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1085]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/182563076-9be061b3-b9e7-4d21-a67c-0e8b9688d110.png)
![image](https://user-images.githubusercontent.com/91315508/182565785-01698beb-b457-49c9-8421-36fd19dc83ad.png)
![image](https://user-images.githubusercontent.com/91315508/182566761-ac13a633-81a4-4744-a4b0-b064a29d07d4.png)

### Describe the solution you'd like

Located at:eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq
AbstractProducer RocketMQProducerImpl RocketMQConsumerImpl
Extract the constants from these classes to the Constants class in the common directory.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by soundarrajan-official** [comment]
I am interested to solve this issue, so can you please assign me for this issue ?

**Comment by Alonexc** [comment]
> I am interested to solve this issue, so can you please assign me for this issue ?

@soundarrajan-official Sorry, this issue is finished and I will close it, are you interested in other issues? eventmesh you are more than welcome to participate.
