### ISSUE TITLE
[Enhancement] Extraction of constants [protocol-http module]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1087]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/182794124-bd04f71f-89ab-4b2c-961b-238a866c9675.png)
![image](https://user-images.githubusercontent.com/91315508/182794249-d294d1ca-402f-4e39-8e5f-77aff7d9028e.png)
![image](https://user-images.githubusercontent.com/91315508/182794333-e06dd54f-e090-4d41-9dc3-5db3c7ef4c43.png)

### Describe the solution you'd like

Located at:eventmesh-protocol-plugin/eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/resolver
Extract the constants from the image into the class HttpProtocolConstant.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Karen-W-2002** [comment]
I would like to work on it
