### ISSUE TITLE
[Enhancement] eventmesh server go rocketmq connector

### ISSUE THREAD

**Issue by walleliu1016** [apache/incubator-eventmesh#1123]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Complete the rocketmq connector in golang

### Describe the solution you'd like

You can refers to [https://github.com/apache/rocketmq-client-go](https://github.com/apache/rocketmq-client-go).

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by horoc** [comment]
Hi, @walleliu1016 , I wonder if any assignees are working on this task?  If not currently, I want to try this.
