### ISSUE TITLE
[Enhancement] eventmesh server go standalone connector

### ISSUE THREAD

**Issue by walleliu1016** [apache/incubator-eventmesh#1124]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Complete the standalone connector

### Describe the solution you'd like

You can refers to the standalone implemented by java

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by horoc** [comment]
I want to fix this issue, please assign it to me, thanks.
