### ISSUE TITLE
[Enhancement] eventmesh server go add ci workflow

### ISSUE THREAD

**Issue by walleliu1016** [apache/incubator-eventmesh#1131]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Add CI workflow

### Describe the solution you'd like

You can config the workflow in the github action, and peek the right CI for eventmesh server go

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by HoffmanZheng** [comment]
I'm working on this issue.

**Comment by HoffmanZheng** [comment]
@walleliu1016 Would you mind help review the PR? https://github.com/apache/incubator-eventmesh/pull/2161
IMO the failed tests are from the existing code, kind of out of my scope
