### ISSUE TITLE
[Enhancement] Eventmesh server go Makefile

### ISSUE THREAD

**Issue by walleliu1016** [apache/incubator-eventmesh#1132]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Write makefile for eventmesh server go

### Describe the solution you'd like

Include 
- build
- test
- coverage
- build docker images

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by baiyutang** [comment]
This task is finished.
