### ISSUE TITLE
[Enhancement] Extraction of constants [runtime module handler directory]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1148]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/184303857-3f8aeb50-d3ca-4f57-b3fe-3c4a8779d1c3.png)

### Describe the solution you'd like

Located at:eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler
Class name:QueryWebHookConfigByIdHandler  QueryWebHookConfigByManufacturerHandler
Please extract the constants for the images into eventmesh/runtime/constants/EventMeshConstants.

> Note: This `issue` is only for contributors who have not contributed to eventmesh and want to contribute to eventmesh, and can only be claimed once per contributor!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sreekesh93** [comment]
I will work on this issue
