### ISSUE TITLE
[Enhancement] Extraction of constants [EventMeshConsumer]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1149]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/184307577-35fe8854-8c68-46fe-8ba3-9c1f8afa2196.png)
![image](https://user-images.githubusercontent.com/91315508/184307596-cca6235d-304c-44db-93fb-bd15707efb4e.png)

### Describe the solution you'd like

Located at: 
1.eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer
2.eventmesh/runtime/core/protocol/grpc/consumer/EventMeshConsumer
The same constants exist in both classes, please extract the constants from the image to `eventmesh/runtime/constants/EventMeshConstants`.

> Note: This `issue` is only for contributors who have not contributed to eventmesh and want to contribute to eventmesh, and can only be claimed once per contributor!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by soundarrajan-official** [comment]
I am willing to contribute to this issue, so can you please assign me for this issue ?
