### ISSUE TITLE
[Enhancement] Extraction of constants [ServiceUtils]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1150]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/184310034-aa55ae07-1fcc-41b6-8b0c-2be28cfcd9f2.png)

### Describe the solution you'd like

Located at:eventmesh/runtime/core/protocol/grpc/service/ServiceUtils.java
Just extract the constants from the image and put them in this class.

> Note: This `issue` is only for contributors who have not contributed to eventmesh and want to contribute to eventmesh, and can only be claimed once per contributor!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by iamkarthikselvaraj** [comment]
Hi, I want to try it.

**Comment by qqeasonchen** [comment]
@iamkarthikselvaraj sure.
