### ISSUE TITLE
[Enhancement] Extraction of constants [runtime module http processor directory]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1151]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/184311201-06348c25-b401-455a-85d8-921c8f9dcce3.png)
![image](https://user-images.githubusercontent.com/91315508/184311218-c9e3a9e3-d8c3-4891-9cab-faea1a916f6a.png)
![image](https://user-images.githubusercontent.com/91315508/184311238-3fc939fd-0a60-46e7-bf28-2b0a6433a9dc.png)
![image](https://user-images.githubusercontent.com/91315508/184311255-602aceda-4070-4a17-9569-b1a412cc65e8.png)
![image](https://user-images.githubusercontent.com/91315508/184312019-4b77fe86-757d-44ff-93c9-ed918351f07b.png)

### Describe the solution you'd like

Located at:eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor
Class name:`LocalUnSubscribeEventProcessor`  `RemoteSubscribeEventProcessor`  `SendAsyncEventProcessor`  `RemoteUnSubscribeEventProcessor`  `ReplyMessageProcessor` `SendAsyncEventProcessor`  `SendAsyncMessageProcessor`  `SendAsyncRemoteEventProcessor`  `SendSyncMessageProcessor`
Replace the constants in these classes above with those in EventMeshConstants, if they are not in EventMeshConstants,please add this constant to EventMeshConstants.

> Note: This `issue` is only for contributors who have not contributed to eventmesh and want to contribute to eventmesh, and can only be claimed once per contributor!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Saranpjs727** [comment]
@qqeasonchen I will finish this issue

**Comment by qqeasonchen** [comment]
> @qqeasonchen I will finish this issue

sure.
