### ISSUE TITLE
[Enhancement] Extraction of constants [ClientGroupWrapper EventMeshProducer]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1152]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/184314075-c6c44752-043c-4367-9312-9101eb6a7d80.png)
![image](https://user-images.githubusercontent.com/91315508/184314092-ff0244d4-6fd4-4a31-8393-2973263eb616.png)
![image](https://user-images.githubusercontent.com/91315508/184314247-7a2fee22-369b-4356-84e4-804b0ad025e3.png)

### Describe the solution you'd like

Located at:
1.eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper
2.eventmesh/runtime/core/protocol/grpc/producer/EventMeshProducer
Class name: `ClientGroupWrapper`  `EventMeshProducer`
Replace the constants in these classes above with those in EventMeshConstants, if they are not in EventMeshConstants,please add this constant to EventMeshConstants.

> Note: This `issue` is only for contributors who have not contributed to eventmesh and want to contribute to eventmesh, and can only be claimed once per contributor!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by indhuvisu** [comment]
I would like to Contribute..requesting to assign this enhancement to me.
