### ISSUE TITLE
[Enhancement] Remove invalid code [Consumer Producer]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1153]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/184320533-7cdfb00d-a74c-4601-8301-eaa49b440b0f.png)
![image](https://user-images.githubusercontent.com/91315508/184320567-0af4cf09-b798-4698-a7a5-206701fdb345.png)

### Describe the solution you'd like

Located at:
1.eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/consumer/Consumer
2.eventmesh-connector-api/src/main/java/org/apache/eventmesh/api/producer/Producer
Remove the invalid code indicated in the image.

> Note: This `issue` is only for contributors who have not contributed to eventmesh and want to contribute to eventmesh, and can only be claimed once per contributor!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by RiemannChow** [comment]
I will finish this issue.
