### ISSUE TITLE
[Enhancement] Substitution of constants [HttpProtocolAdaptor]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1154]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/184322879-984ddd41-9ea9-40ed-8dc0-8d81d3078723.png)

### Describe the solution you'd like

Located at:eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/HttpProtocolAdaptor line 96
Replace the constants in the image with the ones in protocol/http/HttpProtocolConstant.

> Note: This `issue` is only for contributors who have not contributed to eventmesh and want to contribute to eventmesh, and can only be claimed once per contributor!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mroccyen** [comment]
@Alonexc i will try my best to do it，please assign to me

**Comment by Pragalapavithra23** [comment]
@xwm1992 can you please assign it to my name ? I can work on it
