### ISSUE TITLE
[Question] Upgrade grpc and protobuf version to support the compiling in osx aarch_64 platform

### ISSUE THREAD

**Issue by horoc** [apache/incubator-eventmesh#1155]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

Hi, when I tried to compile the project by ```gradle build```, I found currently this project can not compile in the osx aarch_64 platform, since grpc:1.17.1 and protobuf:3.5.1 do not support that architecture, the error message is like :

```
Execution failed for task ':eventmesh-protocol-plugin:eventmesh-protocol-grpc:generateProto'.
> Could not resolve all files for configuration ':eventmesh-protocol-plugin:eventmesh-protocol-grpc:protobufToolsLocator_protoc'.
   > Could not find protoc-3.5.1-osx-aarch_64.exe (com.google.protobuf:protoc:3.5.1).
```

And I searched the plugin version which supports osx aarch_64: grpc support it since v1.42.1, and protoc gen plugin support it since v3.21.1 (correct me If I’m wrong) .

and I have tried to upgrade the version and complied successfully.

```
def grpcVersion = '1.42.1' // CURRENT_GRPC_VERSION
def protobufVersion = '3.21.1'
```

So my question is, should we upgrade the version to fix that? 

If it's necessary, I am willing to submit a PR to do the upgrade, thanks.

**Comment by RiESAEX** [comment]
```
> Task :eventmesh-protocol-plugin:eventmesh-protocol-grpc:generateProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':eventmesh-protocol-plugin:eventmesh-protocol-grpc:generateProto'.
> Could not resolve all files for configuration ':eventmesh-protocol-plugin:eventmesh-protocol-grpc:protobufToolsLocator_grpc'.
   > Could not find protoc-gen-grpc-java-1.17.1-linux-aarch_64.exe (io.grpc:protoc-gen-grpc-java:1.17.1).
     Searched in the following locations:
         https://maven.aliyun.com/repository/public/io/grpc/protoc-gen-grpc-java/1.17.1/protoc-gen-grpc-java-1.17.1-linux-aarch_64.exe
```
found samiler question in centos7 aarch64
