### ISSUE TITLE
[Enhancement] Remove invalid code [ runtime module core and util directory ]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1161]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/184824826-0c6640ee-9b89-42c6-b3af-fcb002275192.png)
![image](https://user-images.githubusercontent.com/91315508/184824911-fab06ad4-0e9e-401f-b994-db9849c6a682.png)
![image](https://user-images.githubusercontent.com/91315508/184824955-2d3e7de9-27ba-48a2-b167-2da3a2ee81b8.png)
![image](https://user-images.githubusercontent.com/91315508/184824973-3cfe5b11-4062-481d-9989-8dfc744e2363.png)
![image](https://user-images.githubusercontent.com/91315508/184824997-a3fa1a96-d576-4c6c-ba1a-da22388a00a2.png)
![image](https://user-images.githubusercontent.com/91315508/184825040-a64db848-c5bd-4a4c-9043-d931b4f2a2e1.png)
![image](https://user-images.githubusercontent.com/91315508/184825079-8c1b5097-dc68-4bcf-9ba6-1a62cdbfbb6f.png)
![image](https://user-images.githubusercontent.com/91315508/184825108-01f098b8-4234-4e62-845b-994126c130f3.png)
![image](https://user-images.githubusercontent.com/91315508/184825196-03af5f25-c552-42d9-a420-9198d5ebc598.png)

### Describe the solution you'd like

Located at:org/apache/eventmesh/runtime
Class name:`MQWrapper` `ConsumerGroupTopicConfig` `HeartbeatProcessor` `BatchSendMessageV2Processor` `ReplyMessageProcessor` `SendAsyncEventProcessor` `SendAsyncMessageProcessor` `SendAsyncRemoteEventProcessor` `RemotingHelper`
Remove the invalid code from these classes (as shown in the figure).

> Note: This `issue` is only for contributors who have not contributed to eventmesh and want to contribute to eventmesh, and can only be claimed once per contributor!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by KeeProMise** [comment]
I want to fix this issue
