### ISSUE TITLE
[Doc] Reference links are not available in 03-demo.md

### ISSUE THREAD

**Issue by qqeasonchen** [apache/incubator-eventmesh#1162]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

some reference links in this[1] doc are not available now.

[1]https://github.com/apache/incubator-eventmesh/blob/master/docs/zh/instruction/03-demo.md

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by srideviabhirami** [comment]
I can fix this issue
