### ISSUE TITLE
[Doc] Deletion of redundant documents

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1165]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

![image](https://user-images.githubusercontent.com/91315508/185051334-577be4d6-1de0-4de6-8f25-078d72e6cbf1.png)
![image](https://user-images.githubusercontent.com/91315508/185051369-a762c426-2773-4b82-a142-b8ca1c8d6f75.png)
CONTRIBUTING.md has been integrated into 03-new-contributor-guidelines.md.
We can remove CONTRIBUTING.md and CONTRIBUTING.zh-CN.md (as shown in the picture).

> Note: This `issue` is only for contributors who have not contributed to eventmesh and want to contribute to eventmesh, and can only be claimed once per contributor!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by surajkrishnan-twks** [comment]
HI , I am willing to work on this issue. please assign to me.

**Comment by qqeasonchen** [comment]
@surajkrishnan-twks sure.
