### ISSUE TITLE
[Doc] Document link not working [01-store-with-docker.md]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1167]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

![image](https://user-images.githubusercontent.com/91315508/185056687-07828b0b-6218-4ae8-8544-bb3ba96d4348.png)
![image](https://user-images.githubusercontent.com/91315508/185056778-1fd8a638-479e-4d88-8f94-2dd98de41721.png)
![image](https://user-images.githubusercontent.com/91315508/185056884-d47dba72-74bf-4c68-bd7c-2675a534ef68.png)
![image](https://user-images.githubusercontent.com/91315508/185056933-0c44f7da-264c-4d43-9a24-6472c46ec970.png)
The files are located at:
docs/en/instruction/01-store-with-docker.md
These links in the documentation are not working.

> Note: This `issue` is only for contributors who have not contributed to eventmesh and want to contribute to eventmesh, and can only be claimed once per contributor!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by JayabalVelusamy** [comment]
Working on it

**Comment by JayabalVelusamy** [comment]
Created a pull request https://github.com/apache/incubator-eventmesh/pull/1573
