### ISSUE TITLE
[Doc] Image link not working [03-stream.md]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1174]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

![image](https://user-images.githubusercontent.com/91315508/186050762-439f1ce4-a8f9-419b-858d-03705eb28763.png)
Located at:docs/en/design-document/03-stream.md
03-stream.md document has images that do not show up (link not working).

> Note: This `issue` is only for contributors who have not contributed to eventmesh and want to contribute to eventmesh, and can only be claimed once per contributor!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Karen-W-2002** [comment]
I'll fix this
