### ISSUE TITLE
[Doc] Image link not working [04-schema-registry.md]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1175]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

![image](https://user-images.githubusercontent.com/91315508/186050141-c6f49ad2-cef9-47c2-843a-e5d16de0bc25.png)
Located at:docs/en/design-document/04-schema-registry.md
There are images in the document that are not showing up (links are not working).

> Note: This `issue` is only for contributors who have not contributed to eventmesh and want to contribute to eventmesh, and can only be claimed once per contributor!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Karen-W-2002** [comment]
I'll fix this

**Comment by sann3** [comment]
I like to work on this issue, please assign to me.

**Comment by qqeasonchen** [comment]
@sann3 sure
