### ISSUE TITLE
[Doc] Add a link to the document [01-store-with-docker.md 01-store.md]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1176]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

![image](https://user-images.githubusercontent.com/91315508/186054680-0a6d91ed-8cc7-46e2-bda9-26d9a4381203.png)
Located at:
docs/zh/instruction/01-store-with-docker.md
docs/zh/instruction/01-store.md
A link needs to be added here. (docs/zh/instruction/02-runtime-with-docker.md docs/zh/instruction/02-runtime.md)

> Note: This `issue` is only for contributors who have not contributed to eventmesh and want to contribute to eventmesh, and can only be claimed once per contributor!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anu-tw** [comment]
I would like to work on this.

**Comment by Anu9518** [comment]
I would like to work on this
