### ISSUE TITLE
[Question] [Broken Link] EventMesh Community Slack

### ISSUE THREAD

**Issue by VenkatDatta** [apache/incubator-eventmesh#1181]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

I'm new to the project and was looking forward to connect to people on Slack.
I tried the link posted in README.md and seems like the link is broken.

Do we have an alternate link that could be used for Slack?

Broken link: https://join.slack.com/t/apacheeventmesh/shared_invite/zt-1blhcbedu-9b7yvwAQcDs3fddZxnZXag

**Comment by qqeasonchen** [comment]
@VenkatDatta I will update it.

**Comment by qqeasonchen** [comment]
@VenkatDatta https://join.slack.com/t/apacheeventmesh/shared_invite/zt-1fal6hggw-PJ3~N6Js_ZFlEvPtpQR7jg
