### ISSUE TITLE
[Enhancement] New dependencies were introduced without updating the licenses

### ISSUE THREAD

**Issue by HeZean** [apache/incubator-eventmesh#1188]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

https://github.com/apache/incubator-eventmesh/commit/47db0db4fe5c87c627f1162e3f16c5cd298c165f introduced some new dependencies, the `known-dependencies.txt` has been updated in https://github.com/apache/incubator-eventmesh/commit/952ffd9e0393b02e5c6eeddbbbaab82f6f706b3c, but copies of [3rd-party licenses](https://github.com/apache/incubator-eventmesh/tree/master/tools/third-party-licenses) were not updated

### Describe the solution you'd like

Update licenses in the folder, you need to be care about the addition lines in https://github.com/apache/incubator-eventmesh/commit/952ffd9e0393b02e5c6eeddbbbaab82f6f706b3c

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xwm1992** [comment]
I can't figure out why this pr associate with this issue, is this correct ? @HeZean

**Comment by HeZean** [comment]
> I can't figure out why this pr associate with this issue, is this correct ? @HeZean

They are not associated, when I committed to that PR, I found the license checker CI failed in https://github.com/apache/incubator-eventmesh/pull/1105#issuecomment-1228594562 and thus opened this issue.

**Comment by HeZean** [comment]
Closing this stale issue since the license was fixed in *some* commit.
