### ISSUE TITLE
[Bug] Can't start the pulsar connector 

### ISSUE THREAD

**Issue by fengyongshe** [apache/incubator-eventmesh#1238]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux

### EventMesh version

master

### What happened

1) After gradle dist & zip , there is no pulsar connector in dir:./plugin/connector , so as other connectors(pravega,knative.etc)
2) set connector.plugin.type=pulsar  And start runtime,  Can't start connector with exception:

> Caused by: java.lang.ClassNotFoundException: org.apache.eventmesh.connector.rocketmq.producer.PulsarProducerImpl
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_161]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
>         at org.apache.eventmesh.spi.loader.JarExtensionClassLoader.lambda$loadResources$1(JarExtensionClassLoader.java:133) ~[eventmesh-spi-1.6.0-release.jar:1.6.0-release]
>         ... 16 more

It is caused by the wrong spi settings in the  gradle.properties and META-INF.eventmesh  for EventMesh-connector-plugin
![image](https://user-images.githubusercontent.com/24557090/189091280-235c98d2-4fba-42ad-9fdc-b72952477515.png)

![image](https://user-images.githubusercontent.com/24557090/189092286-2fa16a8c-55c4-4b07-997e-febc1f96af2f.png)

Should't use rocketmq tag in pulsar connector .

### How to reproduce

1. ./gradlew clean dist
2. ./gradlew installPlugin
3. bash dist/bin/start.sh    //mv pulsar connector to plugin
4. see dist/logs/eventmesh.out

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by pchengma** [comment]
Hi, Fengyong (@fengyongshe), 

Thanks for the question. I reproduced according to the above four steps but did not find the class loading bug for Knative and Pravega connectors. Knative and Pravega connector plugins can be installed in dist/plugin folder after ```./gradlew installPlugin``` and the EventMesh server can be started fine after ```bash dist/bin/start.sh```.

The class loading configuration for the Pulsar connector is in development. I think you can feel free to submit a PR to help fix the related configuration files.

**Comment by fengyongshe** [comment]
I'm willing to accomplish the pulsar connector，Please assign the work to me.  @xwm1992 @pchengma

**Comment by qqeasonchen** [comment]
@fengyongshe sure.

**Comment by fengyongshe** [comment]
Split the issue to different sub-issues for prs manageable
