### ISSUE TITLE
[Doc] Documentation Related 

### ISSUE THREAD

**Issue by dylanlee085** [apache/incubator-eventmesh#1270]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

![image](https://user-images.githubusercontent.com/16497971/190302617-98ed9c1f-ffe1-4da8-ab12-94f02edb92fa.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by liuzhuang2017** [comment]
@qqeasonchen , Hi，i will fix this pr as soon as,can you assign to me? Thanks.
