### ISSUE TITLE
[Doc] Delete duplicate documents [eventmesh-unit-test-rule.md]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1272]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

Located at:
https//github.com/apache/incubator-eventmesh/blob/master/docs/zh/desing-document/eventmesh-unit-test-rule.md

This document already exists in the contribute directory, and the current document can be deleted.

> Note: This `issue` is only for contributors who have not contributed to eventmesh and want to contribute to eventmesh, and can only be claimed once per contributor!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by luodanqing** [comment]
Yes I am willing to submit a PR!

**Comment by qqeasonchen** [comment]
@luodanqing  sure
