### ISSUE TITLE
[Bug] Cannot find the webhook protocol adaptor

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1367]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

master

### What happened

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/91315508/191880257-4b3c8d03-3817-4789-91a7-f17f09f6edc8.png">
This bug occurred while doing an eventmesh webhook test.

### How to reproduce

1. Register the webhook interface with eventmesh according to the webhook document.
2. Start an http server interface and register it with eventmesh for listening.
3. Bind the webhook interface to the GitHub repository.
4. Trigger a GitHub event.

### Debug logs

Bug cause:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/91315508/191881066-8ad4eadf-79ba-44c7-a90d-ca8a4d3e5997.png">
<img width="553" alt="image" src="https://user-images.githubusercontent.com/91315508/191881004-3e179992-0a69-471c-adff-628a037b5122.png">

Located at:org/apache/eventmesh/protocol/webhook/WebHookProtocolAdaptor line 49

The protocol type key does not correspond to it.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by cocodroid** [comment]
please assign to me

**Comment by qqeasonchen** [comment]
sure @cocodroid
