### ISSUE TITLE
[Doc] Document directory rectification [zh metrics-tracing]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1373]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

Move the documents under directory https://github.com/apache/incubator-eventmesh/tree/master/docs/zh/metrics-tracing 
to directory https://github.com/apache/incubator-eventmesh/tree/master/docs/zh/desing-document ,and delete the metrics-tracing directory.
notice:The names of documents moved to design document should be sorted by number.
eg:
<img width="354" alt="image" src="https://user-images.githubusercontent.com/91315508/191908990-065d40dd-35f2-4acb-a456-f89b18cf7a53.png">

Because some Chinese documents have not been translated, please sort and name them according to the order of the last file. The next file starts with 11-.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by manzusaka** [comment]
I can do it , please assign it to me, thanks.

**Comment by surajkrishnan-twks** [comment]
I would like to work on this , please assgin it to me

**Comment by qqeasonchen** [comment]
> I would like to work on this , please assgin it to me 
> 
> 

ok

**Comment by qqeasonchen** [comment]
> I would like to work on this , please assgin it to me 
> 
> 

sorry, this is for first time contributor.

**Comment by qqeasonchen** [comment]
> I would like to work on this , please assgin it to me 
> 
> 

sorry, this is for first time contributor.

**Comment by qqeasonchen** [comment]
> I can do it , please assign it to me, thanks.

sorry, this is for first time contributor.

**Comment by bhavy2202** [comment]
can you assign it to me?

**Comment by bhavy2202** [comment]
what about [_category_.json] file ?

**Comment by qqeasonchen** [comment]
> what about [_category_.json] file ?

@bhavy2202  you can follow en docs
