### ISSUE TITLE
[Enhancement] Add paths-ignore rule to adapt skywalking-eye's update

### ISSUE THREAD

**Issue by horoc** [apache/incubator-eventmesh#1444]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/63457588/192550895-abf5fd74-fba4-4047-865b-979578ab3a8c.png">

**Skywalking-eye** has merged a commit to remove the default ignore rule of ".txt" file which makes our Licenses Check CI pipeline fail since we have lots of ".txt"  Licenses files.

We should add the paths-ignore rule to fix that.

### Describe the solution you'd like

add ignore rule.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by xwm1992** [comment]
nice job!
