### ISSUE TITLE
[pulsar-connector]  pulsar-connector  missing acl  check 

### ISSUE THREAD

**Issue by qiaofazhan** [apache/incubator-eventmesh#1494]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

pulsar-connector  missing acl  check when  building pulsar-client ,such as  JWT；I see the following usage on the Apache Pulsar website:

PulsarClient client = PulsarClient.builder()
    .serviceUrl("pulsar://broker.example.com:6650/")
    .authentication(      AuthenticationFactory.token("eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKb2UifQ.ipevRNuRP6HflG8cFKnmUPtypruRC4fb1DWtoLL62SY") .build();

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by fengyongshe** [comment]
I am willing to accomplish it. @xwm1992

**Comment by qiaofazhan** [comment]
您好，邮件已收到，尽快给您回复。
