### ISSUE TITLE
[Bug] Invite for Slack channel seems to be no longer valid

### ISSUE THREAD

**Issue by iamkarthikselvaraj** [apache/incubator-eventmesh#1497]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

master

### What happened

Invite for Slack channel appears to be invalid in [README.md] file (https://github.com/apache/incubator-eventmesh#readme).

<img width="1792" alt="Screenshot 2022-10-07 at 4 38 46 PM" src="https://user-images.githubusercontent.com/26427259/194540594-d6a0ab21-4f28-4705-831d-157f5b3e2929.png">

### How to reproduce

NA

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by qqeasonchen** [comment]
I will update the invite link.

**Comment by qqeasonchen** [comment]
@iamkarthikselvaraj  here is the link https://join.slack.com/t/apacheeventmesh/shared_invite/zt-1hgto0wcm-KXKz8pJGUwrWdk00juaQSw
