### ISSUE TITLE
[Enhancement] No exception messages are printed

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1508]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195030918-b23e920b-2a76-42de-ac0f-f14bafee5fe5.png)
located at:org/apache/eventmesh/admin/rocketmq/handler/TopicsHandler.java line 93
This method uses a try-catch block that catches the Exception object, but the Exception is not printed out in the try block.

### Describe the solution you'd like

It is recommended to use logger to print this exception.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mroccyen** [comment]
i will try my best to do it，please assign to me

**Comment by xwm1992** [comment]
> i will try my best to do it，please assign to me

sorry this issue is for the first time contributor.

**Comment by mroccyen** [comment]
> > i will try my best to do it，please assign to me
> 
> sorry this issue is for the first time contributor.

ok

**Comment by Pragalapavithra23** [comment]
Started working on it
