### ISSUE TITLE
[Enhancement] Use try-with-resources to manage the closure of resources

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1509]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195033223-29fea5b1-e529-4b30-b102-445d9dba563c.png)
located at:org/apache/eventmesh/admin/rocketmq/handler/TopicsHandler.java line 102
This method allocates and uses an auto closeable resource. However, it manually closes the resource in a finally block. While this is correct management, it doesn't rely on the idiomatic way available to JDK 7 and above, allows for possible subtle problems, and complicates the reading of code by developers expecting the use of try-with-resources.

### Describe the solution you'd like

It is recommended to use try-with-resources to manage the closure of resources.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mroccyen** [comment]
i will try my best to do it，please assign to me

**Comment by xwm1992** [comment]
> i will try my best to do it，please assign to me

sorry this issue is for the first time contributor.

**Comment by mroccyen** [comment]
> > i will try my best to do it，please assign to me
> 
> sorry this issue is for the first time contributor.

ok

**Comment by Shrikumar18** [comment]
Hi @xwm1992, I would like to work on it, kindly assign it to me

**Comment by qqeasonchen** [comment]
sure

Shri kumar ***@***.***>于2022年10月15日 周六02:57写道：
