### ISSUE TITLE
[Enhancement] Specifies a character set name or character set object [ConfigurationWrapper]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1510]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195036001-510f4d0e-940b-4a86-82dc-e23efedfd20d.png)
located at:org/apache/eventmesh/common/config/ConfigurationWrapper.java line 87
Found a call to a method which will perform a byte to String (or String to byte) conversion, and will assume that the default platform encoding is suitable. This will cause the application behaviour to vary between platforms.

### Describe the solution you'd like

It is recommended to use an alternative API and explicitly specify the character set name or character set object.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mroccyen** [comment]
i will try my best to do it，please assign to me

**Comment by vatsal2908** [comment]
I am beginner, can you assign it to me ?

**Comment by hanshal101** [comment]
@xwm1992 Hello, It's my first time in open source projects. Can you please guide me. I would like to work on this issue.

**Comment by Alonexc** [comment]
> @xwm1992 Hello, It's my first time in open source projects. Can you please guide me. I would like to work on this issue.

Hello! This class has been replaced due to a code update, so this issue has been fixed, are you interested in other issues? We will keep updating the 'good first issue'.

**Comment by hanshal101** [comment]
@Alonexc yess I'm interested in solving issues and bugs want to start open source. Also can you please guide me during my journey. It would be really helpful.
