### ISSUE TITLE
[Enhancement] Use the {} tag to inject dynamic content into the string [WatchFileManager]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1511]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195038539-f6eb9dbd-0d72-4519-884c-b20466751a6b.png)
located at: org/apache/eventmesh/common/file/WatchFileManager.java line 67
This method uses the SLF4J or Log4j2 logger to log a String where the first (format) string is created using concatenation. You should inject dynamic content into the string using the {} tag so that String construction is delayed until the actual logging string is needed. If the logging level is high enough that this logging statement is not used, then the appended content will never be executed.

### Describe the solution you'd like

It is recommended to use the {} tag to inject dynamic content into the string.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mroccyen** [comment]
i will try my best to do it，please assign to me
