### ISSUE TITLE
[Enhancement] There is no need to declare exceptions [SubscribeResponseBody]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1515]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195050634-851ea271-8bd3-4591-8f6b-c2384f8417b4.png)
located at: org/apache/eventmesh/common/protocol/http/body/client/SubscribeResponseBody.java line 58
This method declares that it throws a checked exception that it does not throw. As this method is either a constructor, static method or private method, there is no reason for this method to declare the exception in its throws clause, and just causes calling methods to unnecessarily handle an exception that will never be thrown. The exception in question should be removed from the throws clause.

### Describe the solution you'd like

It is recommended to remove the content after throws.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mroccyen** [comment]
i will try my best to do it，please assign to me

**Comment by rinuaby13** [comment]
Hi @xwm1992 ,
I would like to work on this.

**Comment by rinuaby13** [comment]
Hi @xwm1992 ,
There was a build failure,I have resolved it can I do a PR again.

**Comment by xwm1992** [comment]
> Hi @xwm1992 , There was a build failure,I have resolved it can I do a PR again.

OK，you can add another issue to fix this.

**Comment by rinuaby13** [comment]
Hi,
I have raised a new issue #1741,can you review it.
