### ISSUE TITLE
[Enhancement] There is no need to declare exceptions [UnSubscribeResponseBody]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1517]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195051930-9931e400-4799-4a7f-919e-8f2fe149799d.png)
located at: org/apache/eventmesh/common/protocol/http/body/client/UnSubscribeResponseBody.java line 59
This method declares that it throws a checked exception that it does not throw. As this method is either a constructor, static method or private method, there is no reason for this method to declare the exception in its throws clause, and just causes calling methods to unnecessarily handle an exception that will never be thrown. The exception in question should be removed from the throws clause.

### Describe the solution you'd like

It is recommended to remove the content after throws.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mroccyen** [comment]
i will try my best to do it，please assign to me
