### ISSUE TITLE
[Enhancement] Method check a map with containsKey(), before using get() [Subscription]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1525]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195228880-d30ac9a0-cf38-4370-9df0-d317ec910fe8.png)
located at: org/apache/eventmesh/common/protocol/grpc/protos/Subscription.java line 1601 and 2598
This method checks for the presence of a key in a map using containsKey(), before attempting to fetch the value of the key using get(). This equates to doing two map lookups in a row.

### Describe the solution you'd like

 It is much simpler to just fetch the value with get, and checking for non null instead.
eg:
                Map  myMap = getSomeMap();
     	    	String value = myMap.get("foo");
    	    	if (value != null) {
    	    		....
    	    	}

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DevPJ9** [comment]
Hello, @Alonexc I would like to contribute. Can you please specify the requirement? Because I am not getting the condition by looking at the code snippet.

**Comment by Alonexc** [comment]
> Hello, @Alonexc I would like to contribute. Can you please specify the requirement? Because I am not getting the condition by looking at the code snippet.

Ok, this is a very simple code optimization, just modify it according to the example I gave.

**Comment by Alonexc** [comment]
> Hello, @Alonexc I would like to contribute. Can you please specify the requirement? Because I am not getting the condition by looking at the code snippet.

@DevPJ9 If you still don't get it, you can see that someone has already submitted a pr. e.g.
https://github.com/apache/incubator-eventmesh/pull/1550

**Comment by DevPJ9** [comment]
@Alonexc Thanks for the description. Can I raise another PR as one is already undergoing?

**Comment by Alonexc** [comment]
> @Alonexc Thanks for the description. Can I raise another PR as one is already undergoing?

Of course.

**Comment by DevPJ9** [comment]
Hello, @Alonexc I forked the repo and these changes are already done. Thanks for the opportunity. :)

**Comment by qqeasonchen** [comment]
You can find another one.

Pranjal Joshi ***@***.***>于2022年10月14日 周五22:47写道：

**Comment by Alonexc** [comment]
@DevPJ9 Yes, I will close this issue, are you interested in other issues? I will continue to organize other issues, if you are interested, please leave a comment under the issue, eventmesh welcomes your participation in contributing!

**Comment by DevPJ9** [comment]
Yes, sure @Alonexc I would be glad to contribute. :)
