### ISSUE TITLE
[Enhancement] Recalculate serialVersionUID

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1534]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195294699-eeb59caf-49fc-498e-800e-b34239ece0f6.png)
located at: org/apache/eventmesh/common/protocol/http/WebhookProtocolTransportObject.java
explanation:This serializable class defines a serialVersionUID that appears to be a computed value, however the value does not match the computed value, and thus losses it's value as version indicator. 

### Describe the solution you'd like

Recalculate the serialVersionUID.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sudharsan-gitrepo** [comment]
I would like to contribute to this issue. Thanks!

**Comment by DevPJ9** [comment]
Hello, @Alonexc I would like to contribute.

**Comment by Yamilini2000** [comment]
I would like to contribute
