### ISSUE TITLE
[Enhancement] Method uses integer based for loops to iterate over a List [QueryOperationsResponse]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1535]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195296693-9fcb6074-4bad-44a5-b134-fac537ff6344.png)
located at: org/apache/eventmesh/common/protocol/catalog/protos/QueryOperationsResponse.java line 183 and 197
explanation:This method uses an integer-based for loop to iterate over a java.util.List, by calling List.get(i) each time through the loop. The integer is not used for other reasons. It is better to use an Iterator instead, as depending on List implementation, iterators can perform better, and they also allow for exchanging of other collection types without issue.

### Describe the solution you'd like

It is recommended to use iterators or foreach.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by BrindhaEaswaramurthy** [comment]
I would like to work on this issue. Can you please assign this to me

**Comment by xwm1992** [comment]
@BrindhaEaswaramurthy Didn't see your account in our contributor list, please check if your commits associate with your github account email, not other emails.

**Comment by BrindhaEaswaramurthy** [comment]
@xwm1992 , this is the first time i'm contributing to the repo, do i need to add my account anywhere.? can u help me pls
