### ISSUE TITLE
[Enhancement] Method uses integer based for loops to iterate over a List [Subscription]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1536]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195299447-c70c9e3f-a967-4fd2-8744-2ea14e9268b5.png)
located at: org/apache/eventmesh/common/protocol/grpc/protos/Subscription.java line 2874 and 2898
explanation:This method uses an integer-based for loop to iterate over a java.util.List, by calling List.get(i) each time through the loop. The integer is not used for other reasons. It is better to use an Iterator instead, as depending on List implementation, iterators can perform better, and they also allow for exchanging of other collection types without issue.

### Describe the solution you'd like

It is recommended to use iterators or foreach.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by karthiknatarajan-27558** [comment]
Hi Alonexc , 
 I would like to work on this issue.

**Comment by xwm1992** [comment]
This issue is for the first time contributor, issue #1538 has asigned to you.

**Comment by sclark268626** [comment]
Hello Alonexc,
May I work on this issue?

**Comment by sclark268626** [comment]
Thanks!
