### ISSUE TITLE
[Enhancement] Method uses integer based for loops to iterate over a List [Heartbeat]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1537]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195299129-f3ed68e8-fb1f-47a4-9863-0ba65f9ce3e1.png)
located at: org/apache/eventmesh/common/protocol/grpc/protos/Heartbeat.java line 1066 and 1091
explanation:This method uses an integer-based for loop to iterate over a java.util.List, by calling List.get(i) each time through the loop. The integer is not used for other reasons. It is better to use an Iterator instead, as depending on List implementation, iterators can perform better, and they also allow for exchanging of other collection types without issue.

### Describe the solution you'd like

It is recommended to use iterators or foreach.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by captainbkarthick** [comment]
I wish to fix this. Requesting to assign this to me.
