### ISSUE TITLE
[Enhancement] Method uses integer based for loops to iterate over a List [BatchMessage]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1538]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195298355-af644a9a-0ae7-40cb-a31d-2c71464d8010.png)
located at: org/apache/eventmesh/common/protocol/grpc/protos/BatchMessage.java line 1668 and 1690
explanation:This method uses an integer-based for loop to iterate over a java.util.List, by calling List.get(i) each time through the loop. The integer is not used for other reasons. It is better to use an Iterator instead, as depending on List implementation, iterators can perform better, and they also allow for exchanging of other collection types without issue.

### Describe the solution you'd like

It is recommended to use iterators or foreach.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by karthiknatarajan-27558** [comment]
Hi @Alonexc , 
  I would like to contribute to this issue.

**Comment by LiuPiPiPi** [comment]
Hi @Alonexc ,
I would like to contribute to this issue.

**Comment by Alonexc** [comment]
> Hi @Alonexc , I would like to contribute to this issue.

@LiuPiPiPi You can raise a pr to fix this issue, I don't have assigned permissions.

**Comment by Orcohen33** [comment]
I would like to contribute to this issue.
