### ISSUE TITLE
[Enhancement] Remove invalid imports [KafkaProducerImpl]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1554]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195490131-4640e324-07e9-42d5-ab01-0b89c8043e46.png)
located at: org/apache/eventmesh/connector/kafka/producer/KafkaProducerImpl.java
explanation: These imports are not valid.

### Describe the solution you'd like

Remove invalid import and keep the code neat.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sreekesh93** [comment]
@Alonexc  Can you please add #hacktoberfest #HACKTOBERFEST2022 tags to the label

I can work on this thanks
