### ISSUE TITLE
[Enhancement] Remove invalid code [ProducerImpl]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1555]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195489299-b4aa3da1-5efb-4451-9cb0-d7c7ef433950.png)
located at: org/apache/eventmesh/connector/kafka/producer/ProducerImpl.java line 84
explanation: This code has been commented out.

### Describe the solution you'd like

Maybe we should remove the invalid code.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Aparna-devi-chinnu-R** [comment]
Please assign this to me
