### ISSUE TITLE
[Enhancement] Unused field

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1556]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195519944-c66423fa-2aa6-4607-8a45-fd13818e8df9.png)
located at: org/apache/eventmesh/connector/kafka/producer/KafkaProducerImpl.java  line 44
explanation: This field is never used.  Consider removing it from the class.

### Describe the solution you'd like

remove it.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by krittysv** [comment]
Hi @Alonexc ,
I would like to contribute to this issue.
