### ISSUE TITLE
[Enhancement] Method passes a concatenated string to SLF4J's or Log4j2's format string [KafkaConsumerRunner]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1557]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195520562-bc5a455d-dbe8-4360-8275-1b6e0bfafe96.png)
located at: org/apache/eventmesh/connector/kafka/consumer/KafkaConsumerRunner.java line 95
explanation: This method uses an SLF4J or Log4j2 logger to log a string, where the first (format) string is created using concatenation. You should use {} markers to inject dynamic content into the string, so that String building is delayed until the actual log string is needed. If the log level is high enough that this log statement isn't used, then the appends will never be executed.

### Describe the solution you'd like

Use the {} tag to inject dynamic content into a string.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Shrikumar18** [comment]
Hi @xwm1992 I'd like to work on this, can you please assign this to me?
