### ISSUE TITLE
[Enhancement] Reliance on default encoding [ConfigurationWrapper]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1558]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195521562-3a7ff2b5-4fb8-485a-ac98-17398e8448cc.png)
located at: org/apache/eventmesh/connector/kafka/config/ConfigurationWrapper.java line 62
explanation: Found a call to a method which will perform a byte to String (or String to byte) conversion, and will assume that the default platform encoding is suitable. This will cause the application behaviour to vary between platforms. 

### Describe the solution you'd like

It is recommended to use an alternative API and explicitly specify the character set name or character set object.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sudharsan-gitrepo** [comment]
Hello! I would like to fix this issue.
