### ISSUE TITLE
[Enhancement] Method may fail to close stream

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1559]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195522982-383cf11a-2d7a-4af6-9230-b6b70a622245.png)
located at: org/apache/eventmesh/connector/kafka/config/ConfigurationWrapper.java line 62
explanation: The method creates an IO stream object, does not assign it to any fields, pass it to other methods that might close it, or return it, and does not appear to close the stream on all paths out of the method.  This may result in a file descriptor leak. 

### Describe the solution you'd like

It is recommended to use try-with-resources to automatically manage resource closure.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by lukbaran** [comment]
Hi, I'd like to fix this issue.
