### ISSUE TITLE
[Enhancement] Unused variables and field

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1562]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195537634-31ff8851-74e1-44ed-b8ae-7e56639f8fde.png)
located at: org/apache/eventmesh/connector/kafka/consumer/KafkaConsumerImpl.java  line 36 and 43
explanation: Unused variables and fields are considered for deletion.

### Describe the solution you'd like

remove it。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by lukasz-kolasa** [comment]
I would like to fix this issue
