### ISSUE TITLE
[Enhancement] Delete unused logger

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1564]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195541261-474f4e55-45b4-428b-8f8a-d49d9dc89141.png)
located at: org/apache/eventmesh/connector/kafka/producer/ProducerImpl.java line 46
explanation: This class defines fields that are used in a local only fashion, specifically private fields or protected fields in final classes that are accessed first in each method with a store vs. a load. This field could be replaced by one or more local variables.

### Describe the solution you'd like

logger is not used, then we can consider deleting it.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by GopinathRakkiyannan** [comment]
@Alonexc could you please assign on my name. I would like to work on it

**Comment by Pragalapavithra23** [comment]
https://github.com/apache/incubator-eventmesh/pull/1572 @Alonexc
