### ISSUE TITLE
[Enhancement] Method throws alternative exception from catch block without history [ConfigurationWrapper]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1565]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195544981-245c00a1-c0a1-4361-95b9-cc8b664cc9db.png)
located at: org/apache/eventmesh/connector/kafka/config/ConfigurationWrapper.java line 60 and 68
explanation: This method catches an exception, and throws a different exception, without incorporating the original exception. Doing so hides the original source of the exception, making debugging and fixing these problems difficult. 

### Describe the solution you'd like

We can consider using logger to record raw exception information.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by krittysv** [comment]
Hi @Alonexc ,
I would like to contribute to this issue.
