### ISSUE TITLE
[Enhancement] Method throws alternative exception from catch block without history [ConsumerImpl]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1566]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/195545319-89ece492-af5e-4934-a35c-3db375855310.png)
located at: org/apache/eventmesh/connector/kafka/consumer/ConsumerImpl.java line 106 and 118
explanation: This method catches an exception, and throws a different exception, without incorporating the original exception. Doing so hides the original source of the exception, making debugging and fixing these problems difficult. 

### Describe the solution you'd like

We can consider using logger to record raw exception information.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rinuaby13** [comment]
Hi @Alonexc ,I would like to contribute to this issue.

**Comment by xwm1992** [comment]
> Hi @Alonexc ,I would like to contribute to this issue.

@rinuaby13 sure, this has asigned to you.

**Comment by DevPJ9** [comment]
Hello, @xwm1992 I would like to contribute. May I.
