### ISSUE TITLE
[Bug] ConsumerGroup subscribes multiple topics, only first topic can invoke url

### ISSUE THREAD

**Issue by abcMH1966** [apache/incubator-eventmesh#1627]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Windows

### EventMesh version

master

### What happened

When one consumer group subscribes multiple topics, only first subscription can invoke the url.

### How to reproduce

You can subscribe multiple topics by one consumer group, then publish an event with second topic. You will find that first topic works, but the second topic happens nothing.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by xwm1992** [comment]
You subscribe with the http mode, or others?

**Comment by abcMH1966** [comment]
> 

http mode
