### ISSUE TITLE
[Enhancement] Field isn't final but should be [EventMeshStartup]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1684]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197100464-f220fe9d-ef7d-46ff-9a0d-f922f5efa744.png)
located at:
org/apache/eventmesh/runtime/boot/EventMeshStartup.java line 31
analysis and explanation::
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

### Describe the solution you'd like

add final modifier field.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DeepikaMarthandanTW** [comment]
I would like to work on this issue. Can you please assign this task to me?
