### ISSUE TITLE
[Enhancement] Field isn't final but should be [EventMeshHTTPConfiguration]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1685]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197101351-d14966cf-d7ea-4987-b92f-ebb40b2abe55.png)
located at:
org/apache/eventmesh/runtime/configuration/EventMeshHTTPConfiguration.java line 40
analysis and explanation:
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

### Describe the solution you'd like

add final modifier field.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rinuaby13** [comment]
Hi @Alonexc ,I would like to work on this issue.
