### ISSUE TITLE
[Enhancement] Field isn't final but should be [http SendMessageContext]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1687]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197102631-e25c4bae-f990-427f-9c02-7a8c0b7e37a1.png)
located at:
org/apache/eventmesh/runtime/core/protocol/http/producer/SendMessageContext.java line 40
analysis and explanation:
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

### Describe the solution you'd like

add final modifier field.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by krittysv** [comment]
Hi @Alonexc ,
I would like to contribute to this issue.
