### ISSUE TITLE
[Enhancement] Field isn't final but should be [EventMeshTcpConnectionHandler]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1689]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197103083-62d3d42a-348d-4b4e-a5d7-ac4c1deeea35.png)
located at:
org/apache/eventmesh/runtime/core/protocol/tcp/client/EventMeshTcpConnectionHandler.java line 35
analysis and explanation:
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

### Describe the solution you'd like

add final modifier field.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hanish-rishen** [comment]
@xwm1992  @Alonexc i would like to work on this issue, please assign it to me.

**Comment by hanish-rishen** [comment]
i have made this PR #1752 , please have a look
