### ISSUE TITLE
[Enhancement] Field isn't final but should be [ClientGroupWrapper]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1690]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197103389-23267861-816b-43e4-af35-b43c332ac512.png)
located at:
org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java line 76
analysis and explanation:
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

### Describe the solution you'd like

add final modifier field.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Pragalapavithra23** [comment]
@Alonexc can you assign this to my name , I can work on it
