### ISSUE TITLE
[Enhancement] Possible null pointer dereference [EventMeshServer]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1693]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197125104-1e9027cd-ed23-4657-bac2-45a935aed9dc.png)
located at:
org/apache/eventmesh/runtime/boot/EventMeshServer.java line 100
analysis and explanation:
There is a branch of statement that, if executed, guarantees that a null value will be dereferenced, which would generate a NullPointerException when the code is executed.

### Describe the solution you'd like

add NPE exception check.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Pragalapavithra23** [comment]
@xwm1992 I haven't worked on this type of issue , can you please assign it to me ?
