### ISSUE TITLE
[Enhancement] Possible null pointer dereference [HeartBeatTask]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1694]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197125799-b85aee94-47e9-471d-b0c4-b7708550e76a.png)
located at:
org/apache/eventmesh/runtime/core/protocol/tcp/client/task/HeartBeatTask.java line 55、59
analysis and explanation:
There is a branch of statement that, if executed, guarantees that a null value will be dereferenced, which would generate a NullPointerException when the code is executed.

### Describe the solution you'd like

add NPE exception check.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DeepikaMarthandanTW** [comment]
I would like work on this issue. @xwm1992 could you please assign this issue to me?

**Comment by soundarrajan-official** [comment]
I tried to solve this problem
