### ISSUE TITLE
[Enhancement] Invocation of toString on an array [HelloTask]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1697]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197126813-add1b9da-3377-4f8a-9115-f0505066ff63.png)
located at:
org/apache/eventmesh/runtime/core/protocol/tcp/client/task/HelloTask.java line 76
analysis and explanation:
The code invokes toString on an array, which will generate a fairly useless result.

### Describe the solution you'd like

Use the Arrays.toString() method.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hanish-rishen** [comment]
Hi @xwm1992 @Alonexc I would like to take up this issue. Please assign it to me.

**Comment by hanish-rishen** [comment]
@qqeasonchen Made #1754 , please have a look
