### ISSUE TITLE
[Enhancement] Possible null pointer dereference due to return value of called method [BatchPublishMessageProcessor]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1698]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197127002-096bf2e0-d855-48f6-99df-d846a6fd9c85.png)
located at:
org/apache/eventmesh/runtime/core/protocol/grpc/processor/BatchPublishMessageProcessor.java line 101
analysis and explanation:
The return value from a method is dereferenced without a null check, and the return value of that method is one that should generally be checked for null. This may lead to a NullPointerException when the code is executed.

### Describe the solution you'd like

add NPE exception check.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rrpari** [comment]
Please assign this to me.
