### ISSUE TITLE
[Enhancement] Possible null pointer dereference due to return value of called method  [EventMeshConsumer]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1699]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197127240-39635d82-acf6-4ee8-bec2-c7c4b041dcb2.png)
located at:
org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java line 197 198
analysis and explanation:
The return value from a method is dereferenced without a null check, and the return value of that method is one that should generally be checked for null. This may lead to a NullPointerException when the code is executed.

### Describe the solution you'd like

add NPE exception check.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rinuaby13** [comment]
Hi @Alonexc ,
I would like to work on this issue.
