### ISSUE TITLE
[Enhancement] Possible null pointer dereference due to return value of called method  [BatchSendMessageProcessor]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1700]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

located at:
org/apache/eventmesh/runtime/core/protocol/http/processor/BatchSendMessageProcessor.java line 142
analysis and explanation:
The return value from a method is dereferenced without a null check, and the return value of that method is one that should generally be checked for null. This may lead to a NullPointerException when the code is executed.

### Describe the solution you'd like

add NPE exception check.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DeepikaMarthandanTW** [comment]
I can work on this issue. @xwm1992 could you please assign this to me?

**Comment by parvathy00** [comment]
Hi @Alonexc, I would like to work on this issue. Can you please assign this task to me?

**Comment by jayabha-jayas** [comment]
Hi, I would like to work on this issue

**Comment by Yamilini2000** [comment]
I would like to contribute. Can you please assign me?

**Comment by Namrata1-99** [comment]
I would like to contribute to this issue, can you assign me?
