### ISSUE TITLE
[Enhancement] Possible null pointer dereference due to return value of called method [ReplyMessageProcessor]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1703]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197130413-08cf8b1a-7fd1-4a9e-958e-730b421fa5c4.png)
![image](https://user-images.githubusercontent.com/91315508/197130451-39eddb6f-5de3-4a4c-a78b-310db315f3df.png)
located at:
org/apache/eventmesh/runtime/core/protocol/http/processor/ReplyMessageProcessor.java line 155 185
analysis and explanation:
The return value from a method is dereferenced without a null check, and the return value of that method is one that should generally be checked for null. This may lead to a NullPointerException when the code is executed.

### Describe the solution you'd like

add NPE exception check.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jayabha-jayas** [comment]
hi, i would like to work on this issue
