### ISSUE TITLE
[Enhancement] Possible null pointer dereference due to return value of called method [SendAsyncEventProcessor]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1704]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197129977-dde79348-f50c-4b84-bfb3-0c0cdb93a792.png)
![image](https://user-images.githubusercontent.com/91315508/197129988-39c01e85-828f-48db-b708-0b686bfdf58c.png)
![image](https://user-images.githubusercontent.com/91315508/197130004-190c5375-b770-4443-bc59-c31f6edeab4d.png)
![image](https://user-images.githubusercontent.com/91315508/197130014-449874f0-c3f2-4488-b9cf-21ae840350c8.png)
located at:
org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncEventProcessor.java line 141-143 156 173-175 203
analysis and explanation:
The return value from a method is dereferenced without a null check, and the return value of that method is one that should generally be checked for null. This may lead to a NullPointerException when the code is executed.

### Describe the solution you'd like

add NPE exception check.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SreeRanjani14** [comment]
@Alonexc I have raised a PR for this. Kindly check [1771](https://github.com/apache/incubator-eventmesh/pull/1771)
