### ISSUE TITLE
[Enhancement] Possible null pointer dereference due to return value of called method [SendAsyncMessageProcessor]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1705]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197130621-10fcb234-3c17-4725-8a77-a88d8689b833.png)
![image](https://user-images.githubusercontent.com/91315508/197130634-025f9e29-bba8-4719-b43b-2397647c905e.png)
![image](https://user-images.githubusercontent.com/91315508/197130646-5a9ee8e6-ed47-4cfb-ab05-62083e21cbeb.png)
located at:
org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncMessageProcessor.java line 173-175 229 230 234
analysis and explanation:
The return value from a method is dereferenced without a null check, and the return value of that method is one that should generally be checked for null. This may lead to a NullPointerException when the code is executed.

### Describe the solution you'd like

add NPE exception check.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by NewtonVan** [comment]
@xwm1992 Hi, I'm a newbie on eventmesh and I think I'm capable of fixing this issue. Would u pls assign this to me?
