### ISSUE TITLE
[Enhancement] Possible null pointer dereference due to return value of called method [SendAsyncRemoteEventProcessor]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1706]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197130823-ac484e6e-02f9-492a-a3b5-79357844ab2e.png)
![image](https://user-images.githubusercontent.com/91315508/197130839-de456bdb-8045-4920-ac63-7f1c8b5beecf.png)
![image](https://user-images.githubusercontent.com/91315508/197130851-337dda44-2670-4b9a-a688-ac77385b1339.png)
![image](https://user-images.githubusercontent.com/91315508/197130862-daa2941b-d37c-4ed5-8950-e505063fea00.png)
located at:
org/apache/eventmesh/runtime/core/protocol/http/processor/SendAsyncRemoteEventProcessor.java 170-172 185 202-204 232
analysis and explanation:
The return value from a method is dereferenced without a null check, and the return value of that method is one that should generally be checked for null. This may lead to a NullPointerException when the code is executed.

### Describe the solution you'd like

add NPE exception check.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by NewtonVan** [comment]
@xwm1992 Hi, I'm a newbie on eventmesh and I think I'm capable of fixing this issue. Would u pls assign this to me?
