### ISSUE TITLE
[Enhancement] Possible null pointer dereference due to return value of called method  [ClientSessionGroupMapping]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1708]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197131221-b63a0c51-e640-4724-8e9f-abb978f2a1ea.png)
![image](https://user-images.githubusercontent.com/91315508/197131234-9d6fd3af-7e11-4ca0-8ca6-88640efdde20.png)
located at:
org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientSessionGroupMapping.java line 250 269 275 286-288 300 309 301 329 330 335-337 340-342 347 348 351 352 358 359
analysis and explanation:
The return value from a method is dereferenced without a null check, and the return value of that method is one that should generally be checked for null. This may lead to a NullPointerException when the code is executed.

### Describe the solution you'd like

add NPE exception check.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by NewtonVan** [comment]
@xwm1992 I think I'm capable of fixing this issue, would u pls assign this to me？

**Comment by Yamilini2000** [comment]
I would like to contribute. Can you please assign me?
