### ISSUE TITLE
[Enhancement] Possible null pointer dereference due to return value of called method [tcp client Session]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1709]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197131680-17eda811-d92a-493a-983a-11bb720b1d7b.png)
![image](https://user-images.githubusercontent.com/91315508/197131702-2106b246-e821-4322-8662-a604a943592e.png)
![image](https://user-images.githubusercontent.com/91315508/197131718-6890b688-6cec-4b90-80d4-3b0b29660526.png)
![image](https://user-images.githubusercontent.com/91315508/197131727-087f79f2-c8da-4414-9ac9-af77dffb5a2b.png)
located at:
org/apache/eventmesh/runtime/core/protocol/tcp/client/session/Session.java line 170 172 174 182 184 185 221 236
analysis and explanation:
The return value from a method is dereferenced without a null check, and the return value of that method is one that should generally be checked for null. This may lead to a NullPointerException when the code is executed.

### Describe the solution you'd like

add NPE exception check.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by NewtonVan** [comment]
Hi @qqeasonchen, I think I'm capable of fixing this issue, would u pls assign this to me?
