### ISSUE TITLE
[Enhancement] Possible null pointer dereference due to return value of called method [DownStreamMsgContext]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1711]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197132193-5fc29d42-9142-4184-8c9a-9e6c1849dc4b.png)
located at:
org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/DownStreamMsgContext.java line 137 138
analysis and explanation:
The return value from a method is dereferenced without a null check, and the return value of that method is one that should generally be checked for null. This may lead to a NullPointerException when the code is executed.

### Describe the solution you'd like

add NPE exception check.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by srideviabhirami** [comment]
I would like to work on this issue
