### ISSUE TITLE
[Enhancement] Possible null pointer dereference due to return value of called method [SessionPusher]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1712]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197133663-9bd21cb9-3380-45f3-942c-e8a45035fcc6.png)
![image](https://user-images.githubusercontent.com/91315508/197133674-c9d267ad-53fe-471e-99ef-81f46edc8511.png)
located at:
org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/SessionPusher.java line 110 139
analysis and explanation:
The return value from a method is dereferenced without a null check, and the return value of that method is one that should generally be checked for null. This may lead to a NullPointerException when the code is executed.

### Describe the solution you'd like

add NPE exception check.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by srideviabhirami** [comment]
I would like to work on this issue
