### ISSUE TITLE
[Enhancement] Possible null pointer dereference due to return value of called method [SessionSender]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1713]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197133927-84e19e3c-da41-4abf-9b59-97fc9fea500d.png)
![image](https://user-images.githubusercontent.com/91315508/197133936-8d6709a7-2842-476a-b976-51b120fdd054.png)
![image](https://user-images.githubusercontent.com/91315508/197133948-50edddd6-15d8-4eb9-85d4-97bd2b30e30f.png)
![image](https://user-images.githubusercontent.com/91315508/197133959-5a5b709d-7b5c-482f-a17d-8d7ba9ac8bcf.png)
located at:
org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/SessionSender.java line 108 124 132 139 165
analysis and explanation:
The return value from a method is dereferenced without a null check, and the return value of that method is one that should generally be checked for null. This may lead to a NullPointerException when the code is executed.

### Describe the solution you'd like

add NPE exception check.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by srideviabhirami** [comment]
I would like to work on this issue
