### ISSUE TITLE
[Enhancement] Possible null pointer dereference due to return value of called method [UpStreamMsgContext]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1714]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197134200-ca915c66-bb82-4501-b88a-6a3aa980a24c.png)
located at:
org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/UpStreamMsgContext.java line 139
analysis and explanation:
The return value from a method is dereferenced without a null check, and the return value of that method is one that should generally be checked for null. This may lead to a NullPointerException when the code is executed.

### Describe the solution you'd like

add NPE exception check.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SreeRanjani14** [comment]
@Alonexc I would like to work on this issue

**Comment by SreeRanjani14** [comment]
I have raised a PR [#1769](https://github.com/apache/incubator-eventmesh/pull/1769)
