### ISSUE TITLE
[Enhancement] Possible null pointer dereference due to return value of called method [MessageTransferTask]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1715]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197134465-214a3005-f7fa-4a14-a552-8dc117b43527.png)
![image](https://user-images.githubusercontent.com/91315508/197134502-c3618a84-8965-4f60-aa7f-3814935a5bc5.png)
located at: 
org/apache/eventmesh/runtime/core/protocol/tcp/client/task/MessageTransferTask.java line 113 258
analysis and explanation:
The return value from a method is dereferenced without a null check, and the return value of that method is one that should generally be checked for null. This may lead to a NullPointerException when the code is executed.

### Describe the solution you'd like

add NPE exception check.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by soundarrajan-official** [comment]
I tried to solve this problem
