### ISSUE TITLE
[Enhancement] Possible null pointer dereference due to return value of called method [Utils]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1718]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197135090-bf3ce87d-d5ad-451f-81a3-3dbe03d4027f.png)
located at:
org/apache/eventmesh/runtime/util/Utils.java line 73
analysis and explanation:
The return value from a method is dereferenced without a null check, and the return value of that method is one that should generally be checked for null. This may lead to a NullPointerException when the code is executed.

### Describe the solution you'd like

add NPE exception check.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SreeRanjani14** [comment]
@Alonexc I would like to work on this issue

**Comment by SreeRanjani14** [comment]
I have a raised a PR. Kindly check [1774](https://github.com/apache/incubator-eventmesh/pull/1774)
