### ISSUE TITLE
[Enhancement] Unused field

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1719]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197135322-b7490b16-6b04-4e5f-9c4c-75ec33153e37.png)
located at:
org/apache/eventmesh/runtime/boot/EventMeshTCPServer.java 133
analysis and explanation:
Unused field: org.apache.eventmesh.runtime.boot.EventMeshTCPServer.tcpRegisterTask

### Describe the solution you'd like

This field is never used,consider removing it from the class.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DeepikaMarthandanTW** [comment]
I would like to work on this issue. @Alonexc @xwm1992 Can you please assign this task to me?
