### ISSUE TITLE
[Enhancement] Method concatenates strings using + in a loop [RedirectClientByIpPortHandler]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1720]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197135628-93b832d7-c2ca-4f71-8f9c-0686ee58acfa.png)
located at:
org/apache/eventmesh/runtime/admin/handler/RedirectClientByIpPortHandler.java line 82 83
analysis and explanation:
The method seems to be building a String using concatenation in a loop. In each iteration, the String is converted to a StringBuffer/StringBuilder, appended to, and converted back to a String. This can lead to a cost quadratic in the number of iterations, as the growing string is recopied in each iteration.

### Describe the solution you'd like

Use the StringBuilder, append() method instead.
![image](https://user-images.githubusercontent.com/91315508/197135813-b35e43c6-5120-46aa-af20-77af313dbc1f.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DeepikaMarthandanTW** [comment]
I would like to work on this issue. @xwm1992 Can you please assign this task to me?
