### ISSUE TITLE
[Enhancement] Method concatenates strings using + in a loop [ShowClientHandler]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1722]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197137661-5cc5cded-6497-4fd9-b9e5-804479becdf6.png)
located at:
org/apache/eventmesh/runtime/admin/handler/ShowClientHandler.java line 74
analysis and explanation:
The method seems to be building a String using concatenation in a loop. In each iteration, the String is converted to a StringBuffer/StringBuilder, appended to, and converted back to a String. This can lead to a cost quadratic in the number of iterations, as the growing string is recopied in each iteration.

### Describe the solution you'd like

Use the StringBuilder, append() method instead.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Pragalapavithra23** [comment]
@xwm1992 , I can work on this , please assign it to me
