### ISSUE TITLE
[Enhancement] Method concatenates strings using + in a loop [ShowListenClientByTopicHandler]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1723]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197137892-286084a2-1a5a-44e6-b035-06b61a198ef1.png)
located at:
org/apache/eventmesh/runtime/admin/handler/ShowListenClientByTopicHandler.java 71 74
analysis and explanation:
The method seems to be building a String using concatenation in a loop. In each iteration, the String is converted to a StringBuffer/StringBuilder, appended to, and converted back to a String. This can lead to a cost quadratic in the number of iterations, as the growing string is recopied in each iteration.

### Describe the solution you'd like

Use the StringBuilder, append() method instead.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Pragalapavithra23** [comment]
@xwm1992 I can work on this , please assign it to me

**Comment by xwm1992** [comment]
> @xwm1992 I can work on this , please assign it to me

Sorry, these issues are labeled as `good first issue` for first time contributors.

**Comment by MaheshGPai** [comment]
Can this be assigned to me?
