### ISSUE TITLE
[Enhancement] Inefficient use of keyset iterator instead of entrySet iterator [SubscribeProcessor]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#1726]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/197138893-966f21d7-07fd-4276-a71a-78fba469cfeb.png)
located at:
org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java line 251
analysis and explanation:
This method accesses the value of a Map entry, using a key that was retrieved from a keySet iterator. It is more efficient to use an iterator on the entrySet of the map, to avoid the Map.get(key) lookup.

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/197139034-31c5d07d-86ff-45a2-b943-873be4430831.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xwm1992** [comment]
> I would like to work on this issue. @xwm1992 Can you please assign this task to me?

Sorry, these issues are labeled as good first issue for first time contributors.

**Comment by Kavisankar-TW** [comment]
Hi @xwm1992,
I would like to work on this. Can you please assign this task to me?

**Comment by Kavinkumar07** [comment]
I would like to work on this. Can you please assign this task to me?
