### ISSUE TITLE
[Enhancement] Use the methods that have been extracted [rocketmq ConfigurationWrapper]

### ISSUE THREAD

**Issue by dinghuang** [apache/incubator-eventmesh#1889]
![image](https://user-images.githubusercontent.com/20722776/197991475-d3046e4b-1d5a-4536-912a-9b9df947c9fe.png)

located at:
org/apache/eventmesh/connector/rocketmq/config/ConfigurationWrapper.java line 65
Replace the code in the image using the method that has been extracted.
this method is located at:
org/apache/eventmesh/common/utils/PropertiesUtils.java loadPropertiesWhenFileExist

**Comment by NewtonVan** [comment]
I'll try my best to fix this, would u pls assign this to me?

**Comment by NewtonVan** [comment]
> I'll try my best to fix this, would u pls assign this to me?

@xwm1992

**Comment by dinghuang** [comment]
I have already push a commit to solve it.
