### ISSUE TITLE
[Enhancement] There is no need to use return for a void method

### ISSUE THREAD

**Issue by rinuaby13** [apache/incubator-eventmesh#1977]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Located at:java/org/apache/eventmesh/runtime/core/protocol/http/consumer/ConsumerManager.java 

The onChange method is a void method and returns are unnecessary in void function.

### Describe the solution you'd like

Removing unnecessary return statement in ConsumerManager.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by SreeRanjani14** [comment]
@rinuaby13 I have raised a PR for this [1990](https://github.com/apache/incubator-eventmesh/pull/1990). Kindly check this
