### ISSUE TITLE
[Enhancement] Lambda can be replaced with call qualifier 

### ISSUE THREAD

**Issue by dinghuang** [apache/incubator-eventmesh#1980]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

located in RocketMQBinaryMessageReader.java(59)

### Describe the solution you'd like

 this.headers.forEach((k, v) -> fn.accept(k, v)); 

can be replace to 

 this.headers.forEach(fn);

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by Yamilini2000** [comment]
I'm willing to contribute. Can you assign this task to me?
