### ISSUE TITLE
Support Kafka connector plugin and Kafka as event store

### ISSUE THREAD

**Issue by xwm1992** [apache/incubator-eventmesh#199]
Support Kafka connector to deliver event to Kafka, and please help me how can i implement this feature.

**Comment by MajorHe1** [comment]
ok, this feature looks good, you can do this by referring to defibus or rocketmq connector implementations

**Comment by keranbingaa** [comment]
yes, you can implement the interface defined under the eventmesh-connector-api module, then pub/sub the events to kafka event store

**Comment by xwm1992** [comment]
ok, i'll have a look and try to handle this feature.

**Comment by ruanwenjun** [comment]
@xwm1992 Does any guys work for this issue, if there is no one, I will try to implement the Kafka connector.

**Comment by xwm1992** [comment]
> @xwm1992 Does any guys work for this issue, if there is no one, I will try to implement the Kafka connector.

@ruanwenjun no one has dealt with this issue yet, you are welcome to deal with it , looking forward your pull request.
you may create a new branch for version 1.3.0 to complete this feature is better.

**Comment by qqeasonchen** [comment]
@ruanwenjun welcome to contribute.

**Comment by xwm1992** [comment]
@ruanwenjun   此处测试，有相关异常信息输出。 
![image](https://user-images.githubusercontent.com/13237619/121111546-a618ba80-c841-11eb-929b-7804cf26d0e9.png)

**Comment by xwm1992** [comment]
> @xwm1992 Thanks, I have resolved this problem.

Ok, I will have a full test for your pull request by using kafka connector pub/sub messages.

**Comment by Markliniubility** [comment]
Hi I am working on this issue this summer!
