### ISSUE TITLE
Could we support different protocol  for client connect with eventMesh

### ISSUE THREAD

**Issue by chenyi19851209** [apache/incubator-eventmesh#200]
i want to use other service components connect with eventMesh， how can i transfer the communication protocol.
e.g. Prometheus connect with eventMesh to pub events

**Comment by xwm1992** [comment]
This is a good question, at present there are two ways for you to connect with eventMesh:

1. use eventmesh java sdk and followed the sdk method and protocol
2. use http client and set the message format refering to message headers/body in sdk

**Comment by iNanos** [comment]
We will support a protocol parser which can dynamic run on the eventmesh like connector now in the eventmesh, you can personalize implements the interface and plug in the protocal parser to the eventmesh. 
e.g. we will support cloudEvents for http and parse it in eventmesh

**Comment by ruanwenjun** [comment]
@iNanos Can we decouple the implementation of the protocol by using plugin?

**Comment by qqeasonchen** [comment]
> @iNanos Can we decouple the implementation of the protocol by using plugin?

Sure
