### ISSUE TITLE
After the exception occurs in the method, the offset of the pull message request does not change and does not scroll forward incrementally

### ISSUE THREAD

**Issue by mattmao0913** [apache/incubator-eventmesh#204]
Issue description :
      After the exception occurs in the handleMessage method, the offset of the pull message request does not change and does not scroll forward incrementally. the pull request's attribute offset and unique does not change.

**Comment by wqliang** [comment]
please supply your exception images or other detail information

**Comment by xwm1992** [comment]
I have tried the scene you mentioned, but I can't find the problem you said.May be you can pull the newest code and have a try.
