### ISSUE TITLE
Support FOSSA for Security Management

### ISSUE THREAD

**Issue by vongosling** [apache/incubator-eventmesh#208]
1. License link should link to your license file instead of the Apache license v2 website
2. Attach the result after integrate FOSSA, you could attache the script like the following:

<a href="https://app.fossa.com/projects/git%2Bgithub.com%2Fvongosling%2Fjvm-serializer?ref=badge_large" alt="FOSSA Status"><img src="https://app.fossa.com/api/projects/git%2Bgithub.com%2Fvongosling%2Fjvm-serializer.svg?type=large"/></a>

**Comment by xwm1992** [comment]
> License link should link to your license file instead of the Apache license v2 website
Attach the result after integrate FOSSA, you could attache the script like the following:

Thank you for your advice, i'll try it later.

**Comment by vongosling** [comment]
Since enter ASF, we could not import this feature. close temporarily.
