### ISSUE TITLE
[Enhancement]Use try-with-resources to manage resources [ShowListenClientByTopicHandler]

### ISSUE THREAD

**Issue by 1193324541** [apache/incubator-eventmesh#2140]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Use try-with-resources to manage resources [ShowListenClientByTopicHandler]

### Describe the solution you'd like

Use try-with-resources to manage resources [ShowListenClientByTopicHandler]

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by 1193324541** [comment]
收到

**Comment by Alonexc** [comment]
@1193324541 Hello, it would be better to change your issue title to this --> Use try-with-resources to manage resources [ShowListenClientByTopicHandler]
