### ISSUE TITLE
 Method stores return result in local before immediately returning it

### ISSUE THREAD

**Issue by zhudawan** [apache/incubator-eventmesh#2158]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Method stores return result in local before immediately returning it [ConsumerManager]        ConsumerManager261

### Describe the solution you'd like

Method stores return result in local before immediately returning it [ConsumerManager]        ConsumerManager261 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by MajorHe1** [comment]
already fix in #2160
