### ISSUE TITLE
[Enhancement] Workflow Feature Implementation: Event Filter/Validate

### ISSUE THREAD

**Issue by walterlife** [apache/incubator-eventmesh#2190]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Event Filter/Validate based Serverlessworkflow Spec

### Describe the solution you'd like

Event Filter/Validate based Serverlessworkflow Spec

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by horoc** [comment]
I'd like to try this feature, could you help to assign it to me?
