### ISSUE TITLE
[Enhancement] Reliance on default encoding [PinpointConfiguration]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2238]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/203271223-afc9b05d-58f7-4656-93e1-e61be814b13e.png)
located at:
org/apache/eventmesh/trace/pinpoint/config/PinpointConfiguration.java line 127
analysis and explanation:
Found a call to a method which will perform a byte to String (or String to byte) conversion, and will assume that the default platform encoding is suitable. This will cause the application behaviour to vary between platforms. Use an alternative API and specify a charset name or Charset object explicitly.

### Describe the solution you'd like

use the integrated method.
reference:
![image](https://user-images.githubusercontent.com/91315508/203271602-d57af422-ec48-4502-b93d-777352bdf347.png)

this method is located at:
org/apache/eventmesh/common/utils/PropertiesUtils.java loadPropertiesWhenFileExist

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
