### ISSUE TITLE
[Enhancement] Method may fail to close stream and reliance on default encoding [PinpointConfiguration]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2239]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/203272276-d897e9bd-4fa8-4560-ac4e-6da287fc57d8.png)
located at:
org/apache/eventmesh/trace/pinpoint/config/PinpointConfiguration.java line 117
analysis and explanation:
1. The method creates an IO stream object, does not assign it to any fields, pass it to other methods that might close it, or return it, and does not appear to close the stream on all paths out of the method.  This may result in a file descriptor leak.  It is generally a good idea to use a finally block to ensure that streams are closed.
2. Found a call to a method which will perform a byte to String (or String to byte) conversion, and will assume that the default platform encoding is suitable. This will cause the application behaviour to vary between platforms. Use an alternative API and specify a charset name or Charset object explicitly.

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/203272385-fa77baea-de5b-4937-9b7c-4441b69133a0.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by LiuPiPiPi** [comment]
Hi, I want to fix this bug. @Alonexc
