### ISSUE TITLE
[Enhancement]  Method needlessly boxes a boolean constant [PinpointSpanExporter]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2240]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/203272871-3c294c1e-afa6-4a05-a499-c26809505b91.png)
located at:
org/apache/eventmesh/trace/pinpoint/exporter/PinpointSpanExporter.java line 169
analysis and explanation:
This method assigns a Boxed boolean constant to a primitive boolean variable, or assigns a primitive boolean constant to a Boxed boolean variable. Use the correct constant for the variable desired.

### Describe the solution you'd like

It is sufficient to use the constant value true directly, no need to use boxed Boolean constants.
reference:
![image](https://user-images.githubusercontent.com/91315508/203272685-bc5294cb-50bb-488a-94fa-9e7e353e1dcf.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by LiuPiPiPi** [comment]
Hi, I want to fix this bug. @Alonexc
