### ISSUE TITLE
[Enhancement] Method needlessly boxes a boolean constant [NacosWebHookConfigOperation]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2243]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/203273959-bb660691-8c3b-409b-b225-30a462c32d83.png)
located at:
org/apache/eventmesh/webhook/admin/NacosWebHookConfigOperation.java line 108 124
analysis and explanation:
This method assigns a Boxed boolean constant to a primitive boolean variable, or assigns a primitive boolean constant to a Boxed boolean variable. Use the correct constant for the variable desired.

### Describe the solution you'd like

fix reference:
![image](https://user-images.githubusercontent.com/91315508/203274004-e846cec4-e2d6-49f8-b7c7-eea3c411d04d.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Bigotry-zb** [comment]
Hi, I want to do this.

**Comment by LIU-WEI-git** [comment]
Welcome, @Bigotry-zb.
