### ISSUE TITLE
[Enhancement] Method creates local variable-based synchronized collection

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2245]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/203457343-0370ad6b-6d21-4c1b-98ef-6973b9482b43.png)
located at:
org/apache/eventmesh/webhook/admin/FileWebHookConfigOperation.java line 136
analysis and explanation:
This method creates a synchronized collection and stores the reference to it in a local variable. As local variables are by definition thread-safe, it seems questionable that this collection needs to be synchronized.

### Describe the solution you'd like

Change to use StringBuilder.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by LiuPiPiPi** [comment]
Hi, I want to fix this bug. @Alonexc
