### ISSUE TITLE
[Enhancement] Method throws alternative exception from catch block without history [AdminWebHookConfigOperationManage]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2246]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/203457460-f5503237-162a-4983-96a8-2c872c19b96a.png)
located at:
org/apache/eventmesh/webhook/admin/AdminWebHookConfigOperationManage.java line 77
analysis and explanation:
This method catches an exception, and throws a different exception, without incorporating the original exception. Doing so hides the original source of the exception, making debugging and fixing these problems difficult. It is better to use the constructor of this new exception that takes an original exception so that this detail can be passed along to the user. If this exception has no constructor that takes an initial cause parameter, use the initCause method to initialize it instead.

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/203457522-c5944a51-c942-418a-8364-8174e64f361a.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by weihubeats** [comment]
This task has been completed, so it can be closed

**Comment by xwm1992** [comment]
@weihubeats please help to figure out which pr associate this issue

**Comment by weihubeats** [comment]
Sorry, misread, I now mention a pr
