### ISSUE TITLE
[Enhancement] 'assertTrue()' can be simplified to 'assertEquals()'

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2249]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/203457855-e3d29aa3-b604-424e-b707-49e69e37369a.png)
located at:
org/apache/eventmesh/webhook/admin/FileWebHookConfigOperationTest.java

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/203457885-d666d45a-f82a-4298-9e1e-403edbd89641.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by 9luchai** [comment]
I want to fix this issue.

**Comment by xwm1992** [comment]
@9luchai welcome～
