### ISSUE TITLE
problems in the doc and code

### ISSUE THREAD

**Issue by sunxi92** [apache/incubator-eventmesh#225]
the problem in the code:
At present，the eventmesh-runtime package is missing in the master branch and the released version.
the problems in the doc:
1.QuickStart of the Eventmesh-runtime has an error : in the part of 1.4， "cd bin" should be changed to "cd conf"
2.The script of "runadmin.sh" in the QuickStart of eventmesh-sdk-java can not be found in the project
3.The dependency package is missing in the QuickStart of the eventmesh-sdk-java，when project use sdk to connect eventmesh
4.the doc on how to use the API is missing
5.the best practice in the doc is missing
6.the doc lacks a detailed description of the supported functions,which can be specific to the design scheme and implementation
7.the introduction of the items in the configuration files is missing from the doc

**Comment by qqeasonchen** [comment]
@sunxi92 Do you have any other questions?

**Comment by sunxi92** [comment]
> @sunxi92 Do you have any other questions?

There are no other questions at the moment.

**Comment by qqeasonchen** [comment]
> > @sunxi92 Do you have any other questions?
> 
> There are no other questions at the moment.

ok, i will close it.
