### ISSUE TITLE
[Enhancement] Method concatenates the result of a toString() call [AsyncPubClient]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2253]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/203489752-753784b5-de32-4113-90f5-fbf03ae2cbab.png)
located at:
src/test/java/org/apache/eventmesh/runtime/demo/AsyncPubClient.java line 44
analysis and explanation:
This method concatenates the output of a toString() call into a StringBuffer or StringBuilder. It is simpler just to pass the object you want to append to the append call, as that form does not suffer the potential for NullPointerExceptions, and is easier to read.

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/203489915-97cf35be-324e-4297-b2c9-8cb386027c87.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by LiuPiPiPi** [comment]
Hi, I want to fix this bug. @Alonexc

**Comment by mroccyen** [comment]
@LiuPiPiPi welcome~
