### ISSUE TITLE
[Enhancement] Method concatenates the result of a toString() call [CCSubClient]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2254]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/203490003-cabae4c6-6b38-4a4a-905b-07cb41cc2c30.png)
located at:
src/test/java/org/apache/eventmesh/runtime/demo/CCSubClient.java line 47
analysis and explanation:
This method concatenates the output of a toString() call into a StringBuffer or StringBuilder. It is simpler just to pass the object you want to append to the append call, as that form does not suffer the potential for NullPointerExceptions, and is easier to read.

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/203490079-06a389d7-8164-46bb-920d-a78fc6a0684a.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by momoxiaohaiya** [comment]
Hi, I am willing to solve this issue and submit a PR

**Comment by momoxiaohaiya** [comment]
Hi, I am willing to solve this issue and submit a PR

**Comment by xwm1992** [comment]
@momoxiaohaiya welcome～
