### ISSUE TITLE
Roadmap questions.

### ISSUE THREAD

**Issue by ewcchan** [apache/incubator-eventmesh#229]
Hi, According to the roadmap listed in [readme](https://github.com/WeBankFinTech/EventMesh#roadmap), there are plan to support Schema Registry, and additional services like Tracing, Filter, etc. What is the timeline (target year/quarter) of these features? Thanks.

**Comment by qqeasonchen** [comment]
Hi，these features will be launched soon and are expected to be implemented in Q3 this year, and are already in communication with contributors.

**Comment by ewcchan** [comment]
I am interested in the filtering and orchestration capability and their architecture as listed in v1.3. I would like to understand and participate in the design, Is there any early adaption/participation availability of the mentioned features? Thanks

**Comment by qqeasonchen** [comment]
@ewcchan you can give your desgin or idea anytime to community and have a discussion together, welcome to contirbue.

**Comment by qqeasonchen** [comment]
> I am interested in the filtering and orchestration capability and their architecture as listed in v1.3. I would like to understand and participate in the design, Is there any early adaption/participation availability of the mentioned features? Thanks

@ewcchan you can take a look at  #274  #276 , about event streaming or workflow integation, you can participate in the design if you like, thanks.
