### ISSUE TITLE
[Enhancement] Optimize the generation of random numbers

### ISSUE THREAD

**Issue by weihubeats** [apache/incubator-eventmesh#2300]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

ThreadLocalRandom performs better than Random in a multi-threaded environment, so I can't use ThreadLocalRandom instead of Random
<img width="741" alt="image" src="https://user-images.githubusercontent.com/42484192/204280720-a5134f99-a633-47b0-ad79-ce3be57323bb.png">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by horoc** [comment]
Thanks for the suggestion @weihubeats . BTW, it should be an **[Enhancement]** instead of **[Feature]**, right?

**Comment by weihubeats** [comment]
It should be, thank you for helping me to modify
