### ISSUE TITLE
[Enhancement]  Method encodes String bytes without specifying the character encoding [UnitTest]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2341]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/205012358-c1554b74-06cd-4edf-8ea9-45fb1a8c937f.png)
located at:
eventmesh-connector-plugin/eventmesh-connector-redis/src/test/java/org/apache/eventmesh/connector/redis/connector/UnitTest.java line 90
analysis and explanation:
The behavior of the String(byte[] bytes) and String.getBytes() is undefined if the string cannot be encoded in the platform's default charset.

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/205012458-cbbeb9fc-38be-495e-8a5c-46d8e77a9f9e.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want. fix it .
