### ISSUE TITLE
[Enhancement] Method encodes String bytes without specifying the character encoding [RedisProducerTest]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2342]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/205012559-629a9c5b-201a-4849-b2df-494f5ea1c771.png)
located at:
eventmesh-connector-plugin/eventmesh-connector-redis/src/test/java/org/apache/eventmesh/connector/redis/producer/RedisProducerTest.java line 68 104
analysis and explanation:
The behavior of the String(byte[] bytes) and String.getBytes() is undefined if the string cannot be encoded in the platform's default charset.

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/205012608-945ec13f-de5b-41c6-b8f7-deeae9614a22.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by keranbingaa** [comment]
i want to fix it
