### ISSUE TITLE
[Enhancement] Use the methods that have been extracted [ConfigurationWrapper]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2344]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/205017750-d1b9de0f-2f15-478b-9914-5ca31d655ee2.png)
located at:
eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/config/ConfigurationWrapper.java line 58

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/205013131-260fc2d5-f9b2-49cc-8c7d-036166d79d9b.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by keranbingaa** [comment]
i want to fix it
