### ISSUE TITLE
[Enhancement] Method throws alternative exception from catch block without history [ConfigurationWrapper]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2345]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/205012876-da8c5818-c20b-41ac-80a6-6b7ec24b1b56.png)
located at:
eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/main/java/org/apache/eventmesh/connector/rabbitmq/config/ConfigurationWrapper.java line 53 61
analysis and explanation:
This method catches an exception, and throws a different exception, without incorporating the original exception. Doing so hides the original source of the exception, making debugging and fixing these problems difficult.

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/205012969-1a134346-90e2-4508-9d39-b3a175226741.png)
![image](https://user-images.githubusercontent.com/91315508/205012968-60bc6f41-eda5-4631-8f81-85b638f21a65.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by keranbingaa** [comment]
i want to fix it
