### ISSUE TITLE
[Enhancement] Method encodes String bytes without specifying the character encoding [RabbitmqCloudEventTest]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2346]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/205013214-b01b50d1-6a2c-423f-ad97-1d0b424cf594.png)
located at:
eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/test/java/org/apache/eventmesh/connector/rabbitmq/cloudevent/RabbitmqCloudEventTest.java line 43
analysis and explanation:
The behavior of the String(byte[] bytes) and String.getBytes() is undefined if the string cannot be encoded in the platform's default charset.

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/205013263-1cb8034c-e4b3-4402-8ad9-a0dc064e6957.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
