### ISSUE TITLE
[Enhancement] Method encodes String bytes without specifying the character encoding [RabbitmqConsumerTest]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2347]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/205013330-e54e4f08-2f5c-4283-b155-1a0c1bad003b.png)
located at:
eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/test/java/org/apache/eventmesh/connector/rabbitmq/consumer/RabbitmqConsumerTest.java line 71
analysis and explanation:
The behavior of the String(byte[] bytes) and String.getBytes() is undefined if the string cannot be encoded in the platform's default charset.

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/205013408-8d6d0513-04cc-47f2-9e0a-a5b612aac083.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
