### ISSUE TITLE
[Enhancement] Method encodes String bytes without specifying the character encoding [RabbitmqProducerTest]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2348]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/205013534-362d3201-9727-4ef5-a5ae-38ff5034f9ee.png)
located at:
eventmesh-connector-plugin/eventmesh-connector-rabbitmq/src/test/java/org/apache/eventmesh/connector/rabbitmq/producer/RabbitmqProducerTest.java line 71
analysis and explanation:
The behavior of the String(byte[] bytes) and String.getBytes() is undefined if the string cannot be encoded in the platform's default charset.

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/205013584-68a51b9b-c17e-49b2-837b-a2e5e87635d8.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I fix it.
