### ISSUE TITLE
[Enhancement] Method encodes String bytes without specifying the character encoding [PravegaClientTest]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2349]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/205013711-4ea79c2d-2734-4024-ae60-d7fe2a990768.png)
located at:
eventmesh-connector-plugin/eventmesh-connector-pravega/src/test/java/org/apache/eventmesh/connector/pravega/client/PravegaClientTest.java line 163
analysis and explanation:
The behavior of the String(byte[] bytes) and String.getBytes() is undefined if the string cannot be encoded in the platform's default charset.

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/205013792-702459d8-158a-4d35-a195-81a2b52e19e1.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want fix it.
