### ISSUE TITLE
[Enhancement] Method calls equals on an enum instance [EventMeshConsumer]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2372]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/205198998-3de84c29-8f00-426d-a724-f22db5c97168.png)
![image](https://user-images.githubusercontent.com/91315508/205198991-ced4f867-954f-453d-bf81-54bade5fc9d1.png)
![image](https://user-images.githubusercontent.com/91315508/205199014-66b04890-16a9-4381-aea9-e06f43f70270.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java line 268 276 292
analysis and explanation:
This method calls the equals(Object) method on an enum instance. Since enums values are singletons, you can use == to safely compare two enum values. In fact, the implementation for Enum.equals does just that.

### Describe the solution you'd like

Change to use "==".

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it .
