### ISSUE TITLE
[Enhancement] Method calls equals on an enum instance [ServiceUtils]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2373]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/205199143-10fd5d3a-7f0b-40e8-af4b-a846753578d0.png)
![image](https://user-images.githubusercontent.com/91315508/205199147-332bba47-37d0-4df0-82d2-cf94dda67074.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/ServiceUtils.java line 75 93 97
analysis and explanation:
This method calls the equals(Object) method on an enum instance. Since enums values are singletons, you can use == to safely compare two enum values. In fact, the implementation for Enum.equals does just that.

### Describe the solution you'd like

Change to use "==".

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
