### ISSUE TITLE
[Enhancement]  Method calls equals on an enum instance [WebhookPushRequest]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2374]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/205199257-f2c20271-e288-4918-8a2b-8f6b935254c9.png)
![image](https://user-images.githubusercontent.com/91315508/205199266-0c0dcce2-cca9-4d45-9d6a-636e13f6bc83.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/WebhookPushRequest.java line 239 241 250 252
analysis and explanation:
This method calls the equals(Object) method on an enum instance. Since enums values are singletons, you can use == to safely compare two enum values. In fact, the implementation for Enum.equals does just that.

### Describe the solution you'd like

Change to use "==".

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
