### ISSUE TITLE
[Enhancement] Method calls equals on an enum instance [HeartbeatProcessor]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2379]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/205199964-0e999135-1d8b-437c-8558-e6c0283904e5.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/processor/HeartbeatProcessor.java line 72
analysis and explanation:
This method calls the equals(Object) method on an enum instance. Since enums values are singletons, you can use == to safely compare two enum values. In fact, the implementation for Enum.equals does just that.

### Describe the solution you'd like

Change to use "==".

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by keranbingaa** [comment]
i want to fix it
