### ISSUE TITLE
[Enhancement] Method concatenates the result of a toString() call [EventMeshUtil]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2382]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/205200620-7075ac5e-7349-40c9-91b9-c27640b517c7.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshUtil.java line 110
analysis and explanation:
This method concatenates the output of a toString() call into a StringBuffer or StringBuilder. It is simpler just to pass the object you want to append to the append call, as that form does not suffer the potential for NullPointerExceptions, and is easier to read.

### Describe the solution you'd like

Remove the .toString.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
