### ISSUE TITLE
[Enhancement] Inefficient use of keySet iterator instead of entrySet iterator [HttpRequestProtocolResolver]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2384]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/205201364-83d40109-6528-4471-bf0a-38eb97e4dd4a.png)
located at:
eventmesh-protocol-plugin/eventmesh-protocol-http/src/main/java/org/apache/eventmesh/protocol/http/resolver/HttpRequestProtocolResolver.java line 76
analysis and explanation:
This method accesses the value of a Map entry, using a key that was retrieved from a keySet iterator. It is more efficient to use an iterator on the entrySet of the map, to avoid the Map.get(key) lookup.

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/205200968-8f0d7c43-a2c5-48e1-8d67-724d94dfca3d.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it .
