### ISSUE TITLE
[Enhancement] Method stores return result in local before immediately returning it [HttpSummaryMetrics]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2385]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/205201071-fa01e6e0-5872-45e1-bdde-f9ff56b3bb8a.png)
located at:
eventmesh-metrics-plugin/eventmesh-metrics-api/src/main/java/org/apache/eventmesh/metrics/api/model/HttpSummaryMetrics.java line 64 69 95 100 130 164 169 229 234 326 331 390 400 410
analysis and explanation:
This method stores the return result in a local variable, and then immediately returns the local variable. It would be simpler just to return the value that is assigned to the local variable,

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/205201104-5650d547-229b-4962-95cd-442c949a0323.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by keranbingaa** [comment]
I want to fix it
