### ISSUE TITLE
[Enhancement] Method invocation 'toString' may produce 'NullPointerException' [GrpcMessageProtocolResolver]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2518]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/206636958-da03f337-ca12-4e81-bbca-41bd111cbdbf.png)
located at:
eventmesh-protocol-plugin/eventmesh-protocol-cloudevents/src/main/java/org/apache/eventmesh/protocol/cloudevents/resolver/grpc/GrpcMessageProtocolResolver.java line 47 97-116 127 131 140 158 160-188 
analysis and explanation:
These places are prone to NPE.

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/91315508/206637027-01983651-5402-4e96-bc37-8a8a958cb3b9.png)
Use the integrated method replacement to avoid NPEs, and elsewhere use the Objects.requireNonNull() method.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by venkatesh2090** [comment]
I want to fix this issue!
