### ISSUE TITLE
[Enhancement] 'catch' branch identical to 'SocketException' branch

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2519]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/206637517-e2cbd3b8-5f63-4ead-b287-9a2152f90d0c.png)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/utils/IPUtils.java line 115
analysis and explanation:
'catch' branch identical to 'SocketException' branch

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/206637457-346cce19-f893-484f-a37b-2491f1806553.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by keranbingaa** [comment]
i want to fix it
