### ISSUE TITLE
[Enhancement] Method invocation 'getBytes' may produce 'NullPointerException' [HttpCommand]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2522]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/206637927-3081a67d-6db8-498d-98a0-db3e18ca4175.png)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/HttpCommand.java line 236

### Describe the solution you'd like

To add an NPE check, it is recommended to use Objects.requireNonNull().

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by walterlife** [comment]
> I want to fix it.

@jonyangx Hi, There is a pr already related to this issue(before not relate it, already fix). you can also fix this issue #2553
