### ISSUE TITLE
[Enhancement] Method stores return result in local before immediately returning it [Operation]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2523]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/206638070-33e6fba4-4037-4a31-b280-55233f7e5c1d.png)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/catalog/protos/Operation.java line 463
analysis and explanation:
This method stores the return result in a local variable, and then immediately returns the local variable. It would be simpler just to return the value that is assigned to the local variable.

### Describe the solution you'd like

Returns the value of a local variable directly.
reference：
![image](https://user-images.githubusercontent.com/91315508/206638135-77c84cfa-3a01-414e-9b03-3699c6bb755a.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
