### ISSUE TITLE
[Enhancement] Method stores return result in local before immediately returning it [RegistryRequest]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2526]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/206638457-c5f7cd40-247e-4e61-8d47-420638dd535f.png)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/catalog/protos/RegistryRequest.java line 394
analysis and explanation:
This method stores the return result in a local variable, and then immediately returns the local variable. It would be simpler just to return the value that is assigned to the local variable.

### Describe the solution you'd like

Returns the value of a local variable directly.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it .
