### ISSUE TITLE
[Enhancement] Method stores return result in local before immediately returning it [BatchMessage]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2528]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/206639207-ed81c984-d690-4a71-a4ea-d4966f0564a5.png)
![image](https://user-images.githubusercontent.com/91315508/206639265-14c99a02-56d8-4583-880f-f7117a6c4be7.png)
![image](https://user-images.githubusercontent.com/91315508/206639274-d457052b-c7ae-408d-9b27-a3043fdaaca8.png)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/BatchMessage.java line 695 810 1721 1834
analysis and explanation:
This method stores the return result in a local variable, and then immediately returns the local variable. It would be simpler just to return the value that is assigned to the local variable.

### Describe the solution you'd like

Returns the value of a local variable directly.
reference:
![image](https://user-images.githubusercontent.com/91315508/206639481-1a761724-ff9a-4fa8-9dfc-86e7def7f6d4.png)
![image](https://user-images.githubusercontent.com/91315508/206639489-71561fe1-236f-45d8-9687-5a6a370d5289.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
