### ISSUE TITLE
[Enhancement] Method stores return result in local before immediately returning it [Heartbeat]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2529]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/206639691-0bf00db9-2d16-4503-b8ee-42d64a27d8d0.png)
![image](https://user-images.githubusercontent.com/91315508/206639675-55e5b641-874b-427c-b63f-5fca47d6f2c0.png)
![image](https://user-images.githubusercontent.com/91315508/206639703-5506da78-0137-46cb-a553-6eed81906be1.png)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/Heartbeat.java 468 573 1124 1239
analysis and explanation:
This method stores the return result in a local variable, and then immediately returns the local variable. It would be simpler just to return the value that is assigned to the local variable.

### Describe the solution you'd like

Returns the value of a local variable directly.
Reference:
![image](https://user-images.githubusercontent.com/91315508/206639793-9038f3a9-dee7-4d04-b894-10e6bdc260e7.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
