### ISSUE TITLE
[Enhancement] Method stores return result in local before immediately returning it [RequestHeader]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2530]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/206639929-f6c8aecf-cfc7-4643-ae20-fc119a822218.png)
![image](https://user-images.githubusercontent.com/91315508/206639920-726d55eb-163f-4e99-a166-58234116c1e8.png)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/RequestHeader.java line 719 844
analysis and explanation:
This method stores the return result in a local variable, and then immediately returns the local variable. It would be simpler just to return the value that is assigned to the local variable.

### Describe the solution you'd like

Returns the value of a local variable directly.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
