### ISSUE TITLE
[Enhancement] Method stores return result in local before immediately returning it [Response]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2531]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/206640134-0cc3f064-4899-47fc-acb0-d7f3d2123c66.png)
![image](https://user-images.githubusercontent.com/91315508/206640123-f76baaba-d192-4f80-b445-920095dc7e13.png)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/Response.java line 278 385
analysis and explanation:
This method stores the return result in a local variable, and then immediately returns the local variable. It would be simpler just to return the value that is assigned to the local variable.

### Describe the solution you'd like

Returns the value of a local variable directly.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it .
