### ISSUE TITLE
[Enhancement] Method stores return result in local before immediately returning it [SimpleMessage]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2532]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/206640415-bab3beec-c3db-4555-a894-4b3607c70b6a.png)
![image](https://user-images.githubusercontent.com/91315508/206640388-00769a42-cc89-465d-9da4-1908b589a8d6.png)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/SimpleMessage.java line 678 817
analysis and explanation:
This method stores the return result in a local variable, and then immediately returns the local variable. It would be simpler just to return the value that is assigned to the local variable.

### Describe the solution you'd like

Returns the value of a local variable directly.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
