### ISSUE TITLE
[Enhancement] Method stores return result in local before immediately returning it [BaseRequestBody]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2534]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/206641228-0ea0fb87-b276-4cb8-8b37-47f8cc42e29d.png)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/body/BaseRequestBody.java line 32
analysis and explanation:
This method stores the return result in a local variable, and then immediately returns the local variable. It would be simpler just to return the value that is assigned to the local variable.

### Describe the solution you'd like

Returns the value of a local variable directly.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
