### ISSUE TITLE
[Enhancement] Method stores return result in local before immediately returning it [UserAgent]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2537]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/206641593-89020415-534c-4d93-ab38-5745afc634e2.png)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/tcp/UserAgent.java line 151
analysis and explanation:
This method stores the return result in a local variable, and then immediately returns the local variable. It would be simpler just to return the value that is assigned to the local variable.

### Describe the solution you'd like

Returns the value of a local variable directly.
reference:
![image](https://user-images.githubusercontent.com/91315508/206641656-a3e21b6c-332a-4cd4-8b6b-105612f43e17.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by walterlife** [comment]
1. The original code has no performance problems, and code style problems
2. Although the modified code looks more concise, it actually has some side effects. For example, a single line is too complex, the readability is poor, and the testability is poor.
more details can read the google code review guide in depth.
https://google.github.io/eng-practices/review/reviewer/looking-for.html#complexity
