### ISSUE TITLE
[Enhancement] Method may fail to close stream [security onfigurationWrapper]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2541]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/206643651-19c5e084-f3e3-4847-a449-3fd2356f829c.png)
located at:
eventmesh-security-plugin/eventmesh-security-api/src/main/java/org/apache/eventmesh/api/common/ConfigurationWrapper.java
analysis and explanation:
The method creates an IO stream object, does not assign it to any fields, pass it to other methods that might close it, or return it, and does not appear to close the stream on all paths out of the method.  This may result in a file descriptor leak. 

### Describe the solution you'd like

Use try-with-recourse to manage resources.
Reference:
![image](https://user-images.githubusercontent.com/91315508/206643692-e32a5b06-5829-412b-b250-27313c5955d0.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
