### ISSUE TITLE
[Enhancement]  Method invocation may produce 'NullPointerException'

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2543]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/206643388-cdaa2b46-be00-4333-9b1b-7ddb2708d340.png)
![image](https://user-images.githubusercontent.com/91315508/206643402-808fbfc9-5eeb-4659-a191-49a5cbd264dc.png)
located at:
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/RRCallbackResponseHandlerAdapter.java line 87 104

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/206643457-2e304371-20d2-49de-bc1a-4a3213ceda64.png)
![image](https://user-images.githubusercontent.com/91315508/206643465-ab20cca7-bf1f-4cb8-bd94-c2ed10a2481a.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
