### ISSUE TITLE
[Enhancement] Method makes literal string comparisons passing the literal as an argument

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2544]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/206643255-fd5e910f-14e5-467a-adf7-d2bc88e24f77.png)
located at:
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/catalog/EventMeshCatalogClient.java line 76
analysis and explanation:
This line is in the form of 
String str = str.equals("someOtherString");
A NullPointerException may occur if the String variable str is null. If instead the code was restructured to 
String str = someOtherString".equals(str);
that is, call equals() n the string literal, passing the variable as an argument, then this exception could never happen as both equals() check for null.

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/206643328-81a6896f-7110-449c-bbf6-e14c1f59ac21.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Alonexc** [comment]
> Hello there, anyone working on this issue currently @Alonexc and @xwm1992 ?

@rukundob451 No one has claimed it yet, do you want to try? If you want to work for this, you can submit a pr.

**Comment by rukundob451** [comment]
> > Hello there, anyone working on this issue currently @Alonexc and @xwm1992 ?
> 
> @rukundob451 No one has claimed it yet, do you want to try? If you want to work for this, you can submit a pr.

Yes @Alonexc wanted to give it a try.

**Comment by Alonexc** [comment]
> Yes @Alonexc wanted to give it a try.

@rukundob451 Welcome, you can submit a pr first.

**Comment by Alonexc** [comment]
> > > Yes @Alonexc wanted to give it a try.
> > 
> > 
> > @rukundob451 Welcome, you can submit a pr first.
> 
> Alright sure, working on it. Any possible ideas you think I would use?

@rukundob451 This is just a small issue, just follow the reference and fix it, if you have a better idea is also possible.

**Comment by vasaniyakush** [comment]
Is this issue available for contribution?

**Comment by Alonexc** [comment]
> 这个问题可以贡献吗？

This issue has been fixed and I will close it, are you interested in other issues? There are many such issues in the community, so feel free to contribute.

**Comment by rukundob451** [comment]
> @vasaniyakush This issue has been fixed and I will close it, are you interested in other issues? There are many such issues in the community, so feel free to contribute.

Sure @Alonexc will check them out.
