### ISSUE TITLE
[Enhancement] String concatenation '+=' in loop

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2545]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/206643054-6e0cb8d8-c30a-4afd-ad2a-f776d3bd80ed.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/ShowClientBySystemHandler.java line 76

### Describe the solution you'd like

Cnvert variable "result" from String to StringBuilder

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
