### ISSUE TITLE
[Enhancement] Local variable 'result' is redundant [EventMeshUtil]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2546]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/206642906-f1f0bfa1-a427-4775-83f2-e6fa50c0f76d.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshUtil.java line 145

### Describe the solution you'd like

Returns the value of a local variable directly.
reference:
![image](https://user-images.githubusercontent.com/91315508/206642979-f37c2f6a-a2d8-4ec2-b3e2-5c3410a0e03c.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sohel-79** [comment]
I have checked the file I think it has been fixed can you look and confirm again @Alonexc

**Comment by Alonexc** [comment]
> I have checked the file I think it has been fixed can you look and confirm again @Alonexc

@sohel-79 Yes, it's fixed and I will close the issue. sorry!
