### ISSUE TITLE
[Enhancement] 'try' can use automatic resource management

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2547]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/206642518-c370b03a-f65e-477e-9ad7-7d9e2f934ae1.png)
![image](https://user-images.githubusercontent.com/91315508/206642529-4f82ac57-a755-455c-acee-d2f20b3ea2d7.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/IOTinyUtils.java line 92 140
analysis and explanation:
Changing to using try-with-recourse to manage resources can make the code neater.

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/206642614-b6893ca5-0166-4333-bcf9-d637b2b9b265.png)
![image](https://user-images.githubusercontent.com/91315508/206642623-dfc134e5-575d-49ff-b772-5bff13b2816e.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
