### ISSUE TITLE
[Enhancement] Method converts String to boxed primitive using excessive boxing

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2591]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/207541880-75c76fd2-f778-493b-80ae-f854d8709ff4.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/QueryWebHookConfigByManufacturerHandler.java line 64 65
analysis and explanation:
This method passes a String to a wrapped primitive object's parse method, which in turn calls the valueOf method to convert to a boxed primitive. When it is desired to convert from a String to a boxed primitive object, it is simpler to use the BoxedPrimitive.valueOf(String) method.

### Describe the solution you'd like

Use the BoxedPrimitive.valueOf(String) method.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
