### ISSUE TITLE
[Enhancement] 'while' loop replaceable with enhanced 'for'

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2592]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/207542166-3ef515cf-068e-45b5-a163-4b2469222278.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientSessionGroupMapping.java line 369,394
analysis and explanation:
'while' loop replaceable with enhanced 'for

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/207542246-ac4f91ac-9b5c-41ef-b829-c07260f19fb4.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.

**Comment by jonyangx** [comment]
I want to fix it.
