### ISSUE TITLE
[Enhancement] Method specifies an unrelated class when allocating a Logger [HeartbeatService]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2595]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/207543506-bd85e9be-2e5c-4d3e-ab04-2706ef5e8631.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/service/HeartbeatService.java line 37
analysis and explanation:
This method creates a Logger by passing in a specification for a class that is unrelated to the class in which the logger is going to be used. This is likely caused by copy/paste code.
``

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/207543632-ffe23113-a1c7-42dd-b28f-cff6f7dab0e9.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
