### ISSUE TITLE
[Enhancement] Method specifies an unrelated class when allocating a Logger [AbstractPushRequest]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2596]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/207543805-e427e06c-4ebb-40c9-b492-1543214382fe.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/push/AbstractPushRequest.java line 51
analysis and explanation:
This method creates a Logger by passing in a specification for a class that is unrelated to the class in which the logger is going to be used. This is likely caused by copy/paste code.

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/207543850-000a6923-aee0-4055-8391-70c4839e2dbe.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
