### ISSUE TITLE
[Enhancement] Method checks for an item in a set with contains, before using add()

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2597]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/207544014-1006674d-ce52-420f-b2a3-ebacdae8e40c.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/HttpClientGroupMapping.java line 224
analysis and explanation:
This method checks to see if an element is not in a set before adding it. This is unnecessary as you can just add the item, and if the item exists, it won't add it, otherwise it will.

### Describe the solution you'd like

As an example, instead of using 
                Set  mySet = getSomeSet();
                if (!mySet.contains("foo")) {
                    mySet.add("foo");
                }   
convert this to 
                Set  mySet = getSomeSet();
                if (mySet.add("foo")) {
                }

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
