### ISSUE TITLE
[Enhancement] Method invocation 'toString' may produce 'NullPointerException'

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2599]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/207544682-9e8e06e1-e5c7-4bb3-9693-ab113488331b.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/EventMeshConsumer.java line 118,119

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/207544750-6115ad3d-2b51-4572-9c5a-63862d243eee.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by venkatesh2090** [comment]
Hi, I would like to fix this issue.
