### ISSUE TITLE
[Enhancement] Method calls equals on an enum instance [SessionSender]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2600]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/207544873-a08d9944-c341-4e31-afad-feda2203bb43.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/SessionSender.java line 183
analysis and explanation:
This method calls the equals(Object) method on an enum instance. Since enums values are singletons, you can use == to safely compare two enum values. In fact, the implementation for Enum.equals does just that.

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/207544943-005d84b9-fe15-4f26-8ca7-d5e92fd4a177.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
