### ISSUE TITLE
[Enhancement] Argument type 'String' does not match the type of the format specifier '%d'

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2603]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/207545606-66425139-f7d6-4314-ba44-0b4e9f78d7eb.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RejectClientBySubSystemHandler.java line 109

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/207545701-4deb7024-a4a9-486b-a96c-01e1202f7f33.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
