### ISSUE TITLE
[Enhancement] Field isn't final but should be [HTTPMetricsServer]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2604]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/207545889-cb420bc9-0e55-4edc-abcb-f72bbf89649e.png)
![image](https://user-images.githubusercontent.com/91315508/207545871-125243a5-3b6d-4ece-9e1d-560abf94a9cd.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/http/HTTPMetricsServer.java line 36,38,40,42,94,95
analysis and explanation:
This static field public but not final, and could be changed by malicious code or by accident from another package. The field could be made final to avoid this vulnerability.

### Describe the solution you'd like

add final.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
