### ISSUE TITLE
Support for unified access and transformation of OpenTracing protocol

### ISSUE THREAD

**Issue by chenyi19851209** [apache/incubator-eventmesh#263]
hi ,
We hope to connect various open source APM products in the industry with EventMesh, so that users can more conveniently display their OpenTracing tracking information in an integrated and unified platform

**Comment by liwenzheng** [comment]
Very good proposal. It can be built in by default.

**Comment by chenmudu** [comment]
It looks good. I'd be happy to do it. It just so happens that I've been working in this area.

**Comment by qqeasonchen** [comment]
@chenmudu welcome to contirbute~

**Comment by chenmudu** [comment]
Yeah, maybe I should familiarize myself with the project. @qqeasonchen

**Comment by qqeasonchen** [comment]
@chenmudu Would you like to share some new design with us? thanks.

**Comment by liangyuanpeng** [comment]
FYI,  OpenTracing going to archive, use OpenTelemetry will be greate.
