### ISSUE TITLE
[Enhancement] Class defines a computed serialVersionUID that doesn't equate to the calculated value [EventMeshException]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2643]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209280987-c914cdb6-3457-4748-bc32-d48252812584.png)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/exception/EventMeshException.java line 21
analysis and explanation:
This serializable class defines a serialVersionUID that appears to be a computed value, however the value does not match the computed value, and thus losses it's value as version indicator.

### Describe the solution you'd like

recompute the serialVersionUID using IDE.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I 'd like to fix it.
