### ISSUE TITLE
[Enhancement] Class defines a computed serialVersionUID that doesn't equate to the calculated value [JsonException]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2644]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209281296-497c7d75-5f73-42f4-966e-b4aa2486784e.png)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/exception/JsonException.java line 25
analysis and explanation:
This serializable class defines a serialVersionUID that appears to be a computed value, however the value does not match the computed value, and thus losses it's value as version indicator.

### Describe the solution you'd like

recompute the serialVersionUID using IDE.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mxsm** [comment]
@Alonexc  I want to try
