### ISSUE TITLE
[Enhancement] Class defines a computed serialVersionUID that doesn't equate to the calculated value [SubscriptionItem]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2645]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209283356-6e16c209-51d5-4b6b-b886-576cb03f0d82.png)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/SubscriptionItem.java line 27
analysis and explanation:
This serializable class defines a serialVersionUID that appears to be a computed value, however the value does not match the computed value, and thus losses it's value as version indicator.

### Describe the solution you'd like

recompute the serialVersionUID using IDE.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sreenath-tm** [comment]
I would like to solve this issue can you let me know how I can go about fixing this issue.

**Comment by Alonexc** [comment]
> I would like to solve this issue can you let me know how I can go about fixing this issue.

Welcome, just use the IDE to recalculate the serialVersionUID.

**Comment by Alonexc** [comment]
> 

If you do not know how to do, you can first delete line 27 of the code, set the UID, Severity default Warning can be, and then put the cursor on the class name, select Add 'serialVersionUID' field to determine.

**Comment by ibrijesh** [comment]
I would like to contribute. Can you assign to me .

**Comment by Alonexc** [comment]
@ibrijesh Of course, you can submit a pr and associate an issue first.
