### ISSUE TITLE
[Enhancement] Class defines a computed serialVersionUID that doesn't equate to the calculated value [SimpleMessageWrapper]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2647]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209286707-598da04e-2c12-4174-bd50-002689fa67ec.png)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/common/SimpleMessageWrapper.java line 25
analysis and explanation:
This serializable class defines a serialVersionUID that appears to be a computed value, however the value does not match the computed value, and thus losses it's value as version indicator.

### Describe the solution you'd like

recompute the serialVersionUID using IDE.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by koonchen** [comment]
:) pls assigne to me, thx
