### ISSUE TITLE
[Enhancement] Class defines a computed serialVersionUID that doesn't equate to the calculated value [HttpEventWrapper]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2649]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209286966-c10df865-491c-4757-bbe0-ddb92edf7f37.png)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/http/HttpEventWrapper.java line 49
analysis and explanation:
This serializable class defines a serialVersionUID that appears to be a computed value, however the value does not match the computed value, and thus losses it's value as version indicator.

### Describe the solution you'd like

recompute the serialVersionUID using IDE.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by TheAPratap** [comment]
As what you've wrote will make the serialized form of the new version of the class incompatible with the serialized form of the old version.

You can use this instead
<img width="382" alt="Screenshot 2023-01-19 at 10 34 25 PM" src="https://user-images.githubusercontent.com/16948492/213511732-53e948e0-4a78-4c81-893e-fc4201b283e9.png">

**Comment by ria28** [comment]
I want to fix this issue!
