### ISSUE TITLE
[Enhancement] new MyX509TrustManager() may fail to close stream

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2651]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209287406-e348d4e1-0784-4bd2-9519-66dae5e6d0ea.png)
located at:
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/ssl/MyX509TrustManager.java line 46
analysis and explanation:
The method creates an IO stream object, does not assign it to any fields, pass it to other methods that might close it, or return it, and does not appear to close the stream on all paths out of the method.  This may result in a file descriptor leak.  

### Describe the solution you'd like

It is a good idea to use a finally block or a try-with-recourse to make sure the stream is closed.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I'd like to fix it.
