### ISSUE TITLE
[Enhancement] Method init() makes literal string comparisons passing the literal as an argument

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2653]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209287588-c48b7ffc-da78-45cb-81f1-2f3aac1b3ff9.png)
located at:
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/catalog/EventMeshCatalogClient.java line 76
analysis and explanation:
This line is in the form of 
String str = ...
str.equals("someOtherString");
A NullPointerException may occur if the String variable str is null. If instead the code was restructured to 
String str = ...
"someOtherString".equals(str);
that is, call equals() on the string literal, passing the variable as an argument, then this exception could never happen as both equals() check for null.

### Describe the solution you'd like

Adjust the code to:String str = "someOtherString".eals(str).

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I'd like to fix it.
