### ISSUE TITLE
[Enhancement] Method uses immediate execution of a block of code that is often not used [AbstractEventProcessor]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2661]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209297980-1d11bd9e-5ebe-4c6d-ad06-3bb61506e72d.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf/AbstractEventProcessor.java line 129
analysis and explanation:
This method uses the Optional.orElse() method passing in some code that will execute immediately, whether or not the else case of the Optional is needed. This may cause incorrect side effects to happen, or at the minimum, code to execute for no reason.

### Describe the solution you'd like

It would be better to use Optional.orElseGet()

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I'd like to fix it.
