### ISSUE TITLE
[Enhancement] Can be replaced with 'Map.forEach()'

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2662]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209298171-e383573d-2d18-4dca-808e-231330f552d5.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/HTTPMessageHandler.java line 59

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/209298218-cb0d5aa4-e4d2-43dd-9783-fa3f25ac7781.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I'd like to fix it.
