### ISSUE TITLE
[Enhancement] Null pointer dereference

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2663]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209298290-e642fc1a-db1c-452a-be13-1482d3e8a956.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractHTTPServer.java line 333
analysis and explanation:
A null pointer is dereferenced here.  This will lead to a NullPointerException when the code is executed.

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/209300765-cdb4ed90-f686-46a6-82a7-84dbd28140f5.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
