### ISSUE TITLE
[Enhancement] Method appears to call the same method on the same object redundantly [UnSubscribeProcessor]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2677]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209308714-c3784f65-8ab0-4282-9003-66d28ecaf5b1.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/UnSubscribeProcessor.java line 74,84
analysis and explanation:
This method makes two consecutive calls to the same method, using the same constant parameters, on the same instance, without any intervening changes to the objects. If this method does not make changes to the object, which it appears it doesn't, then making two calls is just a waste

### Describe the solution you'd like

These method calls could be combined by assigning the result into a temporary variable, and using the variable the second time.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zeevel** [comment]
I'd like to solve this issue, can you assign this task to me.

**Comment by Alonexc** [comment]
> I'd like to solve this issue, can you assign this task to me.

Welcome! You can start by submitting a pr.
