### ISSUE TITLE
[Enhancement] Method appears to call the same method on the same object [redundantly[AsyncHTTPPushRequest]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2678]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209308843-d3357097-5a37-4682-89d0-58d25b04ee49.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AsyncHTTPPushRequest.java line 116,202
analysis and explanation:
This method makes two consecutive calls to the same method, using the same constant parameters, on the same instance, without any intervening changes to the objects. If this method does not make changes to the object, which it appears it doesn't, then making two calls is just a waste

### Describe the solution you'd like

These method calls could be combined by assigning the result into a temporary variable, and using the variable the second time.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by dilraj-vyas** [comment]
Hi 
I would like to contribute to this project, pls assign this issue to me , thanks.

**Comment by Alonexc** [comment]
> Hi I would like to contribute to this project, pls assign this issue to me , thanks.

Welcome, you can submit a pr first and it will be assigned to you later.
