### ISSUE TITLE
[Enhancement] Method handle(HttpExchange) manually handles closing an auto-closeable resource [RejectAllClientHandler]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2704]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209896676-479e00d3-dd5c-4ed9-a569-1c4a188b0f25.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/RejectAllClientHandler.java
analysis and explanation:
This method allocates and uses an auto closeable resource. However, it manually closes the resource in a finally block. While this is correct management, it doesn't rely on the idiomatic way available to JDK 7 and above, allows for possible subtle problems, and complicates the reading of code by developers expecting the use of try-with-resources.

### Describe the solution you'd like

Change to use try-with-resources to manage resources.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
