### ISSUE TITLE
[Enhancement] Method stores return result in local before immediately returning it [AbstractRemotingServer]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2707]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209896846-99830f8c-a359-48ba-a83b-606460b38545.png)
![image](https://user-images.githubusercontent.com/91315508/209896848-1271e983-97a3-42f1-96e9-ea80f72cbba9.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/boot/AbstractRemotingServer.java line 45,60,72,77
analysis and explanation:
This method stores the return result in a local variable, and then immediately returns the local variable. It would be simpler just to return the value that is assigned to the local variable

### Describe the solution you'd like

1. Returns the value assigned to the local variable directly.
2. Field 'count' may be 'final'
reference:
![image](https://user-images.githubusercontent.com/91315508/209896877-c1dc78ff-5425-4730-abba-797c2eb6c430.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I'd like to fix it.
