### ISSUE TITLE
[Enhancement] Method stores return result in local before immediately returning it [RemotingHelper]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2710]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209897189-d07cdc9b-d7a9-4fc4-aac1-349f40597e77.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/RemotingHelper.java line 53
analysis and explanation:
This method stores the return result in a local variable, and then immediately returns the local variable. It would be simpler just to return the value that is assigned to the local variable

### Describe the solution you'd like

Returns the value assigned to the local variable directly.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I'd like to fix it.
