### ISSUE TITLE
[Enhancement] Method checks the size of a collection against zero rather than using isEmpty() [HttpClientGroupMapping]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2714]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209909810-9800a454-a3f6-463f-9e06-c37a3e5261c8.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/HttpClientGroupMapping.java line 309,314
analysis and explanation:
This method calls the size() method on a collection and compares the result to zero to see if the collection is empty.

### Describe the solution you'd like

For better code clarity, it is better to just use col.isEmpty().

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by tarunsamanta2k20** [comment]
No size()method is present at line 309,314

**Comment by Alonexc** [comment]
> No size()method is present at line 309,314

Due to code updates, it may be different from the actual location, which is now at lines 362 and 369.

**Comment by tarunsamanta2k20** [comment]
@Alonexc 

I will do it by eod
