### ISSUE TITLE
[Enhancement] Method checks the size of a collection against zero rather than using isEmpty() [ClientSessionGroupMapping]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2715]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientSessionGroupMapping.java line 331,337,338
analysis and explanation:
This method calls the size() method on a collection and compares the result to zero to see if the collection is empty.

### Describe the solution you'd like

For better code clarity, it is better to just use col.isEmpty().

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue. Please assign it to me.
