### ISSUE TITLE
[Enhancement] Method checks the size of a collection against zero rather than using isEmpty() [CloudEventProducer]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2718]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209910002-40cb2523-aa4f-480e-9049-3cf85549cf36.png)
located at:
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/grpc/producer/CloudEventProducer.java line 60

### Describe the solution you'd like

For better code clarity, it is better to just use col.isEmpty().

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by TheAPratap** [comment]
fix: Method checks the size of a collection against zero rather than using isEmpty() [CloudEventProducer] #2936

**Comment by sanskar-thakur** [comment]
I'm a first timer with respect to contributing to open source projects.
I would like to work on this issue. Please assign it to me.
Thanks.

**Comment by Alonexc** [comment]
> I'm a first timer with respect to contributing to open source projects. I would like to work on this issue. Please assign it to me. Thanks.

Welcome, this issue has been fixed and I will close it, are you interested in other issues? You are more than welcome to contribute to eventmesh.

**Comment by sanskar-thakur** [comment]
@Alonexc Sure, no problem. I'll look for other open issues that I can contribute to.
