### ISSUE TITLE
[Enhancement] Method checks the size of a collection against zero rather than using isEmpty() [RequestParam]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2720]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209910118-4224443e-fcf2-4290-b14f-7ee102e5eb26.png)
located at:
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/model/RequestParam.java line 77

### Describe the solution you'd like

For better code clarity, it is better to just use col.isEmpty().

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Alonexc** [comment]
> I would like to work on this issue. Please assign it to me.

Welcome, you can submit a pr first and it will be assigned to you later.
