### ISSUE TITLE
[Enhancement]  Method prints the stack trace to the console [EventMeshUtil]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2721]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209910168-206db142-310d-4657-a0e4-687b1eff30b8.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshUtil.java line 226,228
analysis and explanation:
Method prints the stack trace to the console This method prints a stack trace to the console. This is non configurable, and causes an application to look unprofessional

### Describe the solution you'd like

Use the logger to record exception information.
reference:
![image](https://user-images.githubusercontent.com/91315508/209910201-9d907046-32fc-42cd-9796-07b07af38075.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I'd like to fix it.
