### ISSUE TITLE
[Enhancement] Method run() uses integer based for loops to iterate over a List

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2722]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209910644-0ac66ef0-fcd6-4b74-bbb2-c45065432e51.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/SubscribeTask.java line 60
analysis and explanation:
This method uses an integer-based for loop to iterate over a java.util.List, by calling List.get(i) each time through the loop. The integer is not used for other reasons. It is better to use an Iterator instead, as depending on List implementation, iterators can perform better, and they also allow for exchanging of other collection types without issue.

### Describe the solution you'd like

Use foreach or iterator.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I'd like to fix it.
