### ISSUE TITLE
[Enhancement] Method passes a concatenated string to SLF4J's or Log4j2's format string [HTTPMetricsServer]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2724]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209910747-69bf980c-2f54-4e93-b48e-f17328cfff4f.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/metrics/http/HTTPMetricsServer.java line 68
analysis and explanation:
This method uses an SLF4J or Log4j2 logger to log a string, where the first (format) string is created using concatenation. You should use {} markers to inject dynamic content into the string, so that String building is delayed until the actual log string is needed. If the log level is high enough that this log statement isn't used, then the appends will never be executed.

### Describe the solution you'd like

use {} markers to inject dynamic content into the string

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
