### ISSUE TITLE
[Enhancement] Method shutdown() creates iterators on synchronized collections

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2725]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209910797-391dae96-5d33-4e4a-bedb-63cd8e480b38.png)
![image](https://user-images.githubusercontent.com/91315508/209910800-8aa01866-06ce-4683-a57a-73bfc699be24.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/HTTPClientPool.java line 56,74
analysis and explanation:
This method uses a synchronized collection, built from Collections.synchronizedXXXX, but accesses it through an iterator. Since an iterator is, by definition, multithreading-unsafe, this is a conflict in concept. When using iterators, should do the synchronization manually.

### Describe the solution you'd like

1.Synchronize manually.
2. Field 'clients' may be 'final'
reference:
![image](https://user-images.githubusercontent.com/91315508/209910839-c647039d-cfb8-416b-a3e6-bc10dfaf4f86.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I'd like to fix it.
