### ISSUE TITLE
[Enhancement] Method check a map with containsKey(), before using get() [LocalSubscribeEventProcessor]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2726]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209910877-9582a3fc-cb21-4a0c-bbd4-f74b576a4b7f.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/LocalSubscribeEventProcessor.java line 205
analysis and explanation:
This method checks for the presence of a key in a map using containsKey(), before attempting to fetch the value of the key using get(). This equates to doing two map lookups in a row. 

### Describe the solution you'd like

It is much simpler to just fetch the value with get, and checking for non null instead.
Reference:
![image](https://user-images.githubusercontent.com/91315508/209910910-70ed062c-c222-499c-bcce-8d36181b2dc2.png)

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
