### ISSUE TITLE
[Enhancement] Method check a map with containsKey(), before using get() [SubscribeProcessor]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2728]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209910998-bd0413f5-632b-4748-9d38-51fddbabf528.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/SubscribeProcessor.java line 206
analysis and explanation:
This method checks for the presence of a key in a map using containsKey(), before attempting to fetch the value of the key using get(). This equates to doing two map lookups in a row.

### Describe the solution you'd like

It is much simpler to just fetch the value with get, and checking for non null instead.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mvadharia** [comment]
I would like to fix this issue, please assign it to me.
