### ISSUE TITLE
[Enhancement]  Method check a map with containsKey(), before using get() [UnSubscribeProcessor]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2729]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209911048-a5852a26-a7cf-4406-80cf-f5b77fc6650a.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/UnSubscribeProcessor.java line 166
analysis and explanation:
This method checks for the presence of a key in a map using containsKey(), before attempting to fetch the value of the key using get(). This equates to doing two map lookups in a row.

### Describe the solution you'd like

It is much simpler to just fetch the value with get, and checking for non null instead.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
