### ISSUE TITLE
[Enhancement] Method builds a list from one element using Arrays.asList [HttpClientGroupMapping]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2735]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209911915-c628429c-6bda-4f23-b12f-6ae02f885ba0.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer/HttpClientGroupMapping.java line 203,224
analysis and explanation:
This method builds a list using Arrays.asList(foo), passing in a single element. Arrays.asList needs to first create an array from this one element, and then build a List that wraps this array. It is simpler to use Collections.singletonList(foo), which does not create the array, and produces a far simpler instance of List. Since both of these arrays are immutable (from the List's point of view) they are equivalent from a usage standpoint.

### Describe the solution you'd like

It is simpler to use Collections.singletonList(foo).

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
