### ISSUE TITLE
[Enhancement]  Method calls equals on an enum instance [ConsumerManager]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2737]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209912025-c9d35350-3e35-4107-8807-9b27bf9e2e2a.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/ConsumerManager.java line 108,110,115,117,158,184,191
analysis and explanation:
This method calls the equals(Object) method on an enum instance. Since enums values are singletons, you can use == to safely compare two enum values. In fact, the implementation for Enum.equals does just that.

### Describe the solution you'd like

Change it to use "==" or "! =".

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
