### ISSUE TITLE
[Enhancement] Method calls equals on an enum instance [ConsumerGroupTopicConfig]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2738]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209912078-64f0ee28-daf5-4f82-bc8d-3b9e0cdf9881.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/consumergroup/ConsumerGroupTopicConfig.java line 44,
analysis and explanation:
This method calls the equals(Object) method on an enum instance. Since enums values are singletons, you can use == to safely compare two enum values. In fact, the implementation for Enum.equals does just that.

### Describe the solution you'd like

Change it to use "==" or "! =".

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by KingChampion36** [comment]
I'm interested in implementing this fix.
