### ISSUE TITLE
[Enhancement] Method calls equals on an enum instance [StreamTopicConfig]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2739]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/209912116-fc3f85bb-1a07-42a8-b68a-e6bb6ade1d3f.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/consumer/consumergroup/StreamTopicConfig.java line 56,
analysis and explanation:
This method calls the equals(Object) method on an enum instance. Since enums values are singletons, you can use == to safely compare two enum values. In fact, the implementation for Enum.equals does just that.

### Describe the solution you'd like

Change it to use "==" or "! =".

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by jonyangx** [comment]
I want to fix it.
