### ISSUE TITLE
Lightweight SDKs for CloudEvents and EventStreaming

### ISSUE THREAD

**Issue by qqeasonchen** [apache/incubator-eventmesh#274]
They are at least three solutions for SDKs distribution now. 
1. [EventMesh binding CloudEvents and make necessary extensions with EventMesh SDKs](https://github.com/apache/incubator-eventmesh/blob/develop/docs/en/features/eventmesh-cloudevents-sdk-binding.md)[1]  
2. CloudEvents integrate Spring[2][3] 
3. [Spring Cloud Stream and Function Parts](https://github.com/apache/incubator-eventmesh/blob/develop/docs/en/features/eventmesh-stream-design.md)[4][5].

[1] https://github.com/cloudevents/sdk-java
[2] https://github.com/cloudevents/sdk-java/tree/master/spring/src/main/java
[3] https://spring.io/blog/2020/12/23/cloud-events-and-spring-part-2
[4] https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#_event_routing
[5] https://github.com/spring-cloud/spring-cloud-function

**Comment by vongosling** [comment]
Spring Cloud Stream may be a optional extension for native eventmesh sdks

**Comment by ruanwenjun** [comment]
@qqeasonchen Do we need to support all three? Maybe I can try to solve to integrate with Spring.

**Comment by qqeasonchen** [comment]
@ruanwenjun CloudEvents integration maybe the most wanted feature currently, can you do this first if you wish? we can open a discuss online.

**Comment by ruanwenjun** [comment]
@qqeasonchen I am not familiar with CloudEvents, this work is to covert events to CloudEvents format?

**Comment by xwm1992** [comment]
> @qqeasonchen I am not familiar with CloudEvents, this work is to covert events to CloudEvents format?

CloudEvents is a standard events protocal, it's sdk  supports converting messages to CloudEvents for transmission.You can get familiar with it refer to https://github.com/cloudevents/spec

**Comment by ruanwenjun** [comment]
> > @qqeasonchen I am not familiar with CloudEvents, this work is to covert events to CloudEvents format?
> 
> CloudEvents is a standard events protocal, it's sdk supports converting messages to CloudEvents for transmission.You can get familiar with it refer to https://github.com/cloudevents/spec

Thanks, currently, EventMesh transport event by `Package`, do you mean that we need to use the CloudEvents to deliver event? 

https://github.com/cloudevents/sdk-java/blob/687e03bac5569bcfae54f24c0da64291d2a77cac/core/src/main/java/io/cloudevents/core/v1/CloudEventV1.java

**Comment by xwm1992** [comment]
> > > @qqeasonchen I am not familiar with CloudEvents, this work is to covert events to CloudEvents format?
> > 
> > 
> > CloudEvents is a standard events protocal, it's sdk supports converting messages to CloudEvents for transmission.You can get familiar with it refer to https://github.com/cloudevents/spec
> 
> Thanks, currently, EventMesh transport event by `Package`, do you mean that we need to use the CloudEvents to deliver event?
> 
> https://github.com/cloudevents/sdk-java/blob/687e03bac5569bcfae54f24c0da64291d2a77cac/core/src/main/java/io/cloudevents/core/v1/CloudEventV1.java

@ruanwenjun Well，I'm agree delivering the events via CloudEvents. As for **sdk** side , you can depend on **CloudEvents http basic api** to send events and get response; for **eventmesh server** side, you may implements an custom deserializable interface converting **CloudEvents** to **OpenMessage**. You need to pay attention that not only use CloudEvents to send messages , but also for other tasks(such as subscribe/heartbeat/unsubscribe/e.g.)
The above is just my understanding , you can also ask other people for advice, thanks.

**Comment by qqeasonchen** [comment]
We'd better read the spec of CloudEvents first and do a design for EventMesh together. it is useful for widely integration.

**Comment by msdhinesh-geek** [comment]
Hi Eventmesh Team,
Is anyone working on design for CloudEvents and EventStreaming. What is plan ,timeline and roadmap ?
I see most of Event Mesh feature didn't have design and implementation discussion. It will be good if we track and communicate each progress. 
Kindly share your thoughts.

**Comment by yuzhoumao** [comment]
Hi @msdhinesh-geek,

I am working on the design as part of the summer of code 2021 program. A design doc will be sent to dev@eventmesh.incubator.apache.org within the next couple of days.

**Comment by msdhinesh-geek** [comment]
@yuzhoumao Are you working on both feature  CloudEvents and EventStreaming?

**Comment by yuzhoumao** [comment]
I am working on CloudEvents integration.

**Comment by msdhinesh-geek** [comment]
Ok, Then i will look into Event Streaming

**Comment by msdhinesh-geek** [comment]
@qqeasonchen Can you explain functional requirements of Event Streaming

**Comment by qqeasonchen** [comment]
> @qqeasonchen Can you explain functional requirements of Event Streaming

Spring Cloud Stream may be an optional extension for native EventMesh SDKs. Nowadays, we missed the event routing and event filter features. You can refer to [4][5], thanks.

[4] https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#_event_routing
[5] https://github.com/spring-cloud/spring-cloud-function

**Comment by qqeasonchen** [comment]
@msdhinesh-geek do you have any questions that i can help explain?

**Comment by msdhinesh-geek** [comment]
@qqeasonchen  Am working on following design, that allows us to use the binder abstractions from Spring Cloud Stream natively within Apache Camel. 
I choose Camel over Spring-Integration because the fluent API is really nice.

I suggest following module:

1. eventmesh-stream-api - Which will consist of abstractions for streaming, event routing , filtering etc, basically spring cloud stream will take care of streaming, binding to the messaging layer at runtime, Apache Camel will take care of Event Stream Processing like routing, filtering etc.

@qqeasonchen  - Let me know if you want to discuss further related to design.

**Comment by qqeasonchen** [comment]
@msdhinesh-geek yes, you can describe your desgin like https://github.com/apache/incubator-eventmesh/blob/develop/docs/en/features/eventmesh-cloudevents-sdk-binding.md .

**Comment by msdhinesh-geek** [comment]
@qqeasonchen  Sure.

**Comment by qqeasonchen** [comment]
@yuzhoumao Do you have any updates about cloudevents :) ?

**Comment by msdhinesh-geek** [comment]
@qqeasonchen Am working on interface design for binding , I will post design within couple of days.

**Comment by qqeasonchen** [comment]
> @qqeasonchen Am working on interface design for binding , I will post design within couple of days.

looking forward to it :)

**Comment by xwm1992** [comment]
@yuzhoumao Hi, what's the going on with cloudevents?
