### ISSUE TITLE
Lack of licenses in each source file under the eventmesh-runtime module

### ISSUE THREAD

**Issue by xwm1992** [apache/incubator-eventmesh#295]
If we want to publish under the apache, we need to add licenses to each source file. You can do this refer to https://creadur.apache.org/rat/apache-rat/index.html

**Comment by liangyuanpeng** [comment]
Let me work for it .

**Comment by kezhenxu94** [comment]
Hi @xwm1992 and @liangyuanpeng , I hope you'll find [this tool](https://github.com/apache/skywalking-eyes#docker-image) helpful to add license headers into the source files. License eye is a licensing tool to help audit and fix license headers, especially for ASF projects

docker run -it --rm -v $(pwd):/github/workspace apache/skywalking-eyes header fix

**Comment by xwm1992** [comment]
> Hi @xwm1992 and @liangyuanpeng , I hope you'll find this tool helpful to add license headers into the source files. License eye is a licensing tool to help audit and fix license headers, especially for ASF projects

docker run -it --rm -v $(pwd):/github/workspace apache/skywalking-eyes header fix

glad for your help, thank you!

**Comment by liangyuanpeng** [comment]
@kezhenxu94  Cool, It's working.
