### ISSUE TITLE
Lack of licenses in each source file under the eventmesh-starter module

### ISSUE THREAD

**Issue by xwm1992** [apache/incubator-eventmesh#297]
If we want to publish under the apache, we need to add licenses to each source file. You can do this refer to https://creadur.apache.org/rat/apache-rat/index.html

**Comment by justinmclean** [comment]
Hi,

If you need help with this just ask, I’ve reviewed 100’s and 100’s of releases.

Thanks,
Justin

**Comment by justinmclean** [comment]
Also see https://apache.org/dev/licensing-howto.html

**Comment by qqeasonchen** [comment]
> Hi, If you need help with this just ask, I’ve reviewed 100’s and 100’s of releases. Thanks, Justin

@justinmclean Thanks，it would be very appreciated If you can help review.
