### ISSUE TITLE
[Enhancement] Method invocation 'getRetCode' may produce 'NullPointerException'[EventMeshHttpConsumer]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2971]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/215700936-d558b9ee-1b9d-431b-9f76-4d6084b12e33.png)
located at:
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/consumer/EventMeshHttpConsumer.java line 101,132,160

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/215701009-fe76412d-217f-4c88-bf39-2511824232c2.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by uran0sH** [comment]
I would like to work on it if no one is working.

**Comment by Alonexc** [comment]
> I would like to work on it if no one is working.

Welcome.
