### ISSUE TITLE
[Enhancement] Method invocation 'getRetCode' may produce 'NullPointerException'[CloudEventProducer]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2972]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/215701105-54d704d0-35eb-4873-a991-a5c3daa7b764.png)
located at:
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/CloudEventProducer.java
line 79,80

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/215701159-2d0de9bc-726f-4b0d-83ab-0f8d1e703526.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by uran0sH** [comment]
I would like to work on it if no one is working.

**Comment by Alonexc** [comment]
> I would like to work on it if no one is working.

Welcome, you can submit pr first.
