### ISSUE TITLE
[Enhancement] String values are compared using '==', not 'equals()'

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#2988]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/215705806-fb2833d1-bc6b-4a7c-a6da-ae78229966c0.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/consumergroup/ProducerGroupConf.java line 51

### Describe the solution you'd like

reference:
![image](https://user-images.githubusercontent.com/91315508/215705846-ab7b1de8-d387-4b1b-879e-54c8aa240b52.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by kanha-gupta** [comment]
@Alonexc Hi ! i would do this,
is it have to be done in entire codebase or just in ProducerGroupConf ?

**Comment by Alonexc** [comment]
> @Alonexc Hi ! i would do this, is it have to be done in entire codebase or just in ProducerGroupConf ?

Welcome, just do it in this class.
