### ISSUE TITLE
[Bug] v1.7.0 KafkaConsumerRunner.java Use break to break out of the while

### ISSUE THREAD

**Issue by sq-yang-1** [apache/incubator-eventmesh#3077]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

Other

### What happened

Use break to break out of the while Cause the consumer thread to stop

### How to reproduce

.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hgaol** [comment]
Hi, I also found this bug and I'd like to fix it.
