### ISSUE TITLE
[Enhancement] Reliance on default encoding[FileLoad]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#3084]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/221106062-43086f7f-dfc3-449c-8d10-b4f304036e2f.png)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/config/FileLoad.java line 71,73
analysis and explanation:
1.Found a call to a method which will perform a byte to String (or String to byte) conversion, and will assume that the default platform encoding is suitable. This will cause the application behaviour to vary between platforms. Use an alternative API and specify a charset name or Charset object explicitly.
2. The method creates an IO stream object, does not assign it to any fields, pass it to other methods that might close it, or return it, and does not appear to close the stream on all paths out of the method.  This may result in a file descriptor leak.  It is generally a good idea to use a finally block to ensure that streams are closed.

### Describe the solution you'd like

1.Use try-with-resources to manage resources.
2. Use an alternative API and specify a charset name or Charset object explicitly.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sanskar-thakur** [comment]
Hi,

I would like to work on this issue. Please assign it to me.

Thanks,
Sanskar

**Comment by Alonexc** [comment]
> Hi,
> 
> I would like to work on this issue. Please assign it to me.
> 
> Thanks, Sanskar

OK, you can submit a pr first.
