### ISSUE TITLE
[Enhancement] Method uses integer based for loops to iterate over a List

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#3085]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/218021465-c47ade0b-d09a-4ae0-99af-646bb2179a18.png)
located at:
eventmesh-common/src/main/java/org/apache/eventmesh/common/protocol/grpc/protos/BatchMessage.java line 1539
analysis and explanation:
This method uses an integer-based for loop to iterate over a java.util.List, by calling List.get(i) each time through the loop. The integer is not used for other reasons.

### Describe the solution you'd like

It is better to use an iterator or foreach instead.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Prince-1110** [comment]
Please assign this task to me.

**Comment by Alonexc** [comment]
> Please assign this task to me.

@Prince-1110 Welcome, you can submit a pr first.

**Comment by PreetAngadSingh** [comment]
Hi @Alonexc can you reassign this issue to me? I have already implemented the solution

**Comment by Alonexc** [comment]
> Hi @Alonexc can you reassign this issue to me? I have already implemented the solution

@PreetAngadSingh Of course, you can submit a pr.
