### ISSUE TITLE
[Enhancement] Method invocation 'toString' may produce 'NullPointerException'

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#3087]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/218021689-f36e6ee9-70da-48d9-b809-0b7df5e064cb.png)
located at:
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/producer/ProducerImpl.java line 150

### Describe the solution you'd like

Use Objects.requireNonNull() to avoid NPE.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sanskar-thakur** [comment]
Hi,

I'm an experienced Java developer, and a first timer with respect to collaborating on open-source project.
I'm looking forward to contributing on this project, and would like to work on this issue.

Please assign to me if the issue needs to be worked on.
Thanks.
