### ISSUE TITLE
[Enhancement]  Argument 'msg.getSubject()' might be null

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#3088]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/218022338-2c7ba508-dca8-4aaa-88a3-420701b66111.png)
located at:
eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/consumer/PushConsumerImpl.java line 157

### Describe the solution you'd like

Use Objects.requireNonNull() to avoid NPE.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sanskar-thakur** [comment]
Hi,

I'm an experienced Java developer, and a first timer with respect to collaborating on open-source project.
I'm looking forward to contributing on this project, and would like to work on this issue.

Please assign to me if the issue needs to be worked on.
Thanks.

**Comment by Alonexc** [comment]
> Hi,
> 
> I'm an experienced Java developer, and a first timer with respect to collaborating on open-source project. I'm looking forward to contributing on this project, and would like to work on this issue.
> 
> Please assign to me if the issue needs to be worked on. Thanks.

Welcome！
