### ISSUE TITLE
[Enhancement] Format string '"Failed to connect pulsar with exception: %"' is malformed

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#3089]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/218022428-a3b9068b-b976-497c-a9b4-8de79e445407.png)
located at:
eventmesh-connector-plugin/eventmesh-connector-pulsar/src/main/java/org/apache/eventmesh/connector/pulsar/consumer/PulsarConsumerImpl.java line 83

### Describe the solution you'd like

e.g.
![image](https://user-images.githubusercontent.com/91315508/218022473-8daf402c-e388-474a-972d-812c0d911e44.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sanskar-thakur** [comment]
Hi,

I'm an experienced Java developer, and a first timer with respect to collaborating on open-source project.
I'm looking forward to contributing on this project, and would like to work on this issue.

Please assign to me if the issue needs to be worked on.
Thanks.

**Comment by Alonexc** [comment]
> Hi,
> 
> I'm an experienced Java developer, and a first timer with respect to collaborating on open-source project. I'm looking forward to contributing on this project, and would like to work on this issue.
> 
> Please assign to me if the issue needs to be worked on. Thanks.

Hello! Welcome, you can submit a pr first.
