### ISSUE TITLE
[Enhancement] Condition 'this.eventMeshTCPPubClient != null' and 'this.eventMeshTCPSubClient != null' is always 'true'[EventMeshMessageTCPClient]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#3093]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/218023043-a2cbeb11-1f51-4b94-b881-9c865338a915.png)
located at:
eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/impl/eventmeshmessage/EventMeshMessageTCPClient.java line 106,114

### Describe the solution you'd like

e.g.
![image](https://user-images.githubusercontent.com/91315508/218023084-e9566c97-ac7d-4a7a-948c-822c7820425c.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by PickBas** [comment]
I will work on that
