### ISSUE TITLE
[Enhancement] Remove invalid code.

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#3098]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/218024200-45e8d2d4-6b1d-429a-bd1f-10b777c8a52e.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/response/GetConfigurationResponse.java line 45-54

### Describe the solution you'd like

Delete the invalid code.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by tarunsamanta2k20** [comment]
Can I contribute to this issue??

**Comment by tarunsamanta2k20** [comment]
i had contributed to this repo before.

**Comment by Alonexc** [comment]
> i had contributed to this repo before.

Of course.
