### ISSUE TITLE
[Enhancement] Field may be 'final'[ProducerManager]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#3100]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/218024386-463d9f5a-68e4-406c-85e9-417fc7b6ca85.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/grpc/producer/ProducerManager.java line 33,35

### Describe the solution you'd like

e.g.
![image](https://user-images.githubusercontent.com/91315508/218024422-67d5f2e3-98f2-4772-9b25-2e20d200a81f.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by willimpo** [comment]
I want to fix this issue!

**Comment by Alonexc** [comment]
> I want to fix this issue!

Welcome, you can submit a pr first.

**Comment by PreetAngadSingh** [comment]
As this issue is not resolved, i have done the changes. you can check it in the following PR

**Comment by PreetAngadSingh** [comment]
@willimpo can you please check #3148 as CI/Build for macOS is failing.
