### ISSUE TITLE
[Enhancement]  integer multiplication implicitly cast to long

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#3102]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/218024560-b360babe-eb28-4d28-9e9d-921aec93a4f5.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/push/AbstractHTTPPushRequest.java line 89

### Describe the solution you'd like

e.g.
![image](https://user-images.githubusercontent.com/91315508/218024603-51ae232e-a918-42e9-b285-140ee4a98a0c.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by leven-space** [comment]
Should this be closed?

**Comment by leven-space** [comment]
Should this be closed? @Alonexc

**Comment by Alonexc** [comment]
> Should this be closed? @Alonexc
Pr is not merged.
https://github.com/apache/incubator-eventmesh/pull/3109
