### ISSUE TITLE
[Enhancement] Method invocation may produce 'NullPointerException'[ZookeeperRegistryService]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#3105]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/218024922-dd293ac7-0796-409b-9b6c-41a0efeff015.png)
![image](https://user-images.githubusercontent.com/91315508/218024929-95bdeaf4-61da-4c31-888c-eeb20e0130fd.png)
located at:
eventmesh-registry-plugin/eventmesh-registry-zookeeper/src/main/java/org/apache/eventmesh/registry/zookeeper/service/ZookeeperRegistryService.java line 158,206,259

### Describe the solution you'd like

e.g.
![image](https://user-images.githubusercontent.com/91315508/218024956-d71c655b-0c79-4d5b-9766-0f5ad9846b2f.png)
![image](https://user-images.githubusercontent.com/91315508/218024979-86963ab5-a8fc-4c15-ab7f-9d7b62831b18.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Bannirui** [comment]
@Alonexc Hi, l'd like to try, could u pls assign to me. In addition, any CONTRIBUTING.md as a referrence.

**Comment by Alonexc** [comment]
> @Alonexc Hi, l'd like to try, could u pls assign to me. In addition, any CONTRIBUTING.md as a referrence.

Welcome, this is a small change, according to the picture changes can be, of course, if you have a better suggestion is also possible, and finally ensure that the ci check can be passed.
