### ISSUE TITLE
[Enhancement] Refactor Registry

### ISSUE THREAD

**Issue by mxsm** [apache/incubator-eventmesh#3129]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Refactor Registry class

### Describe the solution you'd like

Refactor Registry class code

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by Vishal1297** [comment]
Hi @mxsm,

I would like to work on this.
Can you share more info about this?

**Comment by mxsm** [comment]
> Hi @mxsm,
> 
> I would like to work on this. Can you share more info about this?

Hi @Vishal1297 I am already working on this task and have completed the development of some code.
