### ISSUE TITLE
[Enhancement] Field may be 'final'[TCPClient]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#3163]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/219286998-f436376c-9d31-4281-9d22-ff0e8f1eedb2.png)
ocated at:
eventmesh-runtime/src/test/java/org/apache/eventmesh/runtime/client/common/TCPClient.java line 62,68,73

### Describe the solution you'd like

Add the 'final' modifier.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by cocodroid** [comment]
assign to me.

**Comment by Alonexc** [comment]
> assign to me.

OK, you can submit a pr first.
