### ISSUE TITLE
[Enhancement] Method invocation may produce 'NullPointerException'[JsonUtilsTest]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#3167]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/219287507-5f808dd8-c464-47fa-b99e-866c13984de8.png)
located at:
eventmesh-common/src/test/java/org/apache/eventmesh/common/utils/JsonUtilsTest.java line 61,63,74

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/91315508/219287544-deabe3d9-9a82-45ac-bc15-82f5a4f7d11b.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mxsm** [comment]
@Alonexc  I wil fix it
