### ISSUE TITLE
[Question] Regarding the implementation of admin, in which module should it be located?

### ISSUE THREAD

**Issue by mxsm** [apache/incubator-eventmesh#3192]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

The current project has an eventmesh-admin module, and according to the documentation, its main function is to manage clients, topics, and subscriptions. Based on my understanding, the implementation of client management, topic (CRUD), and subscription should all be located in this module. However, in practice, the related functions are implemented in the sub-modules of the eventmesh-connector-plugin module. For example, in the singleton pattern, topic creation is implemented in the eventmesh-connector-standalone module instead of the corresponding sub-module in the eventmesh-admin module.

I would like to know what the current code module plan is. For example, should the implementation of topic creation related functions for RocketMQ be located in the eventmesh-admin-rocketmq module?

@jonyangx  @xwm1992  @qqeasonchen 

Are there any relevant agreements in the current project? As I mentioned before, I plan to refactor the admin-related code in the eventmesh-connector-plugin into the corresponding sub-module in the eventmesh-admin module.

**Comment by xwm1992** [comment]
Hi @mxsm , for now, the management API used by the admin module can be designed separately and called by the admin. Different connector plug-ins can be used to implement it in the same way as the runtime.

**Comment by mxsm** [comment]
@xwm1992  Get it, Thanks for your answer
