### ISSUE TITLE
Question about some fields in the EventMesh Client Model

### ISSUE THREAD

**Issue by jinrongluo** [apache/incubator-eventmesh#320]
Hi, I am playing around with EventMesh project and also studying the code of EventMesh runtime compoent.

When studying the Http Consumer Manager code, I am seeing it is using the following Client Model
https://github.com/apache/incubator-eventmesh/blob/develop/eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf/Client.java

This client model has these fields. Could you explain what these fields all about? Thanks.

```
    public String env;

    public String dcn;

    public String idc;

    public String sys;

```

**Comment by lrhkobe** [comment]
- env: the enviroment of client, which is used to distinguish different enviroments, such as production environment ，test environment  and development environment;
- dcn: the logical concept, the Data Center Node of client comes from, when the num of client up to the capacity of DCN,  another new DCN will be created for the new client; 
- idc: the physical machine room of client comes from;
- sys: system id, the apllication system identification of the client.

We will redefinite this part more common later and provide relevant guidance. Thank you

**Comment by jinrongluo** [comment]
Thanks for explanation.
