### ISSUE TITLE
Question about EventMesh Topic format

### ISSUE THREAD

**Issue by jinrongluo** [apache/incubator-eventmesh#321]
Hi Dear,

I play around with EventMesh project and also studying the EventMesh codes. I see the RMQ Topic created through EventMesh, the topic name needs to be certain format. For example, "FT0-e-80010000-01-1"

From the code, this method check weather the topic is valid:
https://github.com/apache/incubator-eventmesh/blob/develop/eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshUtil.java#L118

I am wondering why do we have this restriction for topic names.

If we want to create topic names with my own, such as "my-event-topic", what is the solution. 

Thanks.

**Comment by xwm1992** [comment]
> Hi Dear,
> 
> I play around with EventMesh project and also studying the EventMesh codes. I see the RMQ Topic created through EventMesh, the topic name needs to be certain format. For example, "FT0-e-80010000-01-1"
> 
> From the code, this method check weather the topic is valid:
> https://github.com/apache/incubator-eventmesh/blob/develop/eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util/EventMeshUtil.java#L118
> 
> I am wondering why do we have this restriction for topic names.
> 
> If we want to create topic names with my own, such as "my-event-topic", what is the solution.
> 
> Thanks.

Hi, format validation for event topics may be a bit of a problem for you at the moment. For now, you can create topics in the format FT0-E-80010000-01. Similarly, you can create topics such as:FT0-E-80010001-01, it should be noted that **e in the event topic** and **the fourth position of 80010001 is 1**  . We will remove the verification of this part later and provide relevant guidance. Thank you

**Comment by jinrongluo** [comment]
Thanks for your answer.
