### ISSUE TITLE
[Enhancement] Format the project code style according to the eventmesh-code-style.xml code style

### ISSUE THREAD

**Issue by mxsm** [apache/incubator-eventmesh#3221]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Format the project code style according to the eventmesh-code-style.xml code style.

### Describe the solution you'd like

Format the project code style according to the eventmesh-code-style.xml code style.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by Bannirui** [comment]
So, what is the scope. All the project or module by module. and it means Including src code, tests code and other docs, right.

**Comment by mxsm** [comment]
> So, what is the scope. All the project or module by module. and it means Including src code, tests code and other docs, right.

Hi @Bannirui  Documents not included, noly java code. src code, tests code

**Comment by mxsm** [comment]
@Bannirui  I will submit a pr to fix it and Part of the code is done.

**Comment by mxsm** [comment]
@Bannirui Please close you pr to avoid confusion
