### ISSUE TITLE
QuickStart is not quick

### ISSUE THREAD

**Issue by vongosling** [apache/incubator-eventmesh#323]
When a newbie reaches to EventMesh,  it is difficult to quick start from the scratch. I would like to be a such man to try to experience the optimized document. Please opt here:-)

**Comment by Hu-Tu-Tu** [comment]
Is there any difference between the development version of eventmesh and the master version? I see that the source code of the master version needs to be used when starting in QuickStart of runtime

**Comment by qqeasonchen** [comment]
> Is there any difference between the development version of eventmesh and the master version? I see that the source code of the master version needs to be used when starting in QuickStart of runtime

@Hu-Tu-Tu Master is the last release code, usually, develop branch is comleyed.

**Comment by Hu-Tu-Tu** [comment]
So I can start the runtime directly with the development version, right？

**Comment by Hu-Tu-Tu** [comment]
Or it's OK for me to start with any of these versions, right？

**Comment by qqeasonchen** [comment]
> Or it's OK for me to start with any of these versions, right？

@Hu-Tu-Tu may be some differences of different versions due to feature changes, and the quick start needs to be updated too, Currently 1.2.0 is releasing, so the quick start should follow it.

**Comment by Hu-Tu-Tu** [comment]
@qqeasonchen OK，I see

**Comment by Hu-Tu-Tu** [comment]
@qqeasonchen OK, I see, thanks.

**Comment by qqeasonchen** [comment]
@Hu-Tu-Tu moudle discriptions and project structrue is not right in eventmesh-runtime-quickstart.md , you can change it.

**Comment by Hu-Tu-Tu** [comment]
@qqeasonchen I see. I'm also writing eventmesh runtime quickstart.md. Now I've written a Chinese description of rocketmq. If I send it to the tutor's email directly, or can I send it to issue directly, I'll discuss with you whether there are ambiguous or inappropriate parts in the document.

**Comment by xwm1992** [comment]
- #452 
@Hu-Tu-Tu please pay attention to this issue, thks.

**Comment by qqeasonchen** [comment]
@Hu-Tu-Tu Can you record a vedio about quick deployment and upload to bilibi？

**Comment by Hu-Tu-Tu** [comment]
@xwm1992 I've noticed that. Thank you！

**Comment by Hu-Tu-Tu** [comment]
@qqeasonchen Do you want me to deploy the whole project locally, including rocketmq, runtime, TCP and HTTP protocol examples?
