### ISSUE TITLE
[Enhancement] Lambda can be replaced with method reference

### ISSUE THREAD

**Issue by Bannirui** [apache/incubator-eventmesh#3235]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Locating at org/apache/eventmesh/runtime/connector/ConnectorResource.java
Line 47

<img width="1402" alt="截屏2023-02-22 上午11 43 52" src="https://user-images.githubusercontent.com/24436692/220516213-43b38fb3-cc30-4076-8eae-3acce2dcd2c0.png">

### Describe the solution you'd like

e.g.,

<img width="1486" alt="截屏2023-02-22 上午11 44 06" src="https://user-images.githubusercontent.com/24436692/220516247-09c7bc53-15f5-4715-a5bb-a56ca2530b87.png">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by PickBas** [comment]
I will work on that
