### ISSUE TITLE
[Enhancement] Field may be 'final'[HttpSummaryMetrics]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#3252]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/221076614-e6a7398c-0fd4-4ce6-8d0f-00810adf675a.png)
located at:
eventmesh-metrics-plugin/eventmesh-metrics-api/src/main/java/org/apache/eventmesh/metrics/api/model/HttpSummaryMetrics.java line 46,49,51,53,55,112,123,125,127,130,136,185,187,189,191,193,195,260,262,264,266,268,270,336,340,344

### Describe the solution you'd like

add final.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ibrijesh** [comment]
I would like to contribute . Can you please assign this  to me

**Comment by ibrijesh** [comment]
made the changes mentioned in #3362 
added final

looking forward for you response.

**Comment by Alonexc** [comment]
@ibrijesh Welcome to the EventMesh community.

**Comment by ibrijesh** [comment]
@Alonexc   Thank you for welcoming me to the EventMesh community! I'm excited to be a part of this community and look forward to contributing in any way that I can.
