### ISSUE TITLE
Missing Log4j dependency

### ISSUE THREAD

**Issue by ruanwenjun** [apache/incubator-eventmesh#329]
The `log4j2.xml` can't work, this may due to missing  dependencies.
https://logging.apache.org/log4j/2.x/maven-artifacts.html

**Comment by xwm1992** [comment]
> The `log4j2.xml` can't work, this may due to missing dependencies.
> https://logging.apache.org/log4j/2.x/maven-artifacts.html

Well，we have already configured the log4j2 under the build.gradle file

**Comment by ruanwenjun** [comment]
@xwm1992 Great

**Comment by ruanwenjun** [comment]
@xwm1992 Sorry, I still can't find the log4j2 in build.gradle

**Comment by xwm1992** [comment]
> @xwm1992 Sorry, I still can't find the log4j2 in build.gradle

yes, I get this problem too， the log4j2 dependency was missed by others pull request merged. I'll handle this problem
