### ISSUE TITLE
[Enhancement] Use isEmpty() to check whether the collection is empty or not.[ ShowListenClientByTopicHandler]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#3404]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/224203706-775ff58d-a7ad-47b2-b04d-05e705e70ae0.png)
located at:
eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/admin/handler/ShowListenClientByTopicHandler.java line 71
analysis and explanation:
Using Collection.size() to test for emptiness works, but using Collection.isEmpty() makes the code more readable and can be more performant. The time complexity of any isEmpty() method implementation should be O(1) whereas some implementations of size() can be O(n).

### Describe the solution you'd like

use Collection.isEmpty().

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by KamToHung** [comment]
please assign to me

**Comment by Alonexc** [comment]
@KamToHung Welcome, you can submit a pr first.
