### ISSUE TITLE
[Enhancement] Do some missing code optimization.

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#3439]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/91315508/224635188-09c3290e-ea7f-43ac-beab-65ea15ec6d32.png)
![image](https://user-images.githubusercontent.com/91315508/224635266-11f9cfb3-a223-48a9-81f9-e83c5bf031eb.png)

### Describe the solution you'd like

1.logically this should be '!listenSessionSet.isEmpty()'.
2.remove this expression which always evaluates to 'true'.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by qqeasonchen** [comment]
test
