### ISSUE TITLE
How EventMesh offers Administrative API to manage Topic of the eventstore

### ISSUE THREAD

**Issue by jinrongluo** [apache/incubator-eventmesh#346]
I would like to know if there is a plan to add administrative APIs in the EventMesh project, to support Message Topic management. This APIs include create Topic in eventstore (such as RocketMQ), and remove topic, Clear messages inside the Topic.

**Comment by qqeasonchen** [comment]
Currently you can use rocketmq-tools, a dashboard is on schedule.

**Comment by ewcchan** [comment]
Hi, will it be done via the eventmesh-connector-api programming model?

**Comment by qqeasonchen** [comment]
Admin api abstraction is a good choice.

**Comment by jinrongluo** [comment]
Would the community add this Topic Admin API support to EventMesh project? Thanks.

**Comment by qqeasonchen** [comment]
@jinrongluo You can commit your proposal and let's have a discussion first about the AdminAPI if you wish. thanks.

**Comment by jinrongluo** [comment]
hi @qqeasonchen  I discuss this a little bit on another issue #349  

The Topic mgmt REST API looks similar to the following. But the challenging is that the event_store layer, (i.e. RockeMQ) is not offering Topic creation/deletion API programmatically. 

```
  // create one topic
POST /rest/topics
{
    "name":  "mytopic1"
}

// delete one topic
DELETE /rest/topics/{name}

   // List all topics
GET  /rest/topics
```

**Comment by qqeasonchen** [comment]
@jinrongluo I mentioned, we can define it in a sub moudle like eventmesh-admin-api , you can design it and discuss online together, thanks.

**Comment by jinrongluo** [comment]
> @jinrongluo I mentioned, we can define it in a sub moudle like eventmesh-admin-api , you can design it and discuss online together, thanks.

Cool @qqeasonchen Let me start the design of this part, and update this issue later. Thanks.

**Comment by qqeasonchen** [comment]
@jinrongluo you can watch ClientManageController.java together when you design.

**Comment by jinrongluo** [comment]
> @jinrongluo you can watch ClientManageController.java together when you design.

Sure. Thanks @qqeasonchen

**Comment by qqeasonchen** [comment]
@jinrongluo this feature relates to #349
