### ISSUE TITLE
Suggestion of Event Subscription management and persistence

### ISSUE THREAD

**Issue by jinrongluo** [apache/incubator-eventmesh#349]
Right now EventMesh Runtime store the HTTP Publisher-Subscriber subscriptions in a local Map, such as, `EventMeshHTTPServer.localClientInfoMapping`,  `EventMeshHTTPServer.localClientInfoMapping`, `ComsumerManager.consumerTable` etc.

We need to keep the subscriptions in local Map for caching and performance. However we don't have a persistent storage to keep this records. In the case of server restart, the local Map is lost. 

So we suggest to have a  event-mesh management module to manage these subscription records and store them in a database or data store.  We can leverage this management module to manage the subscription read, creation, update, and deletion.

We can also expand functionality of this management module to manage other components of EventMesh, such as Topic and Schemas.

**Comment by vongosling** [comment]
This is a very correct direction. Could you help to detail your idea, such as extract the API and make runtime pluggable?

**Comment by lrhkobe** [comment]
Thank you for your question.

In case of  Eventmesh Runtime Server restart,  the server will disconnect all the client connected to this server, in the same time, it will manage the subscription,clear all the subscription.

As to EventMeshTcpServer, the necessary process of client conncting to Eventmesh Runtime is as follows:

- send the command of `HELLO_REQUEST`  to EventMesh Runtime for creating connection;
- send the command of `SUBSCRIBE_REQUEST` to EventMesh Runtime for subscribing topics;
- send the command of `LISTEN_REQUEST` to EventMesh Runtime for starting consume;

So when  EventMesh Runtime stoppig, the client will reconnect to other Eventmesh Runtime instance, and the subscription will manage in the new instance. When EventMesh  Runtime starting ,the client will do the necessary process above.

Because the subscription is relative to clients connecting to this EventMesh Runtime Server, in case of EventMesh Runtime Server restart, the clients which will connet to this server may change, so as to  this view, the persist of subscription may be unnecessay.

You can compare EventMeshHttpServer with EventMeshTcpServer, thanks for your suggestion again.

**Comment by jinrongluo** [comment]
Thanks @vongosling and @lrhkobe for your comments.

Our use case is that we use EventMesh's HTTP protocol for PubSub, and we don't want the clients to react to the event of EventMesh Server restart. In other words, we would like EventMesh to recover the existing subscriptions after it restarts. This event is transparent to clients.

This is an important design requirement in cloud native production environment, where Client Apps are managed by developers and the number of Client Apps are large. The Server maintenance events should be self-managed, and self-recovered. Operational transparency to End User (Client App) is the key.

With this requirement in mind, I propose the following design model:

1. Have a pluggable persistency layer to store the existing Client Map table. It has two parts:

     1-1). eventmesh-persist-api

      This is the persistency interface module which provide the APIs to persist subscriber (Client) data, including Evn, Region, IDC, DCN, Hostname, Sys, PidTopic, URL,etc. Example APIs look like the followings:

```
// Call after successful Subscribe()
public void addClient(Client client);

// Call after successful Unsubscribed(), or Client's lastUpTime expired
public void removeClient(Client client);

// Call after Runtime restart
public List<Client> loadClients();
```

 1-2). eventmesh-persist

This module provides a pluggable vendor implementation of  `eventmesh-persist-api`, for example it can be file system, in-memory DB, MySQL Database, etcd data store,  Each storage module supplies with its own configuration file, and implementation, this is similar idea to `eventmesh-connector-rocketmq` module implementing `eventmesh-connector-api` 


2.  In Cloud native environment, it is typical for a Server to offer RESTful API for its operations. So I would also suggest having a new eventmesh-rest module which offers a list of RESTful APIs for publish / subscribe. This is on top of the SDK-based support.

HTTP POST  /rest/publish
    headers:  topic
    payload:
    {
        "message": "test message"
    }

HTTP POST /rest/subscribe
    payload:
   { 
         "env": "prod",
         "Sys":  "myapp",
         "ping":  "http://myapp/ping" , // This API is used by Runtime to check the health of client App, similar to Heartbeat
         "topics": ["topic1",  "topic2"],
         "url":  "http://myapp/webhook"
    }

HTTP POST /rest/unsubscribe
    payload:
   { 
         "topics": ["topic1",  "topic2"],
         "url":  "http://myapp/webhook"
    }

In this rest module, the Client module would be lighter, we may not need the Client App

**Comment by jinrongluo** [comment]
We can further extend the persistent module and rest admin module to manage Topics. This is related to my issue #346 

For example at the persist-api module:

```
 public void addTopic(String topicName);
 
public void removeTopic(String topicName);

public List<String> listTopics();
```

At the rest module, we offer this RESTful API:

```
  // create one topic
POST /rest/topics
{
    "name":  "mytopic1"
}

   // List all topics
GET  /rest/topics


```

**Comment by qqeasonchen** [comment]
@lrhkobe Can you show us the method to get the subscriptions about TCP protocol?

**Comment by lrhkobe** [comment]
About TCP protocol, we can get the subscriptions  by script `session.sh` in  directory of `EventMesh\eventmesh-runtime\scripts`.

**Comment by qqeasonchen** [comment]
This feature will be considered with AdminAPI together in v1.3.0.

**Comment by qqeasonchen** [comment]
@jinrongluo Would you like to share some new desgin with us if you like ?

**Comment by jinrongluo** [comment]
> @jinrongluo Would you like to share some new desgin with us if you like ?

The new design is to introduce three new modules in the EventMesh project.

1. **eventmesh-rest** module. This module is to refactor the eventmesh runtime -> admin code into a separate new module. We can add more admin REST APIs into this module.  /subscriptions  API will be in this new module

/topics API will be add to this module too. As for implementation, It can invoke RocketMQ's ./mqadmin command to perform the topic operations: create/update topic, delete topic.

2. **eventmesh-store-api**  module.  EventMesh needs to persist data into database. As mentioned in this issue. subscriptions need to persist into database to preserve the data in case of server restart. This is the database interface module. It provides interface of database CRUD operations.

3. **eventmesh-store-h2**  module. This is H2 reference implementation of eventmesh-store-api. Data such subscriptions are store into H2 database and write back to file system

**Comment by jinrongluo** [comment]
When time permitted I will provide reference implementation and submit a PR for review. Thanks.

**Comment by qqeasonchen** [comment]
@jinrongluo sure, this feature can consider with #339 together.

**Comment by jinrongluo** [comment]
> @jinrongluo sure, this feature can consider with #339 together.

Yes, That's right. Part of the work here can be coming from issue #339. Once #339 is resolved, the three new modules are laid down in the project. I can build on top of it.

Thanks.
