### ISSUE TITLE
Add LGTM Badges

### ISSUE THREAD

**Issue by SteveYurongSu** [apache/incubator-eventmesh#353]
LGTM is a variant analysis platform that automatically checks code for real CVEs and vulnerabilities. Learn more at https://lgtm.com/help/lgtm/about-lgtm .

Here are some alerts in our project reported by LGTM: https://lgtm.com/projects/g/apache/incubator-eventmesh/alerts/?mode=list

I'd like to add LGTM badges in the README.md, it makes easier for people who want to get alerts and then contribute to EventMesh.

**Comment by qqeasonchen** [comment]
Seems interesting.
