### ISSUE TITLE
Setup Github workflows for CodeQL scans

### ISSUE THREAD

**Issue by SteveYurongSu** [apache/incubator-eventmesh#355]
About code scanning:

> 
>   Code scanning is a feature that you use to analyze the code in a GitHub repository to find security vulnerabilities and coding errors. Any problems identified by the analysis are shown in GitHub.
>   
>   You can use code scanning to find, triage, and prioritize fixes for existing problems in your code. Code scanning also prevents developers from introducing new problems. You can schedule scans for specific days and times, or trigger scans when a specific event occurs in the repository, such as a push.
>   
>   If code scanning finds a potential vulnerability or error in your code, GitHub displays an alert in the repository. After you fix the code that triggered the alert, GitHub closes the alert. For more information, see "Managing code scanning alerts for your repository."

See more at: https://docs.github.com/en/code-security/secure-coding/about-code-scanning

**Comment by qqeasonchen** [comment]
Will this cause the every build slow or hard to pass?

**Comment by SteveYurongSu** [comment]
> slow ?

No. First of all this will not have any effect on local builds and this scan will only trigger when a new PR is submitted. 
Currently each code scan takes about 7 minutes, which is only about a minute longer than Travis CI builds.
Considering that these builds are running at the same time, actually checks for each PR will only take about 2 minutes longer after the code scan is introduced.

> or hard to pass?

Code scanning will give a quality report after each check. We'd better determine whether to merge a PR based on the report. This will prevent developers from introducing new problems :)

**Comment by qqeasonchen** [comment]
What is the differences between CodeQL and Travis CI about code scan ?

**Comment by SteveYurongSu** [comment]
> What are the differences between CodeQL and Travis CI about code scan ?

They scan and check our code from very different aspects.

Normally we build our project and run ITs/UTs on Travis CI to check the correctness of the "business logic", but for the security vulnerabilities and coding errors covered or not covered by the UTs/ITs, Travis CI can't do nothing.

CodeQL is professional at potential security vulnerabilities and coding errors finding and it can automatically display alerts it finds in the repository. (BTW, LGTM.com which I mentioned at ISSUE#353 is based on the CodeQL project.)

Actually, many Apache projects have set up boths tools for code check.
