### ISSUE TITLE
Migrate CI to Github Actions and enable code coverage report

### ISSUE THREAD

**Issue by SteveYurongSu** [apache/incubator-eventmesh#364]
I'd like to add a step in CI to evaluate and report the code coverage, and use this as an opportunity to migrate the CI workflow from Travis CI to Github Actions.

Why do I want to migrate the CI workflow from Travis CI to Github Actions?  There are several reasons:

1. The virtual machines that Travis CI provides to public repos to run CI are weaker than that of Github Actions.  We have done some tests in the repo of Apache IoTDB, and the time spent on building executable files and running tests in Travis CI is significantly higher than the time spent on Github Actions.

2. Github Actions make it easier for the flok repos to run integration tests out of the Apache repo. There is a limited amount of runs that Travis CI allows individuals to trigger for free in a year, which causes some contributors (sadly, including me) to be unable to run CI in their own repos.

3. It is more convenient to build workflows using the Github Actions, which allows users to perform multiple checks in one build. We only need to build the code once to run ITs/UTs, perform CodeQL checks and update the code coverage in Codecov.

**Comment by qqeasonchen** [comment]
@SteveYurongSu Thanks for your suggestion. BTW, do you notice the SOC issue? It is strongly recommended to participate in the soc.

**Comment by SteveYurongSu** [comment]
> @SteveYurongSu Thanks for your suggestion. BTW, do you notice the SOC issue? It is strongly recommended to participate in the soc.

Hi @qqeasonchen , thanks for inviting me! 

I have noticed the soc several days ago. No matter whether I participate in the soc or not, I will choose a feasible issue for me to develop :D

**Comment by qqeasonchen** [comment]
@SteveYurongSu thanks.
