### ISSUE TITLE
Clear some legacy concept

### ISSUE THREAD

**Issue by qqeasonchen** [apache/incubator-eventmesh#366]
There are still some legacy concept releated to message bus, such as DCN,  "FT0-e-80010000-01-1", DeFiBus, WeMQ etc, which shoud be updated.

**Comment by iNanos** [comment]
i will solve this

**Comment by qqeasonchen** [comment]
@iNanos thanks，topic format validation should be removed too.

**Comment by ewcchan** [comment]
+1 . Thanks for the clean up effort on the legacy attributes. appreciate!
