### ISSUE TITLE
Upgrade jdk version to 1.8

### ISSUE THREAD

**Issue by ruanwenjun** [apache/incubator-eventmesh#373]
jdk=1.7 currently exists in some configurations, do we need to replace it?
https://github.com/apache/incubator-eventmesh/blob/efb2c118de077f82f83011ed13823e2c6f8b35c2/eventmesh-common/gradle.properties#L17-L19

**Comment by qqeasonchen** [comment]
@ruanwenjun sure, since it is just a configuration, you can set it default to 1.8.
