### ISSUE TITLE
Remove `gitee-mirror.yml` from Github workflows

### ISSUE THREAD

**Issue by SteveYurongSu** [apache/incubator-eventmesh#380]
I think we should remove the `gitee-mirror.yml` from workflows because it uses actions that are not allowed by the Apache.

![image](https://user-images.githubusercontent.com/30497621/120299937-0f5a7400-c2fe-11eb-9bd3-ac0d53a2c727.png)

![image](https://user-images.githubusercontent.com/30497621/120299982-1b463600-c2fe-11eb-8da5-a128a54d70bd.png)

**Comment by qqeasonchen** [comment]
good suggestion, thanks.
