### ISSUE TITLE
Could we support Redis?

### ISSUE THREAD

**Issue by jjz921024** [apache/incubator-eventmesh#389]
Hi, all

Do we have any plans to support redis as event store?

Maybe we can use Pub/Sub of redis to spread event between different nodes

In addition event store, there are else use case in EventMesh?

**Comment by qqeasonchen** [comment]
good suggestion

**Comment by SteveYurongSu** [comment]
Hi, is there anyone working on this issue?
If there is no one, I'd like to work on it :D

**Comment by jjz921024** [comment]
> Hi, is there anyone working on this issue?
> If there is no one, I'd like to work on it :D

hi, i am working on this issue, but not finish. I will creatr pull request. could you help me review the code？

**Comment by jjz921024** [comment]
Also, Could we use [Redis Streams](https://redis.io/topics/streams-intro) instead of Pub/Sub, because it's more like a MQ.

or maybe exist two way to connect redis in the meanwhile, switch by SPI

**Comment by SteveYurongSu** [comment]
> > Hi, is there anyone working on this issue?
> > If there is no one, I'd like to work on it :D
> 
> hi, i am working on this issue, almost finish. I will create pull request late. could you help me review the code？

Sure! it's a good chance for me to learn from you!

> Also, Could we use Redis Streams instead of Pub/Sub, because it's more like a MQ.

+1. Using Redis Streams is better.

**Comment by qqeasonchen** [comment]
@jjz921024 @SteveYurongSu Streaming is a good feature, you can define the interface in connector-api.
