### ISSUE TITLE
Does RPC call support any  routing strategy ? 

### ISSUE THREAD

**Issue by RustRw** [apache/incubator-eventmesh#4]
类似 路由上是树型分布的多节点. 一个请求需要发往全部或部分节点. 有些子节点网络是不通的.

是否支持通过路由转发到对应的节点.

**Comment by wqliang** [comment]
你描述的“一个请求需要发往全部或部分节点”是指什么？是否可以把具体场景描述一下？

**Comment by qqeasonchen** [comment]
我理解是配置指定ip调用吗？或者配置权重之类的？ @RustRw

**Comment by RustRw** [comment]
@wqliang @qqeasonchen  场景是这样的,  每一台机器我都知道, 但是网络不能直连, 有些关键节点有转发属性, 比如某些比较安全的行业里, 地域之间就一两台机器是通的. 这个时候需要加一层设计过的代理. 不知道是否可以有更通用一些的方式(代理)实现.

**Comment by wqliang** [comment]
@RustRw 我理解你遇到的场景是，通过若干台与两边网络都互通的机器，打通网络不互通的两堆机器。这种场景用总线这种方式是能够解决的。像DeFiBus的总线实现方式，就是在总线这一层增加了类似就近监听消费之类的自定义逻辑。可以交流一下你的思路或者理解，或许可以碰出一些新的思路。

**Comment by qqeasonchen** [comment]
@RustRw 可以加群沟通一下

**Comment by RustRw** [comment]
> @RustRw 可以加群沟通一下

好的
