### ISSUE TITLE
What is Apache Event Mesh

### ISSUE THREAD

**Issue by msdhinesh-geek** [apache/incubator-eventmesh#415]
Hi All,
I have been following Apache Event Mesh for couple of months, its seems interesting to me, Even though am not able to find where it can fit to resolve real time problem.
As per my understanding, Event Mesh is a event-driven architecture framework used to create distributed asynchronous event processing application(like micro services etc , one of example as per my understanding). 
Following area of improvements need to achieve Event Mesh as quality project.
1. Distributed architecture issues - process availability, quick responsiveness and reconnection logic if any failure
Discussion is going on - #349 
2. Atomic transaction issue 
3. Governance of event processor components
4. etc

I like to contribute any of above future to Event Mesh, Thanks.

**Comment by qqeasonchen** [comment]
@msdhinesh-geek hi，glad to see you are intrested in eventmesh, here is the introduction https://thestack.technology/apache-event-mesh, eventmesh positioned between the application and envoy as a multi-runtime https://github.com/apache/incubator-eventmesh#what-is-eventmesh , welcome to contribue.

**Comment by msdhinesh-geek** [comment]
@qqeasonchen  Hi, As per reference my understanding was right :-). Let me know what are the upcoming feature for Event Mesh release, I like to contribute.

**Comment by qqeasonchen** [comment]
@msdhinesh-geek https://github.com/apache/incubator-eventmesh/issues/274 is the highest priority, you can work on CloudEvents or Event Streaming if you like.

**Comment by msdhinesh-geek** [comment]
Hi All,
Why can't we do following approach to develop Event Mesh, it will be fun and learning too.

1.Community Call
Every two weeks we host a community call to showcase new features, review upcoming milestones, and engage in a Q&A. 

2.Videos and Podcasts
We have a variety of keynotes, podcasts, and presentations available to reference and learn from.

**Comment by qqeasonchen** [comment]
@msdhinesh-geek thanks for your suggestions, really nice, community call was irregularly scheduled, i will try to push these two forward.

**Comment by xwm1992** [comment]
> Hi All,
> Why can't we do following approach to develop Event Mesh, it will be fun and learning too.
> 
> 1.Community Call
> Every two weeks we host a community call to showcase new features, review upcoming milestones, and engage in a Q&A.
> 
> 2.Videos and Podcasts
> We have a variety of keynotes, podcasts, and presentations available to reference and learn from.

Hi, @msdhinesh-geek the arrangement of the SIG meeting is here https://github.com/apache/incubator-eventmesh/wiki/EventMesh-SIG-Meeting
