### ISSUE TITLE
failed to compile the project in java11

### ISSUE THREAD

**Issue by tydhot** [apache/incubator-eventmesh#422]
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/27889201/124755893-7d7a0280-df5e-11eb-8426-c13bc114c7d5.png">
Here is the error.

**Comment by xwm1992** [comment]
> <img alt="image" width="1384" src="https://user-images.githubusercontent.com/27889201/124755893-7d7a0280-df5e-11eb-8426-c13bc114c7d5.png">
> 
> Here is the error.

Yes, please use jdk8 to build the project.

**Comment by ruanwenjun** [comment]
@tydhot  @xwm1992 Hi, right now, the develop branch can be build by jdk11. It can build successfully on my machine, could you please try again.
