### ISSUE TITLE
Using templates to encourage useful issues and PRs

### ISSUE THREAD

**Issue by SteveYurongSu** [apache/incubator-eventmesh#425]
This PR provides PULL_REQUEST_TEMPLATE & ISSUE_TEMPLATE.

Github official docs for PULL_REQUEST_TEMPLATE & ISSUE_TEMPLATE: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/using-templates-to-encourage-useful-issues-and-pull-requests

PULL_REQUEST_TEMPLATE describes our community's specification for submitting PR.

ISSUE_TEMPLATE provides template for issues such as bug_report / feature_request / enhancement_request / doc_related / question. Issues created by users using ISSUE_TEMPLATE will be automatically labeled with bug / feature / enhancement / doc / question, which is convenient for community management.

**Comment by SteveYurongSu** [comment]
Using PULL_REQUEST_TEMPLATE:

![image](https://user-images.githubusercontent.com/30497621/125018536-e15c1280-e0a7-11eb-9cfa-483282a3236d.png)

**Comment by SteveYurongSu** [comment]
Using ISSUE_TEMPLATE:

![image](https://user-images.githubusercontent.com/30497621/125018798-62b3a500-e0a8-11eb-96b7-8cd94c3f2138.png)

**Comment by SteveYurongSu** [comment]
Hi @qqeasonchen @xwm1992 , is there anything else I need to do for the PR?

**Comment by qqeasonchen** [comment]
no comments, nice job.
