### ISSUE TITLE
Expose clientmanager/admin APIs as RESTful APIs

### ISSUE THREAD

**Issue by yzhao244** [apache/incubator-eventmesh#435]
### Is your enhancement request related to a problem? Please describe

Yes,  the clientmanager/admin APIs which are exposed from eventmesh-runtime module are not following the best practice of RESTful APIs . The problems could be seen by API urls such as "showClient", "rejectAllClient" ,"redirectClientByPath"

### Describe the solution you'd like

Add a new module such as eventmesh-rest which optimizes the existing admin/clientmanager APIs and expose them as RESTful APIs. 

### Describe alternatives you've considered
I will follow up and provide more details later. However, I would like to report this to the community and initiate a discussion here. :) . Please provide your feedbacks.

**Comment by qqeasonchen** [comment]
good suggestions, just go ahead.

**Comment by qqeasonchen** [comment]
#346 #349 are related to this.

**Comment by qqeasonchen** [comment]
@yzhao244 I think you can submit this pr first.

**Comment by qqeasonchen** [comment]
@yzhao244 Is there any updates here?

**Comment by yzhao244** [comment]
@qqeasonchen Yes,  Basically, my idea is to move httpserver context creation, handlers along with its dependencies such as Utils classes to eventmesh-rest module.  Inside the module, a new utility class called "RequestMapping" maps RESTful RequestUrl to the corresponding handler method and extracts values from path variables. As my sample handler class code indicates, any request invokes REST API "/schemaregistry/subjects/{subject}/versions" eventually calls createSchemaHandler method. Additionally, subject value is extracted from the path variable {subject} and passed to handler method as well.   

![image](https://user-images.githubusercontent.com/15642771/129267814-3e01eac8-d925-40db-bc87-0e53cc4cf28e.png)

**Comment by yzhao244** [comment]
HttpServer is still created and run inside eventmensh-runtime. Only the server.createContext part and handlers move to eventmesh-rest module.

**Comment by qqeasonchen** [comment]
@yzhao244 thanks, you can see the new pr #498 , maybe you can give some updates as well, after all, you are the first contributor of this feature :), i hope you can be continue on this, thanks again.

**Comment by JunjieChou** [comment]
Hi, @yzhao244. I would like to coorperate with you on Open Schema related coding part. Any updates here?

**Comment by yzhao244** [comment]
@JunjieChou Great suggestions actually :) . Btw, I am planning contributing eventmesh-openschema-rest module along with a readme file and maybe some skeleton code under the main eventmesh-openschema-plugin module

for example, eventmesh-openschema-plugin/eventmesh-openschema-rest/readme.md which contains my proposed details of EventMesh Schema Registry REST APIs such as REST URL, payload and examples.  
eventmesh-openschema-plugin/eventmesh-openschema-rest/.../controller/SchemaRegistryController.java which only contains some skeleton codes.

I will notify you as soon as I have a PR ready. :)

**Comment by JunjieChou** [comment]
@yzhao244 Hi, good to hear that you are going to start a readme file.

Actually, I have started the coding of the separated RESTful Schema Registry. 

Inspired by what you have coded, I created a new module called ```OpenSchemaRegistry``` under ```eventmesh-openschema-plugin``` as a separate service based on Spring-boot and spring-data-jpa. 

For now, I have accomplished the ```/schemas```  controller. Let me pull a request later. I am newly to these frameworks and welcome reviews and suggestions.

**Comment by JunjieChou** [comment]
@yzhao244 I have created a pr to your forked repository. Hope for reviewing 😊 !

**Comment by yzhao244** [comment]
@JunjieChou Sure, I can definitely review. :) . Btw, did you have a chance to discuss with the community of using SpringBoot and Spring JPA for Schema Registry in EventMesh project. Maybe we can add Eason and other members to this issue to have an open discussion. :) 

My initial thought was exposing Schema Registry REST APIs by leveraging the current EventMesh's ClientManagerController's design of using HttpServer.createContext(""). However, modifying the url and handlers to make the APIs more RESTful without using another Framework. Basically, Schema Registry and Runtime run on the same server. Therefore, I wasn't thinking of adding another framework to EventMesh.

Anyways, I can share some implementations with the community and it could be just my personal thought. lol

@qqeasonchen @ruanwenjun @jinrongluo WDYT

**Comment by ruanwenjun** [comment]
@yzhao244 I agree with using SpringBoot, since we may need to add a new module such like admin-server, it works as a control plane and provide some interface to manage the eventmesh-runtime module and other configuration(e.g. schema).
SpringBoot can help us a lot, and in runtime-module, I think we may don't need to import spring dependency.

**Comment by qqeasonchen** [comment]
I think eventmesh-admin moudle is great.

**Comment by ruanwenjun** [comment]
@yzhao244 @qqeasonchen The topology may look like below, this is a simple demo, the eventmesh-runtime is decentralization and ligntwight. For third-part storage, we may only need to rely on registry center,
![image](https://user-images.githubusercontent.com/22415594/131803530-0d2551b7-7a48-4345-a5aa-aba1e441776b.png)

**Comment by yzhao244** [comment]
@ruanwenjun @qqeasonchen @JunjieChou I agree with eventmesh-admin module, sounds a very good idea. eventmesh-admin module can in the future becomes a management layer which exposes Admin or Schema REST APIs to UI console for end-user to do managements. 

I can rework my existing PR #513 to create eventmesh-admin module. Just double confirm, I will name this new module as "eventmesh-admin" instead of "eventmesh-admim-plugin", am I right? :)

**Comment by yzhao244** [comment]
@ruanwenjun Based on your topology image above, do you think schema registry should be a child module of eventmesh-admin?

For example
eventmesh-admin/eventmesh-admin-schemaregistry
eventmesh-admin/eventmesh-admin-clientmanager

**Comment by ruanwenjun** [comment]
@yzhao244 I think we can leave the plugins out for now, we can just add an admin module.

**Comment by yzhao244** [comment]
> @yzhao244 I think we can leave the plugins out for now, we can just add an admin module.

Sounds good. :)
