### ISSUE TITLE
[Discuss] Eventmesh code style specification

### ISSUE THREAD

**Issue by ruanwenjun** [apache/incubator-eventmesh#444]
## Feature Request
To ensure consistent code style and improve code quality, I think it is necessary to discuss code style specification now.
The specification includes two parts: suggest and mandatory. 
The mandatory specification can be written into `codestyle` and `checkstyle` file, only pr meets the mandatory specification can be merged. Suggest specification can be break in sometimes, it's also recommended following the suggest specification.
Follow the code style specification when submitting pr and conducting code review.

## Mandatory specification
1. All package in source code should be named start with `org.apache.eventmesh.{module}`.
2. Block indentation with 4 spaces.
3. Don't exceed 100 columns.
3. All method in interface should have clear comments.
4. The source code files should only contain English.
5. No more than two consecutive blank lines.
6. Class name should be named by `UpperCamelCase` style, attributes and method name should be named by `lowerCamelCase` style, the constant should be named by `CONSTANT_CASE` style.
7. Method in Unit test should be named by test{Method}_case, e.g. testHello_thorwUserException.
8. ...

## Suggest specification
1. Each method should be as short as possible, no more than 100 lines.
2. Each test method should test just one case and never contain more than two cases.
3. The method name should be a verb and the Class name should be a noun.
4. Using meaningful names and don't add comments anywhere.
5. Using concrete data structures and avoid using Map<String, Object> to describe data.
6. ...

Here is I can think of, welcome to add and discuss.

**Comment by qqeasonchen** [comment]
Glad to see it, and it is time to Do it now.

**Comment by ruanwenjun** [comment]
For better maintain, we can remove the code style file, since the checkstyle can also help us to format code in IDE. And we use checkstyle file to check the code style when we run GitHub CI.
