### ISSUE TITLE
Quick Start is confusing

### ISSUE THREAD

**Issue by iPine** [apache/incubator-eventmesh#452]
## Documentation Related

- The term ‘Remote Deploy’ in the Quick Start Instruction may be confusing. 
The naming of the two deployment methods can be changed to：` 1 Deploy ` & `2 Developer Setup`
- The zip package link may be updated to: https://github.com/apache/incubator-eventmesh/releases 
![image](https://user-images.githubusercontent.com/22928321/126513105-b9416233-0d86-4611-b115-f6a1bf0f16b9.png)

**Comment by qqeasonchen** [comment]
@iPine you can refer to the quckstar doc of develop branch, you can figure it out the problem when deploy.

**Comment by ruanwenjun** [comment]
Closed by no reply.
