### ISSUE TITLE
Automatic License report and check

### ISSUE THREAD

**Issue by xwm1992** [apache/incubator-eventmesh#456]
### Is your enhancement request related to a problem? Please describe

Every time we release the package under the Apache repository, we need check each dependency's license carefully, and we need to support dependency's license report and check automatically.

### Describe the solution you'd like
The license report plugin can integrate this https://github.com/jk1/Gradle-License-Report, it support license report and check. You can also refer to this license check sh https://github.com/apache/skywalking/blob/master/tools/dependencies/check-LICENSE.sh and support a read.me for how to using this license check plugin, thks.

Apache License Policy : https://www.apache.org/legal/resolved.html

**Comment by ruanwenjun** [comment]
Maybe I can do this work, If we use the shell script to check the license, it may need us to store all license in a trust file, and once we add a new jar, we need to add the license in the trust file.
