### ISSUE TITLE
LiteProducer async request code is sync

### ISSUE THREAD

**Issue by ruanwenjun** [apache/incubator-eventmesh#473]
## Bug Report
In `LiteProducer.java`, you can find the below method:
https://github.com/apache/incubator-eventmesh/blob/737c0f09efeba61a62653d33fd553491af7d0deb/eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer/LiteProducer.java#L207-L245

Does this method want to send async request ? It seems that it send sync reqeust.

We may need to change the request code to `MSG_SEND_ASYNC`

**Comment by xwm1992** [comment]
This is not bug in my opinion，the request method with rrcallback is using for send sync message, you can refer the protocol.md.

**Comment by ruanwenjun** [comment]
Thanks
