### ISSUE TITLE
When do you plan to open source completely?

### ISSUE THREAD

**Issue by wangjingquang** [apache/incubator-eventmesh#5]
下述这些功能大概什么时候可以开源？ 有时间计划吗？

服务路由和定位：动态路由及定位(后续开源)
服务代理：TCP/HTTP及多语言的代理(后续开源)
服务治理：服务元数据的管理(后续开源)
平滑升级：平滑升级、平滑扩容(后续开源)

**Comment by qqeasonchen** [comment]
@wangjingquang 正在准备中，敬请期待，目前开源的功能是完整的，可以放心使用

**Comment by javaliming0424** [comment]
源码可以运行么。

**Comment by keranbingaa** [comment]
> 源码可以运行么。

@javaliming0424  gradle构建好后可以直接运行
