### ISSUE TITLE
There is a typo in SubscriptionItem class in eventmesh-common module

### ISSUE THREAD

**Issue by jinrongluo** [apache/incubator-eventmesh#520]
### Describe the bug

There is a typo in SubscriptionItem class in eventmesh-common module

private field **SubcriptionType** is a typo, it should be **SubscriptionType**

```
package org.apache.eventmesh.common.protocol;

public class SubscriptionItem {

    private String topic;

    private SubscriptionMode mode;

    private SubcriptionType type;
```

### Environment

- OS: [e.g. Ubuntu 21.04 LTS]
- EventMesh version(s): [e.g. 1.2.0]
- RocketMQ version(s): [e.g. 4.7.1]
- ...

### Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by ruanwenjun** [comment]
@jinrongluo You can report in this issue, and it's better not create a new issue.
- https://github.com/apache/incubator-eventmesh/issues/405

**Comment by jinrongluo** [comment]
Thanks I will do that. and close this issue.
