### ISSUE TITLE
Typo fix in EventMesh Architecture Diagram

### ISSUE THREAD

**Issue by wuwenzhao** [apache/incubator-eventmesh#534]
## Documentation Related
https://github.com/apache/incubator-eventmesh/blob/develop/README.md
https://github.com/apache/incubator-eventmesh/blob/develop/README.zh-CN.md

## Typo Fix
**"choregography" -> "choreography"**

![image](https://user-images.githubusercontent.com/4035972/134612882-97d393bb-bed6-4bef-9cf1-75339246c81b.png)

**Comment by qqeasonchen** [comment]
@wuwenzhao thanks for you reminder,welcome to try and contribute to eventmesh.
