### ISSUE TITLE
Document path error

### ISSUE THREAD

**Issue by Hu-Tu-Tu** [apache/incubator-eventmesh#538]
## Documentation Related

After the name of the Chinese documents are modified, the relative path of the relevant Chinese documents such as `quickstart.md`, `README.zh-CN` has not been modified. Clicking the link directly cannot open the corresponding Chinese documents.

**Comment by ruanwenjun** [comment]
@Hu-Tu-Tu Could you please provide more details? e.g. which URL is wrong.
I check the Chinese readme.md and quick-start doc,  it's correct. Maybe this issue has been fixed.

**Comment by ruanwenjun** [comment]
Closed by no reply.
