### ISSUE TITLE
How does Eventmesh support a cluster of multiple eventmesh runtime instances

### ISSUE THREAD

**Issue by jinrongluo** [apache/incubator-eventmesh#546]
In production deployment of eventmesh in cloud environment, eventmesh cluster of multiple instances is required for high availability and fault tolerance.

From the code study, eventmesh runtime using local cache Concurrent Map to store client and session information. For example, 
- HTTP Server side: localConsumerGroupMapping and localClientInfoMapping
- TCP Server side:  sessionTable and clientGroupMap

My question is when multiple eventmesh runtimes are running as a single cluster, how these local cache map each each instance are synchronized? 

If these local cache are not synchronized, problem happens when incoming requests are load balanced into the cluster.

For example, a **SUBSCRIBE** request is routed to eventmesh runtime instance 1. then later **UNSUBSCRIBE** request is routed to to instance 2,  UNSUBSCRIBE request will failed.  (That's because the actual subscriber is in instance1)

**Comment by jinrongluo** [comment]
@vongosling

**Comment by xwm1992** [comment]
we need to implement the `eventmesh-registry-plugin` for this.

**Comment by jinrongluo** [comment]
Thanks @xwm1992 this is a good suggestion for eventmesh-registry-plugin
