### ISSUE TITLE
[Enhancement] Add maven dependency guide in java example

### ISSUE THREAD

**Issue by ruanwenjun** [apache/incubator-eventmesh#579]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

User want to use eventmesh java sdk, they need to add eventmesh-sdk-java to their pom.xml/build.gradle, this should be addressed in quick start.
https://mvnrepository.com/artifact/org.apache.eventmesh/eventmesh-sdk-java

### Describe the solution you'd like

Add java client guide like pulsar in quick start.
https://pulsar.apache.org/docs/en/client-libraries-java/

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by HoffmanZheng** [comment]
There is doc of [eventmesh-sdk-java-quickstart](https://github.com/apache/incubator-eventmesh/blob/master/docs/en/instructions/eventmesh-sdk-java-quickstart.md) (and also [the chinese version](https://github.com/apache/incubator-eventmesh/blob/master/docs/cn/instructions/eventmesh-sdk-java-quickstart.md)), is that not enough for a java client guide?
Enrich the above mentioned doc, or write a brand new java client guide, which do you prefer?

**Comment by HoffmanZheng** [comment]
Assign this to me.
