### ISSUE TITLE
[Feature] Add jdk11 compile/test in ci

### ISSUE THREAD

**Issue by ruanwenjun** [apache/incubator-eventmesh#582]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

I have test in my local environment, jdk11 is supported in EventMesh(If not it should be fixed to support jdk11).

It's need to add jdk11 build/test in github ci.

Related issue #422 should be closed after this issue be fixed

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by vongosling** [comment]
Good catch for this feature.
