### ISSUE TITLE
[Bug] Consumer subscription topic is invalid

### ISSUE THREAD

**Issue by hagsyn** [apache/incubator-eventmesh#590]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

-OS[windows 10] -EventMesh version[1.2.0] -RocketMQ version:[4.5.1]

### What happened

When consumers subscribe, the parameters are "url" and "topicList". In fact, only the first topic of topicList takes effect!

### How to reproduce

1. Directly in the source code test project, when consumers start, give topicList two topics.
![image](https://user-images.githubusercontent.com/44764414/141776762-822f73c9-a477-48e1-92d2-2ba228f44daa.png)

2. The properties : eventMesh.connector.plugin.type=rocketmq
3. The test sends the message of the first topic, you can see that it is successful, and the consumer has consumed it.
4. Test sending the message of the following topic, you can see that the controller did not request to come in.
5. Check rocket-console and find that the message is sent to rocketmq.
 
![image](https://user-images.githubusercontent.com/44764414/141778678-f5cf35bc-a1bd-4278-83e4-dc3ad455a6f0.png)

### Debug logs

1. When the consumer starts, eventmesh-runtime receives the request, you can see that there are two topics.
<img width="960" alt="4433a681318391e1f19b2cefe508f8f" src="https://user-images.githubusercontent.com/44764414/141777881-cbc88c85-5928-4c6c-8c30-e13889011a15.png">
![022ed3e059ad1386a239fcb41d9a0b0](https://user-images.githubusercontent.com/44764414/141777890-73fab4cc-b9c2-4fcd-9c0b-45fb40f8e6f6.png)

2. Then by locating, you can see that there is only one topic for [eventMeshHTTPServer.localConsumerGroupMapping].
![b60b89143fee6d5e6f0b36e9b84b1a4](https://user-images.githubusercontent.com/44764414/141778251-f7ceb86d-750d-4b58-ae39-566463c0770a.png)

3. It is judged that there is a problem with the put logic here and needs to be optimized.
![00f3d76267d4bae97f2614a15af3c02](https://user-images.githubusercontent.com/44764414/141778411-f8c69861-3f65-4534-94c1-4664e8dd7e64.png)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by xwm1992** [comment]
I reopen this issue for this change cause the `ConcurrentModificationException` during http sub with multi topics(>2) @hagsyn , you can submit the new pr for fix this and relate this issue, thks. 
![image](https://user-images.githubusercontent.com/13237619/142588589-d551d54c-ffe3-4599-b811-a4472ff20a72.png)
