### ISSUE TITLE
[Enhancement] Add openschema dependency to eventmesh

### ISSUE THREAD

**Issue by yzhao244** [apache/incubator-eventmesh#614]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

I would like to suggest to add openschema dependency to eventmesh project and create a client to communicate with openschema registry. Since openschema community has recently published the first version of OpenSchema Registry implementation which is a standalone schema registry server and maintained by the OpenSchema community,  eventmesh project can directly make a reference to the openschema dependency instead of maintaining openschema implemention within eventmesh project itself. 

### Describe the solution you'd like

Remove the current openschema implementation out of eventmesh project and add openschema dependency to eventmesh project. 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yzhao244** [comment]
@ruanwenjun @qqeasonchen

**Comment by qqeasonchen** [comment]
ok, do we need confirm with @JunjieChou ?

**Comment by JunjieChou** [comment]
> ok, do we need confirm with @JunjieChou ?

sure

**Comment by JunjieChou** [comment]
> ok, do we need confirm with @JunjieChou ?

sure ok

**Comment by vongosling** [comment]
Any update for this thread?

**Comment by qqeasonchen** [comment]
@yzhao244 hi, Could you please help to fix it?

**Comment by jzhou59** [comment]
Hi, I have a pr for the schema client api. I could continue this.
