### ISSUE TITLE
[Question] can`t find rocketmq-client.properties

### ISSUE THREAD

**Issue by socket515** [apache/incubator-eventmesh#626]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

doc link [https://github.com/apache/incubator-eventmesh/blob/develop/docs/en/instructions/eventmesh-runtime-quickstart-with-docker.md](https://github.com/apache/incubator-eventmesh/blob/develop/docs/en/instructions/eventmesh-runtime-quickstart-with-docker.md)

the [eventMesh.properties](https://github.com/apache/incubator-eventmesh/blob/develop/eventmesh-runtime/conf/eventMesh.properties) and [rocketmq-client.properties](https://github.com/apache/incubator-eventmesh/blob/develop/eventmesh-runtime/conf/rocketmq-client.properties) is not found

**Comment by qqeasonchen** [comment]
@socket515 can you find it in the docker?

**Comment by ruanwenjun** [comment]
@socket515 You can find `eventmesh.properties` at https://github.com/apache/incubator-eventmesh/tree/develop/eventmesh-runtime/conf, and `rocketmq-client.properties ` at https://github.com/apache/incubator-eventmesh/tree/develop/eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/resources

**Comment by xwm1992** [comment]
@socket515 Whether the problem has been solved?

**Comment by zmt-Eason** [comment]
If you use rocketmq as eventstore, you should copy rocketmq-client.properties in package eventmesh-connector-plugin to conf in package runtime, which is not mentioned in quickstart doc.
