### ISSUE TITLE
[Enhancement] maven dependencies improvement on build.gradle file

### ISSUE THREAD

**Issue by jinrongluo** [apache/incubator-eventmesh#632]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

There are some maven dependencies in the project's build.gradle are not out of date, or duplicated.  This will improve the adoptions of this project in the community and enterprise.

### Describe the solution you'd like

I would like to clean up and improve the maven dependencies in the project build.gradles.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by vongosling** [comment]
Good catch~

**Comment by vongosling** [comment]
Some works have been done, pls see the latest commits. We could pay more attention here later. @qqeasonchen

**Comment by vongosling** [comment]
It seems our IT should not check the checktyle...gradlew clean build jacocoTestReport checkLicense -x check
