### ISSUE TITLE
[Enhancement] Update to log4j 2.x

### ISSUE THREAD

**Issue by ruanwenjun** [apache/incubator-eventmesh#642]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

I find we use log4j2 in EventMesh, 
```java
"org.apache.logging.log4j:log4j-api:2.13.3"
"org.apache.logging.log4j:log4j-core:2.13.3"
"org.apache.logging.log4j:log4j-slf4j-impl:2.13.3"
```
this lib has been reported some big security issues today, and we may need to solve this.

### Describe the solution you'd like

Upgrade log4j version or use logback.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by vongosling** [comment]
I will close the issue and  pr. I think EventMesh PPMC should pay more attention to this serious problem as soon as possible. Strictly speaking, such problems need to be transmitted through the security channel. Try not to display them externally. Apache EventMesh specifically offers security features and is responsive to issues around its features. If you have any concern around Security or believe you have uncovered a vulnerability, please report it via the e-mail address security@apache.org. In the message, try to provide a description of the issue and ideally a way of reproducing it.

Dealing with fixed issues or general questions on how to use the security features should be handled regularly via the users and the dev lists.

The ASF Security team maintains a page with a description of how vulnerabilities are handled, check their web page for more information. @qqeasonchen
