### ISSUE TITLE
[Question] Quick start doc dose not work.

### ISSUE THREAD

**Issue by horoc** [apache/incubator-eventmesh#652]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

I tried to start runtime by following the quickstart doc.

In root directory:
`
gradle clean dist
`

Dist result:

<img width="367" alt="截屏2021-12-15 上午2 29 20" src="https://user-images.githubusercontent.com/63457588/146058464-aa0f1b88-01cc-43d7-9f36-b8b9fbe99423.png">

At the bin directory:
`
sh start.sh
`
then the error occurs

<img width="1099" alt="截屏2021-12-15 上午2 30 05" src="https://user-images.githubusercontent.com/63457588/146058867-386feb7b-e41b-4c4c-95ed-284615ca4ea4.png">

I found the default plugin path is
`
org.apache.eventmesh.spi.loader.JarExtensionClassLoader#EVENTMESH_EXTENSION_PLUGIN_DIR
` 
<img width="734" alt="截屏2021-12-15 上午2 30 28" src="https://user-images.githubusercontent.com/63457588/146059279-9f3f7bc1-136e-489d-a984-1dfe91a40c8b.png">

It's seems like the default plugin path is mismatch from the structure of dist result.

**Comment by qqeasonchen** [comment]
@ruanwenjun can you take a look?

**Comment by xwm1992** [comment]
you should excute `gradle clean jar dist` first and then execute `gradle installPlugin` please. @horoc

**Comment by horoc** [comment]
> you should excute `gradle clean jar dist` first and then execute `gradle installPlugin` please. @horoc

I have tried, but It's not work for me, the errors in log file is the same.  

I tired to change the default plugin path in code, and It's seems works. 😂

**Comment by ruanwenjun** [comment]
@horoc Thanks for your feedback. If you try to start from source code, you can use -`DeventMeshPluginDir=your_plugin_path` to set the plugin directory. We will optimize this later.

**Comment by xwm1992** [comment]
![image](https://user-images.githubusercontent.com/13237619/146320556-3bcf9a1d-4516-4dd0-b8a5-e20f5b3eb35a.png)
please confirm that you have configured the ` default plugin path dist/plugin` in your jvm options. @horoc

**Comment by horoc** [comment]
> @horoc Thanks for your feedback. If you try to start from source code, you can use -`DeventMeshPluginDir=your_plugin_path` to set the plugin directory. We will optimize this later.



> ![image](https://user-images.githubusercontent.com/13237619/146320556-3bcf9a1d-4516-4dd0-b8a5-e20f5b3eb35a.png) please confirm that you have configured the ` default plugin path -DeventMeshPluginDir=dist/plugin` in your jvm options. @horoc

Thanks for your help ~
