### ISSUE TITLE
[Bug] EventMesh examples runtime error

### ISSUE THREAD

**Issue by li-xiao-shuang** [apache/incubator-eventmesh#687]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

MacBook Pro 2.6 GHz 六核Intel Core i7

### What happened

An error occurred when executing the EventMesh example.

### How to reproduce

1. start eventmesh runtime
2. run SyncRequestInstance example

### Debug logs

io.cloudevents.core.format.EventDeserializationException: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'contentStr': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (byte[])"contentStr with special protocal"; line: 1, column: 12]

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by xwm1992** [comment]
`SyncRequestInstance` has't been supported under the http mode .

**Comment by xwm1992** [comment]
This question is clear, so close the issue.
