### ISSUE TITLE
[Enhancement] Change the default merge strategy to squash

### ISSUE THREAD

**Issue by ruanwenjun** [apache/incubator-eventmesh#692]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

In most times, I think use squash merge is better, this can reduce the committs number and make the committs log clear.

A clear committs log can help developers easy to scan the history of changes.

### Describe the solution you'd like

Change the order in .asf.yaml

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ruanwenjun** [comment]
@qqeasonchen What do you think?

**Comment by qqeasonchen** [comment]
LGTM
