### ISSUE TITLE
The slack link is already dead

### ISSUE THREAD

**Issue by Shoothzj** [apache/incubator-eventmesh#702]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Chrome

### What happened

join slack button is broken

### How to reproduce

click the join slack button

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by qqeasonchen** [comment]
@Shoothzj hi, which button do you indicate?

**Comment by Shoothzj** [comment]
@qqeasonchen https://join.slack.com/t/apacheeventmesh/shared_invite/zt-yx3n2ak7-HcVG98CDqb~7PwgoDzgfMA

**Comment by qqeasonchen** [comment]
@Shoothzj ok，You can help to fix it, btw, will you contribute a pulsar connector?

**Comment by Shoothzj** [comment]
> @Shoothzj ok，You can help to fix it, btw, will you contribute a pulsar connector?

- - - I can't fix that because I don't know the right link 😂 
I have the willing, but i haven't figure out how.

**Comment by ruanwenjun** [comment]
> @qqeasonchen https://join.slack.com/t/apacheeventmesh/shared_invite/zt-yx3n2ak7-HcVG98CDqb~7PwgoDzgfMA

Please check again, I checked it can work now :)

**Comment by Shoothzj** [comment]
@ruanwenjun It shows that 
```
This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.
```
Sorry, it might be my fault wrong reading the error message, how can I join this slack channel now?

**Comment by ruanwenjun** [comment]
> @ruanwenjun It shows that
> 
> ```
> This link is no longer active
> To join this workspace, you’ll need to ask the person who originally invited you for a new link.
> ```
> 
> Sorry, it might be my fault wrong reading the error message, how can I join this slack channel now?

When you click the link, a window should pop up, but it doesn't pop?

![image](https://user-images.githubusercontent.com/22415594/148651838-3279b7a8-465b-492c-b808-16aa24cf235f.png)

**Comment by Shoothzj** [comment]
> 

Yes, it shows
![image](https://user-images.githubusercontent.com/12933197/148664306-67acf688-4e6c-48a8-a130-73a101d46a07.png)

**Comment by ruanwenjun** [comment]
@Shoothzj Oh, I find the link will be expire in 30d, here is a new link, please try again.
https://join.slack.com/t/apacheeventmesh/shared_invite/zt-11974dndy-cn3Aq638eleKwKPWP9tkLg

**Comment by Shoothzj** [comment]
@ruanwenjun It works. I open #705 to fix this issue :)
