### ISSUE TITLE
[Bug] Error when running example module without Zipkin working

### ISSUE THREAD

**Issue by Roc-00** [apache/incubator-eventmesh#713]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Running the starter and example module in IDEA.

### What happened

When spanExporter is set to Zipkin, if Zipkin is not running, an error will be reported when running the example module.
![image](https://user-images.githubusercontent.com/84842773/149334635-1703ba52-a1d4-4b85-bc38-34d3332aa980.png)

### How to reproduce

Run the starter and example module in IDEA without Zipking working.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by qqeasonchen** [comment]
@Roc-00 thanks, please help to fix it.
