### ISSUE TITLE
[Question] Some questions in grpc feature

### ISSUE THREAD

**Issue by xwm1992** [apache/incubator-eventmesh#718]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

Now that eventmesh support transfer message with http/tcp/grpc three ways, have some questions below:

- as we first design we have supported two protocols(cloudevents/eventmesh message)
- for http transfer method, we use the `HttpCommand` carry both protocols messages
- for tcp transfer method, we use the `Package` carry both protocols messages
- for grpc transfer method, we use the `EventMeshMessage`/`BatchMessage` carry both protocols messages

Now, for grpc transfer method, I just see convert the `cloudevents` to `eventmesh message`, like pic below. I just think this is a protocols conversion function, but if we treat this just as a message carrier, please don't name it as `EventMeshMessage` because this is a protocol.

![image](https://user-images.githubusercontent.com/13237619/149770313-660f563d-d493-4b27-99e8-c63d1bc0c901.png)

![image](https://user-images.githubusercontent.com/13237619/149769985-4657f8f1-2b7e-495a-aab8-66ae4edcfe20.png)

@jinrongluo please take a look, thanks

**Comment by jinrongluo** [comment]
Hi @xwm1992 Thanks for your review.

GRPC protocol messaging model is different from TCP and HTTP.  We have different message model for different Service/Operations: 

- EventMeshMessage
- BatchMessage
- Subscription
- Heartbeat

Detail is in this protobuf file:

https://github.com/apache/incubator-eventmesh/blob/grpc/eventmesh-protocol-plugin/eventmesh-protocol-grpc/src/main/proto/eventmesh-client.proto

**Comment by jinrongluo** [comment]
Discussed with @xwm1992 offline. We agree to rename EventMeshMessage to SimpleMessage.

**Comment by jinrongluo** [comment]
hi @xwm1992 as per your suggestion. I rename the GRPC publish message to SimpleMessage.

Here is the commit - https://github.com/apache/incubator-eventmesh/pull/723/commits/802b010ef6686ef4d891bee1214071f9d6787a1c

The PR is here - https://github.com/apache/incubator-eventmesh/pull/723

Thanks for review.

**Comment by xwm1992** [comment]
![image](https://user-images.githubusercontent.com/13237619/150936078-a4877130-2031-487a-bc68-aa034b1ebea5.png)
@jinrongluo Hi, I have some questions for the grpc structure of sdk module, for the Pub side, there batch\publish\request-reply three modes for publish; for the Sub side, I only find the async subcribe mode, how can I use the request-reply for grpc?

**Comment by vongosling** [comment]
I will close this issue, we could create a new issue to discuss the remaining issues for our new Grpc features.
