### ISSUE TITLE
[Enhancement] Update log4j to 2.17.1 (or newer)

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-eventmesh#735]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

https://github.com/apache/incubator-eventmesh/blob/master/build.gradle#L412 -- shows that log4j 2.17.0 is used but this too has a CVE. https://logging.apache.org/log4j/2.x/security.html

### Describe the solution you'd like

Update to v 2.17.1 or higher

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by ruanwenjun** [comment]
closed by #736
