### ISSUE TITLE
[Question] Eventmesh running memory cost

### ISSUE THREAD

**Issue by creeew** [apache/incubator-eventmesh#739]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

Hi, friends. Could you tell me the average memory cost when a eventmesh project running

**Comment by qqeasonchen** [comment]
@creeew Eventmesh has a very simple architecture, it acts as a computer node rather than a store, so memory is not the main consumption. but I agree it still has some optimizations.

**Comment by qqeasonchen** [comment]
@qqeasonchen btw, Eventmesh support cluster scale, so it may not a problem.
