### ISSUE TITLE
[Bug] LogExporter cannot be cast to EventMeshExporter

### ISSUE THREAD

**Issue by liwenzheng** [apache/incubator-eventmesh#748]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

master

### What happened

![image](https://user-images.githubusercontent.com/1767832/151113877-c2dc0a79-c4ac-4467-91a7-e3219621afa1.png)
![image](https://user-images.githubusercontent.com/1767832/151113939-4d773170-f92f-4702-b077-68612cdf4c8e.png)

### How to reproduce

use master ,you run startup.

### Debug logs

[main] ERROR org.apache.eventmesh.runtime.trace.OpenTelemetryTraceFactory - fail to set tracer's exporter,due to org.apache.eventmesh.runtime.exporter.LogExporter cannot be cast to org.apache.eventmesh.runtime.exporter.EventMeshExporter

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xwm1992** [comment]
@Roc-00 please take a look.

**Comment by liwenzheng** [comment]
> @Roc-00 please take a look.

I know, using exceptions to handle, but this is not a good way。

**Comment by ruanwenjun** [comment]
Use a ExporterManager to load the exporter is better, we can hold the mapping between exporter name and exporter instance. And in this case, does the LogExporter need to implements with EventMeshExporter?

**Comment by Roc-00** [comment]
> > @Roc-00 please take a look.
> 
> I know, using exceptions to handle, but this is not a good way。

Yes,you are right, my purpose was to set the logExporter as a default realization.

**Comment by Roc-00** [comment]
> Use a ExporterManager to load the exporter is better, we can hold the mapping between exporter name and exporter instance. And in this case, does the LogExporter need to implements with EventMeshExporter?

I am working on transforming trace into plugin.Thank you for your advices, and I will try to use ExporterManager in the trace-plugin.

**Comment by ruanwenjun** [comment]
> 

Great, you can refer to the other plugin module.

**Comment by ruanwenjun** [comment]
> > Use a ExporterManager to load the exporter is better, we can hold the mapping between exporter name and exporter instance. And in this case, does the LogExporter need to implements with EventMeshExporter?
> 
> I am working on transforming trace into plugin.Thank you for your advices, and I will try to use ExporterManager in the trace-plugin.

Great, you can refer to the other plugin module.
