### ISSUE TITLE
[Bug] Cloudevents published through TCP cannot be consumed through HTTP

### ISSUE THREAD

**Issue by xiehongfeng100** [apache/incubator-eventmesh#761]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Window

### EventMesh version

master

### What happened

I publish events to the EventMesh through TCP, but cannot be consumed by the HTTP subscriber.

### How to reproduce

According to the instruction [QuickStart](https://eventmesh.apache.org/zh/docs/instructions/eventmesh-runtime-quickstart/)：
1. Start the EventMesh runtime by running **org.apache.eventmesh.runtime.boot.EventMeshStartup**.
2. Push events through TCP by running **org.apache.eventmesh.tcp.demo.pub.cloudevents.AsyncPublish**.
3. Susbcribe topic "TEST-TOPIC-TCP-ASYNC" (same with cloudevents subject sent in step 2) through TCP by running **org.apache.eventmesh.http.demo.sub.SpringBootDemoApplication**. 
![image](https://user-images.githubusercontent.com/3980738/153143340-b33fc56f-16d3-4874-bda5-662a3977f2f4.png)

### Debug logs

Through debugging, I found there is a process publishing events to the HTTP subscriber. The problem is in **type conversion failure** (and with no logs). Detail is as below:
![image](https://user-images.githubusercontent.com/3980738/153141472-004d65dc-d8bd-4543-bc92-c7845a310c5e.png)

And I found **HttpCommand** and **Package** has a quite different structure.
![image](https://user-images.githubusercontent.com/3980738/153144634-33d289fd-32ad-489b-8596-061f25bc457d.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by qqeasonchen** [comment]
@xiehongfeng100 got it.

**Comment by zongtanghu** [comment]
Has anyone else put a pr to fix this issues? @qqeasonchen @ruanwenjun

**Comment by ruanwenjun** [comment]
> Has anyone else put a pr to fix this issues? @qqeasonchen @ruanwenjun

Not yet 😄 .

**Comment by zongtanghu** [comment]
Okay, @wangshaojie4039  you can put forward a pr to fix this bug!

**Comment by ruanwenjun** [comment]
@wangshaojie4039 If you are interested to fix this issue, I will assign to you.

**Comment by wangshaojie4039** [comment]
ok,I will fix it
