### ISSUE TITLE
[Enhancement] invalid code can be removed from the eventmesh-connector-plugin module

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#782]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

Some invalid code was found in this module.Such as:
<img width="640" alt="image" src="https://user-images.githubusercontent.com/91315508/155270904-68335b0e-d3ff-4948-86e2-26a301b335f6.png">
<img width="640" alt="image" src="https://user-images.githubusercontent.com/91315508/155270960-05218027-9ead-4074-abb4-4f64a3bc7282.png">
![image](https://user-images.githubusercontent.com/91315508/155270998-5e42a196-9cf7-44b0-ba06-a9b7f44e4353.png)

Located in:
1.eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/cloudevent/impl package.
2.eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/utils package.
3.rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/MessagingAccessPointImpl.java This class is commented out.
4.rocketmq/src/main/java/org/apache/rocketmq/client/impl/consumer/ConsumeMessageConcurrentlyService.java
5.eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/java/org/apache/eventmesh/connector/standalone/consumer/StandaloneConsumerAdaptor.java
6.eventmesh-connector-plugin/eventmesh-connector-standalone/src/main/java/org/apache/eventmesh/connector/standalone/producer/StandaloneProducerAdaptor.java
Suggestion: Delete invalid code.

**Comment by AhahaGe** [comment]
can I have a try?

**Comment by Alonexc** [comment]
> can I have a try?

Sure.

**Comment by AhahaGe** [comment]
please assign to me
