### ISSUE TITLE
[Question] Can I remove invalid code from the eventmesh-runtime module?

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#783]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

There is a lot of invalid code in the EventMesh-Runtime module, for example:
<img width="863" alt="Screen Shot 2022-02-23 at 14 48 02" src="https://user-images.githubusercontent.com/91315508/155272774-14a06bba-6d15-4bb1-9874-a03d26d4b4b2.png">
<img width="893" alt="Screen Shot 2022-02-23 at 14 49 38" src="https://user-images.githubusercontent.com/91315508/155272925-137bbc26-b16d-4af0-9071-0396c223f91c.png">

Located in:
1.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/util package.
2.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/patch: EventMeshConsumeConcurrentlyContext.java and EventMeshMessageListenerConcurrently.java
3.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/domain under this package has a few class is commented.
4.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/consumer package.
5.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor package.
6.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java
7.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/rebalance/EventmeshRebalanceImpl.java
8.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/ClientAckContext.java
9.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/DownStreamMsgContext.java
10.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/SessionPusher.java
11.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/SessionSender.java
12.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/Session.java
13.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task package

Suggestion: Delete invalid code.

**Comment by sarihuangshanrong** [comment]
let me do that.

**Comment by Alonexc** [comment]
> 让我这样做。

OK.
