### ISSUE TITLE
[Enhancement]  Some suggestions for the eventmesh-admin module. 

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#784]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

<img width="640" alt="image" src="https://user-images.githubusercontent.com/91315508/155280074-b8447ff3-d739-4cfa-a31d-02b3b9cd63cf.png">
<img width="640" alt="image" src="https://user-images.githubusercontent.com/91315508/155280209-122da610-c46f-4250-9243-4f3cd28b7816.png">
<img width="640" alt="image" src="https://user-images.githubusercontent.com/91315508/155280770-cef53fb6-ad8b-47cf-bc2d-ccbcf139c057.png">

AdminController, TopicsHandler, NetUtils, RequestMapping classes have reusable String constants.

Suggestion: Create a constant class under the admin package for these constants.

**Comment by AhahaGe** [comment]
please assign to me

**Comment by gzchen008** [comment]
got it

**Comment by gzchen008** [comment]
got it

**Comment by xwm1992** [comment]
> please assign to me

Hi, @AhahaGe , please leave this to the new guy and find if there are points of interest in roadmap.

**Comment by likegeek** [comment]
please let me try

**Comment by xwm1992** [comment]
> please let me try

@likegeek sorry this has been assigned to @gzchen008, we will continue to sort out some issues.

**Comment by AhahaGe** [comment]
> > please assign to me
> 
> Hi, @AhahaGe , please leave this to the new guy and find if there are points of interest in roadmap.

fine

**Comment by ruanwenjun** [comment]
Closed by #788
