### ISSUE TITLE
[Enhancement] Some suggestions for eventmesh-examples.

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#785]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

<img width="640" alt="image" src="https://user-images.githubusercontent.com/91315508/155282108-4f68a82d-4260-4629-8f41-8b36003d3030.png">
These constants are used in multiple classes and are proposed to be placed in a Constant class.
<img width="640" alt="image" src="https://user-images.githubusercontent.com/91315508/155282520-2181bc58-ea9d-4b46-a469-5e2539ac1aab.png">

Located in:eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/pub/eventmeshmessage/SyncRequest.java and eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/sub/eventmeshmessage/SyncResponse.java
You are advised to obtain it by reading the configuration file.
Such as:
<img width="750" alt="Screen Shot 2022-02-23 at 16 21 07" src="https://user-images.githubusercontent.com/91315508/155283121-be56029f-82f3-4d36-8054-1ffc4d86b245.png">

Invalid code in AsyncSubscribe class can be removed.
<img width="640" alt="image" src="https://user-images.githubusercontent.com/91315508/155283280-9696992b-6a9e-493e-baac-9698e556fbb3.png">

**Comment by likegeek** [comment]
please let me try
