### ISSUE TITLE
[Question] Some suggestions for the eventmesh-sdk-java module.

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#786]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

<img width="640" alt="image" src="https://user-images.githubusercontent.com/91315508/155291569-8c55979e-31a9-41d6-9b86-228eca4a0097.png">

Located in:eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/RequestContext.java
Invalid code that can be removed.

<img width="284" alt="Screen Shot 2022-02-23 at 17 28 42" src="https://user-images.githubusercontent.com/91315508/155293408-6dc4b3aa-a546-4375-87c1-42ffcd078e9a.png">
Located in:eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/consumer

These three classes do not seem to be in use and can be deleted.

**Comment by lucky-lsr** [comment]
please assign to me

**Comment by Alonexc** [comment]
> please assign to me

OK
