### ISSUE TITLE
[Feature] Support Knative as Eventing Infra

### ISSUE THREAD

**Issue by qqeasonchen** [apache/incubator-eventmesh#790]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

The high level mission of Knative Eventing is: Enable asynchronous application development through event delivery from anywhere. EventMesh can acts as Eventing Infra.

https://knative.dev/docs/
https://knative.dev/docs/eventing/

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by AmanSarraf** [comment]
I am a computer science major in my freshmen year. I have some experience with open source contributions, and I want to contribute to this issue under GSOC, I am proficient in JAVA and have knowledge of docker and Kubernetes.

**Comment by qqeasonchen** [comment]
> I am a computer science major in my freshmen year. I have some experience with open source contributions, and I want to contribute to this issue under GSOC, I am proficient in JAVA and have knowledge of docker and Kubernetes.

welcome Aman ：）

**Comment by pchengma** [comment]
Hello! I was selected for the "Apache EventMesh Support Knative as Eventing Infra" project in GSoC 2022. Could you please assign me? I will submit PRs for this project. Thanks very much!

**Comment by xwm1992** [comment]
> Hello! I was selected for the "Apache EventMesh Support Knative as Eventing Infra" project in GSoC 2022. Could you please assign me? I will submit PRs for this project. Thanks very much!

welcome~ @pchengma
