### ISSUE TITLE
[Doc] fix incorrect instruction in eventmesh-runtime-quickstart-with-docker.md

### ISSUE THREAD

**Issue by xwm1992** [apache/incubator-eventmesh#795]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

![image](https://user-images.githubusercontent.com/13237619/156094035-93da5794-c518-4778-8e4a-1b58ec1fee03.png)

above picture have the instruction error, please fix this change the `eventMesh.properties` -> `eventmesh.properties`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ZhangQuankang** [comment]
please assign to me
