### ISSUE TITLE
[Enhancement] compile project with junit error

### ISSUE THREAD

**Issue by xwm1992** [apache/incubator-eventmesh#796]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

![image](https://user-images.githubusercontent.com/13237619/156096894-959e324b-dafe-4326-a879-749a2ecaf445.png)
compile project with junit error
 

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/13237619/156097846-c465331c-d049-4520-97c5-b7522214953d.png)
please change `junit:junit` -> `junit:junit:4.13.2`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by hsld9527** [comment]
assign to me, please
