### ISSUE TITLE
[Enhancement] a complement to code optimization for the eventmesh-examples module

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#806]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

In the eventmesh-examples module,http and grpc are not code optimized

### Describe the solution you'd like

We suggest that such constants be placed in a constant class and the constant class be placed in the `eventmesh-examples/src/main/java/org/apache/eventmesh/common` package

<img width="679" alt="Screen Shot 2022-03-08 at 15 55 58" src="https://user-images.githubusercontent.com/91315508/157193493-3816eeac-011c-46e8-83e2-e2ba925fa63d.png"><img width="653" alt="Screen Shot 2022-03-08 at 16 13 46" src="https://user-images.githubusercontent.com/91315508/157194856-3d796ea5-e78c-4db2-83d0-441d9e094192.png">
<img width="432" alt="Screen Shot 2022-03-08 at 17 02 04" src="https://user-images.githubusercontent.com/91315508/157203490-56cd3540-e4c3-4847-94d2-64be80c027ab.png">

delete invalid code.
located in `eventmesh-examples/src/main/java/org/apache/eventmesh/tcp/demo/sub/eventmeshmessage/AsyncSubscribe.java`

<img width="408" alt="Screen Shot 2022-03-08 at 16 56 23" src="https://user-images.githubusercontent.com/91315508/157202417-2a1f8dfb-2773-41db-a0af-eda8cafa7e86.png">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by fengyongshe** [comment]
I'm willing to do it.
