### ISSUE TITLE
[Feature] Metadata consistency and persistent governance

### ISSUE THREAD

**Issue by vongosling** [apache/incubator-eventmesh#817]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

As we know, metadata is stored in the memory of the EventMesh. When a large-scale cluster encounters jitters, both consistency and reliability are at risk. Here, we hope to propose a metadata management system based on raft or gossip protocol. The dledger, etcd, or jgroups component can be introduced. Welcome to sign up and get the task:-)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by qqeasonchen** [comment]
ETCD is a good choice.
