### ISSUE TITLE
[Enhancement] Clean up useless code in the eventmesh-runtime module

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#838]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

I found a lot of useless code and some useless classes in the eventmesh-runtime module and recommended removing them.

### Describe the solution you'd like

Such as:
![image](https://user-images.githubusercontent.com/91315508/164183279-213443fc-2fe6-4cf3-8e2b-3baea6e62f12.png)
![image](https://user-images.githubusercontent.com/91315508/164183338-e6e35537-b6d9-4f95-b65a-2685b8a5a6f5.png)

We can remove the useless code, it is located in:
1.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/http/processor/inf package,ReplyMessageProcessor.class、SendAsyncMessageProcessor.class、BatchSendMessageProcessor.class
2.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/group/ClientGroupWrapper.java
3.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/ClientAckContext.java
4.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/push/DownStreamMsgContext.java
5.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/send/SessionSender.java
6.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/Session.java
7.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/HelloTask.java
8.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/task/ListenTask.java
9.eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/domain
These two interfaces are not used,we can remove the domain package and these two interfaces.
![image](https://user-images.githubusercontent.com/91315508/164185157-760ca900-f6e8-42bc-8f6d-517ecb776950.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by tjx-outlook** [comment]
Hi, I'm a first-time contributor and I'd like to try this issue.

Is it still available? If so, could you please assign it to me?

Thanks!
