### ISSUE TITLE
[Enhancement] Extraction of constants [eventmesh-protocol-meshmessage]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#839]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request
![image](https://user-images.githubusercontent.com/91315508/182796166-a069bca3-1b5e-4dda-8903-faa9e4288664.png)
![image](https://user-images.githubusercontent.com/91315508/164196979-fe7efb69-8d83-46ab-bcd4-625b09bef39b.png)
![image](https://user-images.githubusercontent.com/91315508/183795535-d79cc02f-e919-4a35-8deb-84fa6ac270c9.png)

### Describe the solution you'd like
Located at：eventmesh-protocol-meshmessage/src/main/java/org/apache/eventmesh/protocol/meshmessage/resolver
Extract these constants from the image into the MeshMessageProtocolConstant.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xwm1992** [comment]
> @Alonexc Hi, thanks for your feedback, agree with you that we can use the constant to replace. According to our [issue policy](https://github.com/apache/incubator-eventmesh/blob/master/CONTRIBUTING.md#open-an-issue--pr), we don't suggest creating an issue for these kinds of optimization, this will generate lots of minor issue, welcome to directly submit a PR if you think the code can be optimized. I will close this issue.

I understand your idea, this issue is set up for the first time to participate in The EventMesh contributor, I will label it as `good first issue` and reopen it, thanks.

**Comment by ruanwenjun** [comment]
> 

Got it, good idea.

**Comment by chakkk309** [comment]
Hi, I want to try it

**Comment by xwm1992** [comment]
> Hi, I want to try it

welcome for your contribution~

**Comment by chakkk309** [comment]
Hi@xwm1992, It looks like [RSTdefg](https://github.com/RSTdefg) has fixed the issue, I found out that he has made the corresponding commit.

**Comment by xwm1992** [comment]
> Hi @xwm1992, It looks like [RSTdefg](https://github.com/RSTdefg) has fixed the issue ([link](https://github.com/RSTdefg/incubator-eventmesh/commit/e66e7a4b02cb67d14936f139c50c11dda7202f05)), I found out that he has made the corresponding commit.

Yes, this issue is quietly simple, so we just merged another pull request from RSTdefg, his pull request for this issue hasn't been merged.
