### ISSUE TITLE
[Enhancement] Some optimizations to the eventmesh-sdk module

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#843]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Do some optimization.

### Describe the solution you'd like

located in:eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/tcp/common/PropertyConst.java

![image](https://user-images.githubusercontent.com/91315508/164358571-c2fad178-0008-4e19-9752-011350890150.png)
This class is not in use and it is recommended to delete it.

located in:eventmesh-sdk-java/src/main/java/org/apache/eventmesh/client/http/producer
![image](https://user-images.githubusercontent.com/91315508/164359608-1457c060-a70b-467a-b325-68ef8394c47f.png)
![image](https://user-images.githubusercontent.com/91315508/164359635-8da3ceac-d072-4d7c-8231-e8089c8f84b4.png)
![image](https://user-images.githubusercontent.com/91315508/164359653-b9df63e1-84fd-4b69-8f16-1b14155832ac.png)

The constant classes in the CloudDeventProducer, EventMeshMessageProducer, and OpenMessageProducer classes in this package suggest extracting a constant class and putting it there.in eventmesh - sdk - java/src/main/Java/org/apache/eventmesh/client/http directory and create a common directory will be the constant class into it,change the PROTOCOL_TYPE to CE_PROTOCOL, EM_MESSAGE_PROTOCOL, and OP_MESSAGE_PROTOCOL, respectively.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Markliniubility** [comment]
Hi,

I would like to work on this issue. Thanks!

**Comment by xwm1992** [comment]
> Hi,
> 
> I would like to work on this issue. Thanks!

welcome @Markliniubility

**Comment by xiaoyang-sde** [comment]
> Hi,
> 
> I would like to work on this issue. Thanks!

Welcome to the EventMesh community!

**Comment by Markliniubility** [comment]
> @Markliniubility How is the progress of this issue ?

Sorry about the delay! I just submitted the PR for it. Thanks!
