### ISSUE TITLE
[Enhancement] Clean up some useless constants and classes

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#844]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Clean up some useless constants and classes in the eventmesh-connector-plugin module.

### Describe the solution you'd like

located in:eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/common
The Constants and EventMeshContants classes in this package have a large number of unused Constants,we can remove them.
![image](https://user-images.githubusercontent.com/91315508/165042752-34c9345b-a86d-47d6-9268-b6340618ba49.png)
![image](https://user-images.githubusercontent.com/91315508/165042837-8ed01335-0b35-4798-9597-1bed48cfc1cd.png)

eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/domain/NonStandardKeys.java There are unused keys in this class
![image](https://user-images.githubusercontent.com/91315508/165043669-83389e01-6e4c-4e27-bb83-5b0975775287.png)

ConsumeRequest and RocketMQConstants, under the same package, are not used.
![image](https://user-images.githubusercontent.com/91315508/165045062-f379d5f2-0e7d-4dcc-81c7-2765eed2eabf.png)
![image](https://user-images.githubusercontent.com/91315508/165045096-0061e9dd-4855-4efb-b0d4-a59f72bc2aed.png)

eventmesh-connector-plugin/eventmesh-connector-rocketmq/src/main/java/org/apache/eventmesh/connector/rocketmq/promise/FutureState.java This class is useless, so we can remove this package and this class.
![image](https://user-images.githubusercontent.com/91315508/165045427-982ac485-9d27-4458-9b0a-0fe5b8b303da.png)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Witness167** [comment]
Hi,

I would like to work on this issue. Thanks!

**Comment by Alonexc** [comment]
@Witness167 Ok, welcome!

**Comment by xwm1992** [comment]
@Witness167 How is the progress of this issue ?

**Comment by SunnyBoy-WYH** [comment]
Hi!  can you assign this good first issue to me? thanks

**Comment by captainbkarthick** [comment]
@qqeasonchen ,
Looks like the fix for this issue is merged.
Requesting to check and close the issue.
