### ISSUE TITLE
[Bug] Could not find or load main class in eventmesh-examples

### ISSUE THREAD

**Issue by xuesongxs** [apache/incubator-eventmesh#847]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Linux

### EventMesh version

1.4.0

### What happened

Error: Could not find or load main class org.apache.eventmesh.tcp.demo.AsyncSubscribe

### How to reproduce

sh http_pub.sh
sh tcp_pub.sh
...

### Debug logs

Error: Could not find or load main class org.apache.eventmesh.tcp.demo.AsyncSubscribe

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by ruanwenjun** [comment]
@xuesongxs The entrypoint in the example script is incorrect,  I have seen you PR.
