### ISSUE TITLE
[Enhancement] Add test code for this module [eventmesh-security-plugin]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#858]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Add test code for eventmesh-security-plugin module.

### Describe the solution you'd like

Module name: eventmesh-security-acl,eventmesh-security-api and eventmesh-security-auth-http-basic
Located in: eventmesh-security-plugin
Task status: ×(unfinished) / √ (finished)

> Notes: This issue will not be closed, if you want to submit a pr to do some unit tests on this module or select some of the following classes to do some unit tests, please submit a detailed issue separately and linked to the pr you submitted.

| Task Status | Class | Type |
| :-----: | :----- | :----- |
| × | org/apache/eventmesh/acl/impl/AclServiceImpl.java | service |
| × | org/apache/eventmesh/api/acl/AclService.java | service |
| × | org/apache/eventmesh/api/auth/AuthService.java | service |
| × | org/apache/eventmesh/api/common/ConfigurationWrapper.java | common |
| × | org/apache/eventmesh/auth/http/basic/config/AuthConfigs.java | config |
| × | org/apache/eventmesh/api/exception/AclException.java | exception |
| × | org/apache/eventmesh/auth/http/basic/impl/AuthHttpBasicService.java | service |

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by zrsaber** [comment]
Please assign to me. I'll try to work on this.
