### ISSUE TITLE
[Enhancement] Add test code for this module [eventmesh-connector-standalone]

### ISSUE THREAD

**Issue by Alonexc** [apache/incubator-eventmesh#863]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Add test code for eventemsh-connector-standalone module.

### Describe the solution you'd like

Module name: eventmesh-connector-standalone
Located in: eventmesh-connector-plugin/eventmesh-connector-standalone
Task status: ×(unfinished) / √(finished)
>Notes: This issue will not be closed, if you want to submit a pr to do some unit tests on this module or select some of the following classes to do some unit tests, please submit a detailed issue separately and linked to the pr you submitted.

| Task Status | Class | Type |
| :-----: | :------ | :------ |
| × | org/apache/eventmesh/connector/standalone/broker/model/MessageEntity.java | model |
| × | org/apache/eventmesh/connector/standalone/broker/task/HistoryMessageClearTask.java | task |
| × | org/apache/eventmesh/connector/standalone/broker/task/SubScribeTask.java | task |
| × | org/apache/eventmesh/connector/standalone/broker/MessageQueue.java | broker |
| × | org/apache/eventmesh/connector/standalone/broker/StandaloneBroker.java | broker |
| × | org/apache/eventmesh/connector/standalone/consumer/StandaloneConsumer.java | consumer |
| × | org/apache/eventmesh/connector/standalone/consumer/StandaloneConsumerAdaptor.java | consumer |
| × | org/apache/eventmesh/connector/standalone/producer/StandaloneProducer.java | producer |
| × | org/apache/eventmesh/connector/standalone/producer/StandaloneProducerAdaptor.java | producer |
| × | org/apache/eventmesh/connector/standalone/resource/StandaloneConnectorResourceService.java | service |

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by titanventura** [comment]
Can I take this up ? Please assign me to this issue if it is not being worked on !

**Comment by HattoriHenzo** [comment]
It seems like this task hos not been already completed. Can you assign it to me, I will work on it.
