### ISSUE TITLE
[Enhancement] @EventMeshSPI eventMeshExtensionType attribute is not clear purpose

### ISSUE THREAD

**Issue by mroccyen** [apache/incubator-eventmesh#872]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

 @EventMeshSPI eventMeshExtensionType attribute is only used for the case of the jar package extension spi path, here can be perfected comment, it is best to modify the property name, I am not literally every time I understand what this property is used for, only know the type used to represent the spi

### Describe the solution you'd like

add commont or update name of @EventMeshSPI eventMeshExtensionType attribute

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by qqeasonchen** [comment]
@mroccyen nice~
