### ISSUE TITLE
[Doc] Sync update readme_zh with readme_en

### ISSUE THREAD

**Issue by qqeasonchen** [apache/incubator-eventmesh#891]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

Now the Chinese readme file[1] is far behaind with English[2], it needs to be updated to the latest. 

[1]https://github.com/apache/incubator-eventmesh/blob/master/README.zh-CN.md
[2]https://github.com/apache/incubator-eventmesh/blob/master/README.md

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by qqeasonchen** [comment]
@xiaoyang-sde can you find a new guy to contribute, and let him become a contributor?

**Comment by xiaoyang-sde** [comment]
> @xiaoyang-sde can you find a new guy to contribute, and let him become a contributor?

Yeah I contacted my classmates and one of them is willing to contribute. I will assign the issue to him.

**Comment by Markliniubility** [comment]
Hi I can do the contribution!
