### ISSUE TITLE
[Feature] Add consul registry

### ISSUE THREAD

**Issue by huyuanxin** [apache/incubator-eventmesh#900]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Feature Request

Add consul registry

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by qqeasonchen** [comment]
@huyuanxin welcome, good idea~
