### ISSUE TITLE
[Discuss] Add third-party dependency license of eventmesh-sdk-go

### ISSUE THREAD

**Issue by ruanwenjun** [apache/incubator-eventmesh#924]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Right now, our license check script doesn't check the dependency of non-Java package. So the CI can pass if we add new other language module like go, but we need to add the license and notice.

The `eventmesh-sdk-go` will not in our java release distribution, but we still need to announce we have these dependencies, I am not sure if we need to put these in our main distribution package.

Do we have any way to check other language dependency?

### Describe the solution you'd like

Add license and notice.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by qqeasonchen** [comment]
good idea~

**Comment by xwm1992** [comment]
- #958
