### ISSUE TITLE
[Enhancement] Update licenses files

### ISSUE THREAD

**Issue by xwm1992** [apache/incubator-eventmesh#958]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

Since we support the go SDK, we need to supply the third-party dependencies licenses for the go SDK.

### Describe the solution you'd like

Support the go SDK licenses and distinguish these licenses from java.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by ruanwenjun** [comment]
closed by #959
