### ISSUE TITLE
[Doc] Fix the abnormal display of pictures in some documents

### ISSUE THREAD

**Issue by walterlife** [apache/incubator-eventmesh#967]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

There are some abnormal pictures in some documents

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by tjx-outlook** [comment]
Hi, I'm a first-time contributor and I'd like to try this issue.

Is it still available? If so, could you please assign it to me?

Thanks!
