### ISSUE TITLE
[Doc] Fix gradlew license header

### ISSUE THREAD

**Issue by kirinzhu** [apache/incubator-eventmesh#979]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

The gradlew license header is incomplete, and needs to be fixed.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ruanwenjun** [comment]
I have submit #977 to fix this, please take a look.

**Comment by kirinzhu** [comment]
> I have submitted #977 to fix this, please take a look.

Yes, I noticed it. Could you please associate this issue with your pr? Thank you!
