### ISSUE TITLE
[Bug] Possible null pointer dereference

### ISSUE THREAD

**Issue by kirinzhu** [apache/incubator-eventmesh#981]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

master

### What happened

The return value from a method is dereferenced without a null check, and the return value of that method is one that should generally be checked for null. This may lead to a NullPointerException when the code is executed.

The bug appears in the package org.apache.eventmesh.runtime.core.protocol.http.processor many times.

### How to reproduce

It will happen if the return value is null.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by Evankirthi** [comment]
I would like to work on this issue

**Comment by qqeasonchen** [comment]
> I would like to work on this issue

Ok

**Comment by Prakhar047** [comment]
this is my very first contribution, can you please assign this task to me?

**Comment by Yamilini2000** [comment]
Can I work on this issue since it has been more than 2 weeks the issue unresolved
