### ISSUE TITLE
[Bug] Reliance on default encoding

### ISSUE THREAD

**Issue by kirinzhu** [apache/incubator-eventmesh#982]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

master

### What happened

Found a call to a method which will perform a byte to String (or String to byte) conversion, and will assume that the default platform encoding is suitable. This will cause the application behaviour to vary between platforms. Use an alternative API and specify a charset name or Charset object explicitly.

This bug happens in many packages.

### How to reproduce

It may happen if the program runs on other platforms.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by HeZean** [comment]
Hi, what's the status of this issue? I saw you checked "Yes I am willing to submit a PR!". May I work on it?
