### ISSUE TITLE
[Bug] ProducerGroupConf#equals doesn't work

### ISSUE THREAD

**Issue by kirinzhu** [apache/incubator-eventmesh#997]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

master

### What happened

This code compares java.lang.String objects for reference equality using the == or != operators instead of equals()

### How to reproduce

In module eventmesh-runtime
In class org.apache.eventmesh.runtime.core.consumergroup.ProducerGroupConf
In method org.apache.eventmesh.runtime.core.consumergroup.ProducerGroupConf.equals(Object)
In [line 50]

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pkyriakou23** [comment]
hi, i am curious all i have to do is to change `return groupName == that.groupName; ` to  `return groupName.(that.groupName); `  ?
