### ISSUE TITLE
[Enhancement] Consider implementing the Serializable interface

### ISSUE THREAD

**Issue by kirinzhu** [apache/incubator-eventmesh#999]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Enhancement Request

This class implements the Comparator interface. Maybe we consider whether or not it should also implement the Serializable interface. If a comparator is used to construct an ordered collection such as a TreeMap, then the TreeMap will be serializable only if the comparator is also serializable. Making them serializable is good defensive programming and could enhance the robustness of the program

### Describe the solution you'd like

In module eventmesh-runtime
In class org.apache.eventmesh.runtime.util.ValueComparator
At [lines 23-29]

Consider implementing the Serializable interface

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by misselvexu** [comment]
I will finish this issue .

**Comment by HeZean** [comment]
[WeOpen Star] working on it
